<?xml version="1.0"?>
<!DOCTYPE Meet [<!ELEMENT Meet (Track,Date,Quali,Race+)>
<!ELEMENT Track (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Quali (#PCDATA)>
<!ELEMENT Race (RaceNum,RaceName,RaceTime,RaceTimeDateUTC,Distance,RaceGrade,PrizeMoney1,PrizeMoney2,PrizeMoney3,PrizeMoney4,PrizeMoney5,PrizeMoney6,PrizeMoney7,PrizeMoney8,GOBIS,Hurdle,Handicap,TAB,GradeCode,Dog+)>
<!ELEMENT RaceNum (#PCDATA)>
<!ELEMENT RaceName (#PCDATA)>
<!ELEMENT RaceTime (#PCDATA)>
<!ELEMENT RaceTimeDateUTC (#PCDATA)>
<!ELEMENT Distance (#PCDATA)>
<!ELEMENT RaceGrade (#PCDATA)>
<!ELEMENT PrizeMoney1 (#PCDATA)>
<!ELEMENT PrizeMoney2 (#PCDATA)>
<!ELEMENT PrizeMoney3 (#PCDATA)>
<!ELEMENT PrizeMoney4 (#PCDATA)>
<!ELEMENT PrizeMoney5 (#PCDATA)>
<!ELEMENT PrizeMoney6 (#PCDATA)>
<!ELEMENT PrizeMoney7 (#PCDATA)>
<!ELEMENT PrizeMoney8 (#PCDATA)>
<!ELEMENT GOBIS (#PCDATA)>
<!ELEMENT Hurdle (#PCDATA)>
<!ELEMENT Handicap (#PCDATA)>
<!ELEMENT TAB (#PCDATA)>
<!ELEMENT GradeCode (#PCDATA)>
<!ELEMENT Dog (RaceBox,DogName,BestTime,DogHandicap,StartsTOT,StartsTTD,Trainer,Suburb,Owner,Sire,Dam,Colour,Sex,Whelped,DogGrade,DogGOBIS,DogPRIZE,Form+)>
<!ELEMENT RaceBox (#PCDATA)>
<!ELEMENT DogName (#PCDATA)>
<!ELEMENT BestTime (#PCDATA)>
<!ELEMENT DogHandicap (#PCDATA)>
<!ELEMENT StartsTOT (#PCDATA)>
<!ELEMENT StartsTTD (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>
<!ELEMENT Suburb (#PCDATA)>
<!ELEMENT Owner (#PCDATA)>
<!ELEMENT Sire (#PCDATA)>
<!ELEMENT Dam (#PCDATA)>
<!ELEMENT Colour (#PCDATA)>
<!ELEMENT Sex (#PCDATA)>
<!ELEMENT Whelped (#PCDATA)>
<!ELEMENT DogGrade (#PCDATA)>
<!ELEMENT DogGOBIS (#PCDATA)>
<!ELEMENT DogPRIZE (#PCDATA)>
<!ELEMENT Form (Place,FormBox,Weight,TrackCode,FormDistance,FormDate,FormGrade,FormHandicap,Margin,FirstSecond,DogTime,WinTime,BON,StartPrice,PIR,Split)>
<!ELEMENT Place (#PCDATA)>
<!ELEMENT FormBox (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT TrackCode (#PCDATA)>
<!ELEMENT FormDistance (#PCDATA)>
<!ELEMENT FormDate (#PCDATA)>
<!ELEMENT FormGrade (#PCDATA)>
<!ELEMENT FormHandicap (#PCDATA)>
<!ELEMENT Margin (#PCDATA)>
<!ELEMENT FirstSecond (#PCDATA)>
<!ELEMENT DogTime (#PCDATA)>
<!ELEMENT WinTime (#PCDATA)>
<!ELEMENT BON (#PCDATA)>
<!ELEMENT StartPrice (#PCDATA)>
<!ELEMENT PIR (#PCDATA)>
<!ELEMENT Split (#PCDATA)>
]>
<Meet id="153784459">
<Track>Meadows (MEP)</Track>
<Date>09 Nov 16</Date>
<Quali />
<Race id="168909154">
<RaceNum>1</RaceNum>
<RaceName>TAB EARLY QUADDIE</RaceName>
<RaceTime>11:55AM</RaceTime>
<RaceTimeDateUTC>09 Nov 16 12:55AM</RaceTimeDateUTC>
<Distance>525m</Distance>
<RaceGrade>Maiden</RaceGrade>
<PrizeMoney1>$990</PrizeMoney1>
<PrizeMoney2>$285</PrizeMoney2>
<PrizeMoney3>$140</PrizeMoney3>
<PrizeMoney4 />
<PrizeMoney5 />
<PrizeMoney6 />
<PrizeMoney7 />
<PrizeMoney8 />
<GOBIS />
<Hurdle />
<Handicap />
<TAB>TRI/QUIN R/D EXACTA PICK4</TAB>
<GradeCode>M</GradeCode>
<Dog id="1238510086">
<RaceBox>1</RaceBox>
<DogName>DYNA YATUL</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 10-0-3-3</StartsTOT>
<StartsTTD>Trk/Dst 5-0-2-1</StartsTTD>
<Trainer id="101324">Andrea Dailly</Trainer>
<Suburb>Corio</Suburb>
<Owner>Brendan Wheeler</Owner>
<Sire id="792880037">Sh Avatar</Sire>
<Dam id="-713683">Searle Bale</Dam>
<Colour>RF</Colour>
<Sex>D</Sex>
<Whelped>05 Nov 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>1275</DogPRIZE>
<Form>
<Place>2nd</Place>
<FormBox>7</FormBox>
<Weight>33.1</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>12Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>13.00L</Margin>
<FirstSecond>"Suffragette"</FirstSecond>
<DogTime>31.13</DogTime>
<WinTime>30.26</WinTime>
<BON>29.95</BON>
<StartPrice>$6.50</StartPrice>
<PIR>M/4543</PIR>
<Split>5.32</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>5</FormBox>
<Weight>33.0</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>19Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>3.25L</Margin>
<FirstSecond>"Blue Murray"</FirstSecond>
<DogTime>31.07</DogTime>
<WinTime>30.85</WinTime>
<BON>29.91</BON>
<StartPrice>$11.50</StartPrice>
<PIR>M/8532</PIR>
<Split>5.54</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>5</FormBox>
<Weight>32.6</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>26Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>6.00L</Margin>
<FirstSecond>"Surefire"</FirstSecond>
<DogTime>26.02</DogTime>
<WinTime>25.60</WinTime>
<BON>25.32</BON>
<StartPrice>$15.60</StartPrice>
<PIR>M/455</PIR>
<Split>6.80</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>7</FormBox>
<Weight>32.7</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>02Nov16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>5.00L</Margin>
<FirstSecond>"Aston Jesse"</FirstSecond>
<DogTime>26.26</DogTime>
<WinTime>25.91</WinTime>
<BON>25.64</BON>
<StartPrice>$19.20</StartPrice>
<PIR>M/533</PIR>
<Split>6.83</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>4</FormBox>
<Weight>32.9</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>06Nov16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>8.50L</Margin>
<FirstSecond>"Effective Comet"</FirstSecond>
<DogTime>30.51</DogTime>
<WinTime>29.93</WinTime>
<BON>29.48</BON>
<StartPrice>$7.90</StartPrice>
<PIR>M/5543</PIR>
<Split>5.30</Split>
</Form>
</Dog>
<Dog id="1092430060">
<RaceBox>2</RaceBox>
<DogName>DIAMA BALE</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 4-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 1-0-0-0</StartsTTD>
<Trainer id="118743">Darren Fisher</Trainer>
<Suburb>Lara</Suburb>
<Owner>Darcie Fisher</Owner>
<Sire id="-622536">David Bale</Sire>
<Dam id="-710125">Ucme Typhoon</Dam>
<Colour>RBD</Colour>
<Sex>B</Sex>
<Whelped>14 Aug 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>5th</Place>
<FormBox>2</FormBox>
<Weight>23.8</Weight>
<TrackCode>WBL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>18Aug16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>7.50L</Margin>
<FirstSecond>"Arolok Lil' Gal"</FirstSecond>
<DogTime>26.10</DogTime>
<WinTime>25.60</WinTime>
<BON>25.31</BON>
<StartPrice>$2.90</StartPrice>
<PIR>M/455</PIR>
<Split>6.85</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>3</FormBox>
<Weight>23.6</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>24Aug16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>15.00L</Margin>
<FirstSecond>"Lektra Fire"</FirstSecond>
<DogTime>31.58</DogTime>
<WinTime>30.58</WinTime>
<BON>29.99</BON>
<StartPrice>$5.10</StartPrice>
<PIR>M/6777</PIR>
<Split>5.40</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>5</FormBox>
<Weight>23.4</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>28Aug16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>14.00L</Margin>
<FirstSecond>"Omega Lucy"</FirstSecond>
<DogTime>26.04</DogTime>
<WinTime>25.09</WinTime>
<BON>24.99</BON>
<StartPrice>$4.40</StartPrice>
<PIR>M/866</PIR>
<Split>5.71</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>6</FormBox>
<Weight>23.4</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>600</FormDistance>
<FormDate>31Aug16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>13.00L</Margin>
<FirstSecond>"Tink Allen"</FirstSecond>
<DogTime>36.37</DogTime>
<WinTime>35.51</WinTime>
<BON>34.86</BON>
<StartPrice>$9.00</StartPrice>
<PIR>M/7766</PIR>
<Split>9.71</Split>
</Form>
<Form />
</Dog>
<Dog id="1238510089">
<RaceBox>3</RaceBox>
<DogName>DYNA BEVLIN</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 0-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="101324">Andrea Dailly</Trainer>
<Suburb>Corio</Suburb>
<Owner>Brendan Wheeler</Owner>
<Sire id="792880037">Sh Avatar</Sire>
<Dam id="-713683">Searle Bale</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>05 Nov 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form />
<Form />
<Form />
<Form />
<Form />
</Dog>
<Dog id="1007830006">
<RaceBox>4</RaceBox>
<DogName>TALANJEE LOU</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 8-0-2-1</StartsTOT>
<StartsTTD>Trk/Dst 2-0-0-1</StartsTTD>
<Trainer id="111877">Gerard Taylor</Trainer>
<Suburb>Allansford</Suburb>
<Owner>Gerard Taylor</Owner>
<Sire id="-9071">Kinloch Brae</Sire>
<Dam id="-234683">Thomeli Diamond</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>28 May 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>710</DogPRIZE>
<Form>
<Place>6th</Place>
<FormBox>3</FormBox>
<Weight>27.1</Weight>
<TrackCode>WBL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>29Sep16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>10.00L</Margin>
<FirstSecond>"Dream Future"</FirstSecond>
<DogTime>26.34</DogTime>
<WinTime>25.65</WinTime>
<BON>25.30</BON>
<StartPrice>$12.10</StartPrice>
<PIR>M/546</PIR>
<Split>6.88</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>6</FormBox>
<Weight>27.6</Weight>
<TrackCode>HOR</TrackCode>
<FormDistance>480</FormDistance>
<FormDate>04Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>13.00L</Margin>
<FirstSecond>"Moneypenny"</FirstSecond>
<DogTime>28.29</DogTime>
<WinTime>27.40</WinTime>
<BON>27.40</BON>
<StartPrice>$17.90</StartPrice>
<PIR>M/566</PIR>
<Split>6.68</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>4</FormBox>
<Weight>27.6</Weight>
<TrackCode>HOR</TrackCode>
<FormDistance>480</FormDistance>
<FormDate>11Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>3.5L</Margin>
<FirstSecond>"Crazed Blaze"</FirstSecond>
<DogTime>27.78</DogTime>
<WinTime>27.55</WinTime>
<BON>27.37</BON>
<StartPrice>$5.30</StartPrice>
<PIR>M/222</PIR>
<Split>6.56</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>6</FormBox>
<Weight>27.4</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>26Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>3.5L</Margin>
<FirstSecond>"Queen Yuna"</FirstSecond>
<DogTime>31.16</DogTime>
<WinTime>30.92</WinTime>
<BON>30.29</BON>
<StartPrice>$9.00</StartPrice>
<PIR>M/5665</PIR>
<Split>5.36</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>5</FormBox>
<Weight>27.4</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>02Nov16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>2.75L</Margin>
<FirstSecond>"Kappow"</FirstSecond>
<DogTime>30.81</DogTime>
<WinTime>30.63</WinTime>
<BON>30.14</BON>
<StartPrice>$20.50</StartPrice>
<PIR>M/2333</PIR>
<Split>5.18</Split>
</Form>
</Dog>
<Dog id="1238530081">
<RaceBox>5</RaceBox>
<DogName>DYNA CALDER</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 4-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 2-0-0-0</StartsTTD>
<Trainer id="101324">Andrea Dailly</Trainer>
<Suburb>Corio</Suburb>
<Owner>Brendan Wheeler</Owner>
<Sire id="792880037">Sh Avatar</Sire>
<Dam id="-713683">Searle Bale</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>05 Nov 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>6th</Place>
<FormBox>7</FormBox>
<Weight>30.6</Weight>
<TrackCode>WBL</TrackCode>
<FormDistance>390</FormDistance>
<FormDate>08Sep16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Miss Popularity"</FirstSecond>
<DogTime>22.99</DogTime>
<WinTime>22.54</WinTime>
<BON>22.30</BON>
<StartPrice>$9.20</StartPrice>
<PIR>M/67</PIR>
<Split>8.90</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>3</FormBox>
<Weight>30.4</Weight>
<TrackCode>WBL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>15Sep16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>5.50L</Margin>
<FirstSecond>"Dyna Zaynabi"</FirstSecond>
<DogTime>25.99</DogTime>
<WinTime>25.61</WinTime>
<BON>25.42</BON>
<StartPrice>$9.70</StartPrice>
<PIR>M/344</PIR>
<Split>6.95</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>8</FormBox>
<Weight>31.2</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>28Sep16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>13.00L</Margin>
<FirstSecond>"Shima Bar"</FirstSecond>
<DogTime>31.07</DogTime>
<WinTime>30.17</WinTime>
<BON>30.17</BON>
<StartPrice>$27.00</StartPrice>
<PIR>M/7776</PIR>
<Split>5.32</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>1</FormBox>
<Weight>30.3</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>12Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>6.00L</Margin>
<FirstSecond>"Olfina Allen"</FirstSecond>
<DogTime>31.09</DogTime>
<WinTime>30.69</WinTime>
<BON>29.95</BON>
<StartPrice>$5.80</StartPrice>
<PIR>S/5544</PIR>
<Split>5.44</Split>
</Form>
<Form />
</Dog>
<Dog id="1206250046">
<RaceBox>6</RaceBox>
<DogName>BERRIDALE BUDDIE</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 1-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="106709">Scott Stefanos</Trainer>
<Suburb>Longwood</Suburb>
<Owner>Stephen Robinson</Owner>
<Sire id="-399888">Swift Fancy</Sire>
<Dam id="-537505">Berridale Queen</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>23 Oct 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>6th</Place>
<FormBox>4</FormBox>
<Weight>36.4</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>31Oct16</FormDate>
<FormGrade>All Maiden</FormGrade>
<FormHandicap />
<Margin>8.50L</Margin>
<FirstSecond>"Another Spritely"</FirstSecond>
<DogTime>26.48</DogTime>
<WinTime>25.90</WinTime>
<BON>25.75</BON>
<StartPrice>$6.50</StartPrice>
<PIR>M/666</PIR>
<Split>6.90</Split>
</Form>
<Form />
<Form />
<Form />
<Form />
</Dog>
<Dog id="1591690037">
<RaceBox>7</RaceBox>
<DogName>ENVY HEIST</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 0-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="101324">Andrea Dailly</Trainer>
<Suburb>Corio</Suburb>
<Owner>Craig Davis</Owner>
<Sire id="-3386">Talk's Cheap</Sire>
<Dam id="-721328">Hot Genetics</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>25 Apr 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form />
<Form />
<Form />
<Form />
<Form />
</Dog>
<Dog id="1238510076">
<RaceBox>8</RaceBox>
<DogName>HADVEL BALE</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 2-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="101324">Andrea Dailly</Trainer>
<Suburb>Corio</Suburb>
<Owner>Paul Wheeler</Owner>
<Sire id="259130003">Adios Alonso</Sire>
<Dam id="-622212">Bala Bale</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>05 Nov 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>6th</Place>
<FormBox>7</FormBox>
<Weight>36.5</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>26Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>9.00L</Margin>
<FirstSecond>"Mimosa"</FirstSecond>
<DogTime>26.12</DogTime>
<WinTime>25.50</WinTime>
<BON>25.32</BON>
<StartPrice>$10.20</StartPrice>
<PIR>S/777</PIR>
<Split>6.87</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>3</FormBox>
<Weight>37.2</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>02Nov16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>19.00L</Margin>
<FirstSecond>"Aston Jesse"</FirstSecond>
<DogTime>27.18</DogTime>
<WinTime>25.91</WinTime>
<BON>25.64</BON>
<StartPrice>$18.50</StartPrice>
<PIR>S/778</PIR>
<Split>6.89</Split>
</Form>
<Form />
<Form />
<Form />
</Dog>
<Dog id="1591720049">
<RaceBox>9</RaceBox>
<DogName>APEX PRO Res.</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 0-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="101324">Andrea Dailly</Trainer>
<Suburb>Corio</Suburb>
<Owner>Craig Davis</Owner>
<Sire id="-3386">Talk's Cheap</Sire>
<Dam id="-721328">Hot Genetics</Dam>
<Colour>RBD</Colour>
<Sex>D</Sex>
<Whelped>25 Apr 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form />
<Form />
<Form />
<Form />
<Form />
</Dog>
<Dog id="1137360008">
<RaceBox>10</RaceBox>
<DogName>JACK THE FIPA Res.</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 19-0-4-4</StartsTOT>
<StartsTTD>Trk/Dst 1-0-1-0</StartsTTD>
<Trainer id="112922">Phillip Tanti</Trainer>
<Suburb>Kings Park</Suburb>
<Owner>Team Five Paws Syn Synd L Elford,J Palmer,B McDade,C Abbott,A Palmer,E Rinaldi</Owner>
<Sire id="-132414">Surf Lorian</Sire>
<Dam id="-712988">Five Paws</Dam>
<Colour>RBD</Colour>
<Sex>D</Sex>
<Whelped>01 Sep 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>1235</DogPRIZE>
<Form>
<Place>2nd</Place>
<FormBox>1</FormBox>
<Weight>35.4</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>25Sep16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>4.25L</Margin>
<FirstSecond>"Mister Ebby"</FirstSecond>
<DogTime>30.17</DogTime>
<WinTime>29.87</WinTime>
<BON>29.39</BON>
<StartPrice>$7.40</StartPrice>
<PIR>M/7322</PIR>
<Split>5.37</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>8</FormBox>
<Weight>35.3</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>02Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>2.50L</Margin>
<FirstSecond>"Duty Free"</FirstSecond>
<DogTime>30.22</DogTime>
<WinTime>30.06</WinTime>
<BON>29.34</BON>
<StartPrice>$9.70</StartPrice>
<PIR>M/4333</PIR>
<Split>5.38</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>7</FormBox>
<Weight>35.2</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>09Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>16.00L</Margin>
<FirstSecond>"Shez Rocking"</FirstSecond>
<DogTime>31.38</DogTime>
<WinTime>30.28</WinTime>
<BON>29.51</BON>
<StartPrice>$11.20</StartPrice>
<PIR>M/6778</PIR>
<Split>5.34</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>4</FormBox>
<Weight>35.4</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>01Nov16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>3.25L</Margin>
<FirstSecond>"Zipping Luna"</FirstSecond>
<DogTime>30.33</DogTime>
<WinTime>30.12</WinTime>
<BON>29.62</BON>
<StartPrice>$14.10</StartPrice>
<PIR>M/5444</PIR>
<Split>5.28</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>4</FormBox>
<Weight>35.5</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>06Nov16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>7.00L</Margin>
<FirstSecond>"El Mirage"</FirstSecond>
<DogTime>30.61</DogTime>
<WinTime>30.13</WinTime>
<BON>29.48</BON>
<StartPrice>$24.50</StartPrice>
<PIR>M/3333</PIR>
<Split>5.30</Split>
</Form>
</Dog>
</Race>
<Race id="168909148">
<RaceNum>2</RaceNum>
<RaceName>AJS CORPORATION HT1</RaceName>
<RaceTime>12:14PM</RaceTime>
<RaceTimeDateUTC>09 Nov 16 01:14AM</RaceTimeDateUTC>
<Distance>525m</Distance>
<RaceGrade>Mixed 6/7 Heat</RaceGrade>
<PrizeMoney1>$1325</PrizeMoney1>
<PrizeMoney2>$375</PrizeMoney2>
<PrizeMoney3>$190</PrizeMoney3>
<PrizeMoney4 />
<PrizeMoney5 />
<PrizeMoney6 />
<PrizeMoney7 />
<PrizeMoney8 />
<GOBIS />
<Hurdle />
<Handicap />
<TAB>TRI/QUIN R/D EXACTA PICK4</TAB>
<GradeCode>X67H</GradeCode>
<Dog id="1206210171">
<RaceBox>1</RaceBox>
<DogName>GABRIELLE ALLEN</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 11-1-2-2</StartsTOT>
<StartsTTD>Trk/Dst 5-0-2-1</StartsTTD>
<Trainer id="101324">Andrea Dailly</Trainer>
<Suburb>Corio</Suburb>
<Owner>Janice Wheeler</Owner>
<Sire id="792880037">Sh Avatar</Sire>
<Dam id="-713681">Quiz Bale</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>30 Oct 14</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>2650</DogPRIZE>
<Form>
<Place>6th</Place>
<FormBox>3</FormBox>
<Weight>25.7</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>07Oct16</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>3.5L</Margin>
<FirstSecond>"Weasley Grange"</FirstSecond>
<DogTime>26.37</DogTime>
<WinTime>26.14</WinTime>
<BON>25.68</BON>
<StartPrice>$5.00</StartPrice>
<PIR>M/665</PIR>
<Split>6.75</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>4</FormBox>
<Weight>25.0</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>15Oct16</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>8.00L</Margin>
<FirstSecond>"Tedesco"</FirstSecond>
<DogTime>30.56</DogTime>
<WinTime>30.02</WinTime>
<BON>29.90</BON>
<StartPrice>$17.30</StartPrice>
<PIR>M/3344</PIR>
<Split>5.16</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>4</FormBox>
<Weight>25.4</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>19Oct16</FormDate>
<FormGrade>Restricted Win Heat</FormGrade>
<FormHandicap />
<Margin>3.00L</Margin>
<FirstSecond>"Woofa Combo"</FirstSecond>
<DogTime>30.45</DogTime>
<WinTime>30.25</WinTime>
<BON>29.91</BON>
<StartPrice>$4.10</StartPrice>
<PIR>Q/3433</PIR>
<Split>5.12</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>4</FormBox>
<Weight>25.1</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>29Oct16</FormDate>
<FormGrade>Restricted Win Final</FormGrade>
<FormHandicap />
<Margin>8.00L</Margin>
<FirstSecond>"Tedesco"</FirstSecond>
<DogTime>30.52</DogTime>
<WinTime>29.98</WinTime>
<BON>29.54</BON>
<StartPrice>$22.80</StartPrice>
<PIR>M/7555</PIR>
<Split>5.22</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>6</FormBox>
<Weight>25.8</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>06Nov16</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>9.00L</Margin>
<FirstSecond>"Aston Gisle"</FirstSecond>
<DogTime>30.08</DogTime>
<WinTime>29.48</WinTime>
<BON>29.48</BON>
<StartPrice>$5.30</StartPrice>
<PIR>M/5665</PIR>
<Split>5.16</Split>
</Form>
</Dog>
<Dog id="1362060081">
<RaceBox>2</RaceBox>
<DogName>NIGHT KING</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 8-2-2-0</StartsTOT>
<StartsTTD>Trk/Dst 3-0-1-0</StartsTTD>
<Trainer id="130148">Tina Womann</Trainer>
<Suburb>Lara</Suburb>
<Owner>Bartolo And Earl Synd R Bartolo,C Earl,G Bartolo,L Earl</Owner>
<Sire id="-168350">Collision</Sire>
<Dam id="-478907">Miss Black Fern</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>28 Jan 15</Whelped>
<DogGrade>6</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>11750</DogPRIZE>
<Form>
<Place>1st</Place>
<FormBox>2</FormBox>
<Weight>35.5</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>30Aug16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>1.5L</Margin>
<FirstSecond>"Vulcan"</FirstSecond>
<DogTime>26.04</DogTime>
<WinTime>26.04</WinTime>
<BON>25.88</BON>
<StartPrice>$2.40</StartPrice>
<PIR>Q/211</PIR>
<Split>6.60</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>3</FormBox>
<Weight>35.6</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>06Sep16</FormDate>
<FormGrade>Maiden Semi Final</FormGrade>
<FormHandicap />
<Margin>9.00L</Margin>
<FirstSecond>"Miss Morrisset"</FirstSecond>
<DogTime>26.64</DogTime>
<WinTime>26.04</WinTime>
<BON>25.77</BON>
<StartPrice>$3.40</StartPrice>
<PIR>S/877</PIR>
<Split>7.04</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>6</FormBox>
<Weight>36.3</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>15Oct16</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>10.00L</Margin>
<FirstSecond>"Tedesco"</FirstSecond>
<DogTime>30.70</DogTime>
<WinTime>30.02</WinTime>
<BON>29.90</BON>
<StartPrice>$15.90</StartPrice>
<PIR>S/8865</PIR>
<Split>5.28</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>4</FormBox>
<Weight>36.1</Weight>
<TrackCode>SHP</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>24Oct16</FormDate>
<FormGrade>S/E Heat</FormGrade>
<FormHandicap />
<Margin>0.50L</Margin>
<FirstSecond>"Vista King"</FirstSecond>
<DogTime>25.41</DogTime>
<WinTime>25.38</WinTime>
<BON>25.35</BON>
<StartPrice>$23.60</StartPrice>
<PIR>M/222</PIR>
<Split>6.68</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>4</FormBox>
<Weight>36.0</Weight>
<TrackCode>SHP</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>29Oct16</FormDate>
<FormGrade>S/E Final</FormGrade>
<FormHandicap />
<Margin>3.00L</Margin>
<FirstSecond>"Aston Ah Chee"</FirstSecond>
<DogTime>25.16</DogTime>
<WinTime>25.16</WinTime>
<BON>25.16</BON>
<StartPrice>$28.30</StartPrice>
<PIR>M/221</PIR>
<Split>6.65</Split>
</Form>
</Dog>
<Dog id="960960005">
<RaceBox>3</RaceBox>
<DogName>CUTIE ALLIYAH</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 7-1-0-1</StartsTOT>
<StartsTTD>Trk/Dst 1-0-0-1</StartsTTD>
<Trainer id="117088">Adrian Caramia</Trainer>
<Suburb>Melton</Suburb>
<Owner>A &amp; K Chisholm Synd A Chisholm,K Chisholm</Owner>
<Sire id="-210522">Cosmic Rumble</Sire>
<Dam id="-467813">After Party</Dam>
<Colour>BD</Colour>
<Sex>B</Sex>
<Whelped>27 Apr 14</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>1665</DogPRIZE>
<Form>
<Place>3rd</Place>
<FormBox>5</FormBox>
<Weight>28.1</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>13Jul16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>7.50L</Margin>
<FirstSecond>"Qura Allen"</FirstSecond>
<DogTime>30.90</DogTime>
<WinTime>30.40</WinTime>
<BON>30.21</BON>
<StartPrice>$31.00</StartPrice>
<PIR>M/3334</PIR>
<Split>5.25</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>8</FormBox>
<Weight>28.1</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>24Jul16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>13.00L</Margin>
<FirstSecond>"What Iam Iam"</FirstSecond>
<DogTime>30.48</DogTime>
<WinTime>29.64</WinTime>
<BON>29.46</BON>
<StartPrice>$21.90</StartPrice>
<PIR>S/8776</PIR>
<Split>5.64</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>1</FormBox>
<Weight>28.1</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>595</FormDistance>
<FormDate>07Aug16</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin>6.00L</Margin>
<FirstSecond>"Selena"</FirstSecond>
<DogTime>34.66</DogTime>
<WinTime>34.66</WinTime>
<BON>34.06</BON>
<StartPrice>$6.90</StartPrice>
<PIR>S/1111</PIR>
<Split>9.40</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>6</FormBox>
<Weight>28.4</Weight>
<TrackCode>BEN</TrackCode>
<FormDistance>660</FormDistance>
<FormDate>17Aug16</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>3.75L</Margin>
<FirstSecond>"Cashino"</FirstSecond>
<DogTime>38.46</DogTime>
<WinTime>38.20</WinTime>
<BON>38.20</BON>
<StartPrice>$10.10</StartPrice>
<PIR>S/222</PIR>
<Split>15.49</Split>
</Form>
<Form>
<Place>F</Place>
<FormBox>4</FormBox>
<Weight>28.1</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>23Oct16</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin />
<FirstSecond>"Brooklyn Skye"</FirstSecond>
<DogTime>0.00</DogTime>
<WinTime>29.85</WinTime>
<BON>29.49</BON>
<StartPrice>$5.00</StartPrice>
<PIR>S/765</PIR>
<Split>5.31</Split>
</Form>
</Dog>
<Dog id="1155400013">
<RaceBox>4</RaceBox>
<DogName>GALLOPING FANTOM</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 25-1-8-1</StartsTOT>
<StartsTTD>Trk/Dst 3-0-1-0</StartsTTD>
<Trainer id="125087">Robert Conway</Trainer>
<Suburb>Bunyip</Suburb>
<Owner>Robert Conway</Owner>
<Sire id="-710086">Black Magic Opal</Sire>
<Dam id="-318074">Sips Her Latte</Dam>
<Colour>F</Colour>
<Sex>D</Sex>
<Whelped>21 Oct 14</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>3475</DogPRIZE>
<Form>
<Place>5th</Place>
<FormBox>3</FormBox>
<Weight>32.9</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>22Oct16</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>8.50L</Margin>
<FirstSecond>"Bro Sam's Hook"</FirstSecond>
<DogTime>31.74</DogTime>
<WinTime>31.15</WinTime>
<BON>30.64</BON>
<StartPrice>$33.40</StartPrice>
<PIR>Q/2233</PIR>
<Split>4.99</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>4</FormBox>
<Weight>32.9</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>26Oct16</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Iron Anda"</FirstSecond>
<DogTime>31.04</DogTime>
<WinTime>30.59</WinTime>
<BON>30.29</BON>
<StartPrice>$38.60</StartPrice>
<PIR>M/6566</PIR>
<Split>5.38</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>5</FormBox>
<Weight>32.9</Weight>
<TrackCode>HVL</TrackCode>
<FormDistance>350</FormDistance>
<FormDate>30Oct16</FormDate>
<FormGrade>Restricted Win Heat</FormGrade>
<FormHandicap />
<Margin>11.00L</Margin>
<FirstSecond>"Blackjack's Back"</FirstSecond>
<DogTime>19.88</DogTime>
<WinTime>19.18</WinTime>
<BON>18.89</BON>
<StartPrice>$37.70</StartPrice>
<PIR>M/4</PIR>
<Split>6.72</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>1</FormBox>
<Weight>32.7</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>02Nov16</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Spring To Wyn"</FirstSecond>
<DogTime>30.82</DogTime>
<WinTime>30.37</WinTime>
<BON>30.14</BON>
<StartPrice>$14.30</StartPrice>
<PIR>Q/2222</PIR>
<Split>5.26</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>4</FormBox>
<Weight>32.6</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>05Nov16</FormDate>
<FormGrade>Restricted Win Heat</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Audacious Angel"</FirstSecond>
<DogTime>31.23</DogTime>
<WinTime>30.79</WinTime>
<BON>30.49</BON>
<StartPrice>$18.80</StartPrice>
<PIR>M/5422</PIR>
<Split>4.99</Split>
</Form>
</Dog>
<Dog id="1160770038">
<RaceBox>5</RaceBox>