<?xml version="1.0"?>
<!DOCTYPE Meet [<!ELEMENT Meet (Track,Date,Quali,Race+)>
<!ELEMENT Track (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Quali (#PCDATA)>
<!ELEMENT Race (RaceNum,RaceName,RaceTime,RaceTimeDateUTC,Distance,RaceGrade,PrizeMoney1,PrizeMoney2,PrizeMoney3,PrizeMoney4,PrizeMoney5,PrizeMoney6,PrizeMoney7,PrizeMoney8,GOBIS,Hurdle,Handicap,TAB,GradeCode,Dog+)>
<!ELEMENT RaceNum (#PCDATA)>
<!ELEMENT RaceName (#PCDATA)>
<!ELEMENT RaceTime (#PCDATA)>
<!ELEMENT RaceTimeDateUTC (#PCDATA)>
<!ELEMENT Distance (#PCDATA)>
<!ELEMENT RaceGrade (#PCDATA)>
<!ELEMENT PrizeMoney1 (#PCDATA)>
<!ELEMENT PrizeMoney2 (#PCDATA)>
<!ELEMENT PrizeMoney3 (#PCDATA)>
<!ELEMENT PrizeMoney4 (#PCDATA)>
<!ELEMENT PrizeMoney5 (#PCDATA)>
<!ELEMENT PrizeMoney6 (#PCDATA)>
<!ELEMENT PrizeMoney7 (#PCDATA)>
<!ELEMENT PrizeMoney8 (#PCDATA)>
<!ELEMENT GOBIS (#PCDATA)>
<!ELEMENT Hurdle (#PCDATA)>
<!ELEMENT Handicap (#PCDATA)>
<!ELEMENT TAB (#PCDATA)>
<!ELEMENT GradeCode (#PCDATA)>
<!ELEMENT Dog (RaceBox,DogName,BestTime,DogHandicap,StartsTOT,StartsTTD,Trainer,Suburb,Owner,Sire,Dam,Colour,Sex,Whelped,DogGrade,DogGOBIS,DogPRIZE,Form+)>
<!ELEMENT RaceBox (#PCDATA)>
<!ELEMENT DogName (#PCDATA)>
<!ELEMENT BestTime (#PCDATA)>
<!ELEMENT DogHandicap (#PCDATA)>
<!ELEMENT StartsTOT (#PCDATA)>
<!ELEMENT StartsTTD (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>
<!ELEMENT Suburb (#PCDATA)>
<!ELEMENT Owner (#PCDATA)>
<!ELEMENT Sire (#PCDATA)>
<!ELEMENT Dam (#PCDATA)>
<!ELEMENT Colour (#PCDATA)>
<!ELEMENT Sex (#PCDATA)>
<!ELEMENT Whelped (#PCDATA)>
<!ELEMENT DogGrade (#PCDATA)>
<!ELEMENT DogGOBIS (#PCDATA)>
<!ELEMENT DogPRIZE (#PCDATA)>
<!ELEMENT Form (Place,FormBox,Weight,TrackCode,FormDistance,FormDate,FormGrade,FormHandicap,Margin,FirstSecond,DogTime,WinTime,BON,StartPrice,PIR,Split)>
<!ELEMENT Place (#PCDATA)>
<!ELEMENT FormBox (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT TrackCode (#PCDATA)>
<!ELEMENT FormDistance (#PCDATA)>
<!ELEMENT FormDate (#PCDATA)>
<!ELEMENT FormGrade (#PCDATA)>
<!ELEMENT FormHandicap (#PCDATA)>
<!ELEMENT Margin (#PCDATA)>
<!ELEMENT FirstSecond (#PCDATA)>
<!ELEMENT DogTime (#PCDATA)>
<!ELEMENT WinTime (#PCDATA)>
<!ELEMENT BON (#PCDATA)>
<!ELEMENT StartPrice (#PCDATA)>
<!ELEMENT PIR (#PCDATA)>
<!ELEMENT Split (#PCDATA)>
]>
<Meet id="212709069">
<Track>Warragul</Track>
<Date>01 Jun 17</Date>
<Quali />
<Race id="225565736">
<RaceNum>1</RaceNum>
<RaceName>AUSTRALIAN QUALITY PET FOODS</RaceName>
<RaceTime>12:12PM</RaceTime>
<RaceTimeDateUTC>01 Jun 17 02:12AM</RaceTimeDateUTC>
<Distance>400m</Distance>
<RaceGrade>Tier 3 - Maiden</RaceGrade>
<PrizeMoney1>$500</PrizeMoney1>
<PrizeMoney2>$140</PrizeMoney2>
<PrizeMoney3>$70</PrizeMoney3>
<PrizeMoney4 />
<PrizeMoney5 />
<PrizeMoney6 />
<PrizeMoney7 />
<PrizeMoney8 />
<GOBIS />
<Hurdle />
<Handicap />
<TAB>TRI/QUIN R/D EXACTA PICK4</TAB>
<GradeCode>T3-M</GradeCode>
<Dog id="1107900040">
<RaceBox>1</RaceBox>
<DogName>DO LOOKS COUNT</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 6-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="109900">Terrence Churchill</Trainer>
<Suburb>Allambee</Suburb>
<Owner>Terrence Churchill</Owner>
<Sire id="-88028">Premier Boloney</Sire>
<Dam id="-715498">Kristingee</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>22 Sep 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>6th</Place>
<FormBox>1</FormBox>
<Weight>33.2</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>14Mar17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>6.00L</Margin>
<FirstSecond>"Merl's Angel"</FirstSecond>
<DogTime>23.49</DogTime>
<WinTime>23.09</WinTime>
<BON>22.62</BON>
<StartPrice>$4.70</StartPrice>
<PIR>M/56</PIR>
<Split>8.72</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>4</FormBox>
<Weight>33.6</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>390</FormDistance>
<FormDate>25Mar17</FormDate>
<FormGrade>Maiden Qualifying Heat</FormGrade>
<FormHandicap />
<Margin>2.50L</Margin>
<FirstSecond>"Regal Tycoon"</FirstSecond>
<DogTime>22.67</DogTime>
<WinTime>22.67</WinTime>
<BON>22.06</BON>
<StartPrice />
<PIR />
<Split>8.68</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>3</FormBox>
<Weight>33.8</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>390</FormDistance>
<FormDate>05Apr17</FormDate>
<FormGrade>Maiden Quali Final</FormGrade>
<FormHandicap />
<Margin>12.00L</Margin>
<FirstSecond>"Tiggerlong Ray"</FirstSecond>
<DogTime>23.24</DogTime>
<WinTime>22.44</WinTime>
<BON>22.12</BON>
<StartPrice>$35.00</StartPrice>
<PIR>M/76</PIR>
<Split>8.95</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>7</FormBox>
<Weight>31.9</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>395</FormDistance>
<FormDate>08May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>14.00L</Margin>
<FirstSecond>"Vane Power"</FirstSecond>
<DogTime>24.08</DogTime>
<WinTime>23.10</WinTime>
<BON>22.89</BON>
<StartPrice>$8.20</StartPrice>
<PIR>M/777</PIR>
<Split>5.20</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>3</FormBox>
<Weight>31.7</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>395</FormDistance>
<FormDate>12May17</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>12.00L</Margin>
<FirstSecond>"Select Danger"</FirstSecond>
<DogTime>23.95</DogTime>
<WinTime>23.18</WinTime>
<BON>22.85</BON>
<StartPrice>$21.00</StartPrice>
<PIR>M/334</PIR>
<Split>5.10</Split>
</Form>
</Dog>
<Dog id="1967110007">
<RaceBox>2</RaceBox>
<DogName>OFF HER ROCKER</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 11-0-2-2</StartsTOT>
<StartsTTD>Trk/Dst 6-0-1-1</StartsTTD>
<Trainer id="112668">Rachael Busuttil</Trainer>
<Suburb>Kilmany</Suburb>
<Owner>Rachael Busuttil</Owner>
<Sire id="-737921">Luca Neveelk</Sire>
<Dam id="-44218">Dirty Bit</Dam>
<Colour>BKW</Colour>
<Sex>B</Sex>
<Whelped>10 Aug 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>420</DogPRIZE>
<Form>
<Place>2nd</Place>
<FormBox>4</FormBox>
<Weight>27.1</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>04May17</FormDate>
<FormGrade>All Maiden</FormGrade>
<FormHandicap />
<Margin>0.25L</Margin>
<FirstSecond>"Kruzin' Cripps"</FirstSecond>
<DogTime>23.39</DogTime>
<WinTime>23.38</WinTime>
<BON>22.85</BON>
<StartPrice>$2.00</StartPrice>
<PIR>Q/11</PIR>
<Split>8.53</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>8</FormBox>
<Weight>27.2</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>395</FormDistance>
<FormDate>08May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>3.5L</Margin>
<FirstSecond>"Vane Power"</FirstSecond>
<DogTime>23.34</DogTime>
<WinTime>23.10</WinTime>
<BON>22.89</BON>
<StartPrice>$2.40</StartPrice>
<PIR>Q/112</PIR>
<Split>4.88</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>1</FormBox>
<Weight>27.2</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>11May17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>8.50L</Margin>
<FirstSecond>"Zara's Pride"</FirstSecond>
<DogTime>24.04</DogTime>
<WinTime>23.46</WinTime>
<BON>22.76</BON>
<StartPrice>$2.40</StartPrice>
<PIR>M/84</PIR>
<Split>9.03</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>7</FormBox>
<Weight>27.4</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>15May17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>5.00L</Margin>
<FirstSecond>"Blue Addiction"</FirstSecond>
<DogTime>19.37</DogTime>
<WinTime>19.04</WinTime>
<BON>18.39</BON>
<StartPrice>$3.10</StartPrice>
<PIR>Q/16</PIR>
<Split>4.89</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>7</FormBox>
<Weight>27.0</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>29May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>17.00L</Margin>
<FirstSecond>"Dukestar"</FirstSecond>
<DogTime>19.65</DogTime>
<WinTime>18.50</WinTime>
<BON>18.28</BON>
<StartPrice>$5.00</StartPrice>
<PIR>M/47</PIR>
<Split>5.00</Split>
</Form>
</Dog>
<Dog id="1295000000">
<RaceBox>3</RaceBox>
<DogName>BELJAY GALAXY</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 9-0-2-2</StartsTOT>
<StartsTTD>Trk/Dst 3-0-2-0</StartsTTD>
<Trainer id="113907">Adam Scott</Trainer>
<Suburb>Pearcedale</Suburb>
<Owner>Tartan Lodge Synd L Scott,J Leonard-Scott,B Scott,A Scott</Owner>
<Sire id="-210522">Cosmic Rumble</Sire>
<Dam id="-276010">Hope To Salute</Dam>
<Colour>WBK</Colour>
<Sex>D</Sex>
<Whelped>02 Dec 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>610</DogPRIZE>
<Form>
<Place>3rd</Place>
<FormBox>7</FormBox>
<Weight>32.9</Weight>
<TrackCode>CRN</TrackCode>
<FormDistance>520</FormDistance>
<FormDate>07Mar17</FormDate>
<FormGrade>Maiden Semi Final</FormGrade>
<FormHandicap />
<Margin>8.50L</Margin>
<FirstSecond>"Dr. Gidget"</FirstSecond>
<DogTime>30.89</DogTime>
<WinTime>30.32</WinTime>
<BON>30.32</BON>
<StartPrice>$43.60</StartPrice>
<PIR>M/1233</PIR>
<Split>5.47</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>6</FormBox>
<Weight>33.6</Weight>
<TrackCode>CRN</TrackCode>
<FormDistance>520</FormDistance>
<FormDate>15Mar17</FormDate>
<FormGrade>Maiden Final</FormGrade>
<FormHandicap />
<Margin>26.00L</Margin>
<FirstSecond>"Trouper"</FirstSecond>
<DogTime>32.20</DogTime>
<WinTime>30.45</WinTime>
<BON>29.99</BON>
<StartPrice>$62.00</StartPrice>
<PIR>Q/2788</PIR>
<Split>5.49</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>3</FormBox>
<Weight>33.3</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>04May17</FormDate>
<FormGrade>All Maiden</FormGrade>
<FormHandicap />
<Margin>3.00L</Margin>
<FirstSecond>"Pistol"</FirstSecond>
<DogTime>23.44</DogTime>
<WinTime>23.24</WinTime>
<BON>22.85</BON>
<StartPrice>$4.60</StartPrice>
<PIR>M/11</PIR>
<Split>8.49</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>4</FormBox>
<Weight>33.1</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>11May17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>14.00L</Margin>
<FirstSecond>"Zara's Pride"</FirstSecond>
<DogTime>24.41</DogTime>
<WinTime>23.46</WinTime>
<BON>22.76</BON>
<StartPrice>$7.40</StartPrice>
<PIR>M/28</PIR>
<Split>8.49</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>6</FormBox>
<Weight>32.5</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>25May17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>1.00L</Margin>
<FirstSecond>"Joyce's Choice"</FirstSecond>
<DogTime>23.38</DogTime>
<WinTime>23.32</WinTime>
<BON>22.60</BON>
<StartPrice>$7.00</StartPrice>
<PIR>M/12</PIR>
<Split>8.45</Split>
</Form>
</Dog>
<Dog id="1451560004">
<RaceBox>4</RaceBox>
<DogName>SHREK'S CAPRI</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 7-0-1-1</StartsTOT>
<StartsTTD>Trk/Dst 3-0-0-1</StartsTTD>
<Trainer id="22989">Robert Lesjak</Trainer>
<Suburb>Nyora</Suburb>
<Owner>Amanda Lesjak</Owner>
<Sire id="-327320">Pat's Dunroaming</Sire>
<Dam id="-624796">Shrek's Queen</Dam>
<Colour>F</Colour>
<Sex>B</Sex>
<Whelped>26 Mar 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>210</DogPRIZE>
<Form>
<Place>7th</Place>
<FormBox>3</FormBox>
<Weight>29.9</Weight>
<TrackCode>CRN</TrackCode>
<FormDistance>311</FormDistance>
<FormDate>04Feb17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>10.00L</Margin>
<FirstSecond>"First Target"</FirstSecond>
<DogTime>18.69</DogTime>
<WinTime>18.00</WinTime>
<BON>17.77</BON>
<StartPrice>$31.20</StartPrice>
<PIR>M/66</PIR>
<Split>10.05</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>6</FormBox>
<Weight>28.9</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>04May17</FormDate>
<FormGrade>All Maiden</FormGrade>
<FormHandicap />
<Margin>7.50L</Margin>
<FirstSecond>"Raging Inferno"</FirstSecond>
<DogTime>23.37</DogTime>
<WinTime>22.85</WinTime>
<BON>22.85</BON>
<StartPrice>$18.70</StartPrice>
<PIR>M/22</PIR>
<Split>8.47</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>3</FormBox>
<Weight>28.5</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>08May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>4.75L</Margin>
<FirstSecond>"Zipping Penny"</FirstSecond>
<DogTime>18.89</DogTime>
<WinTime>18.57</WinTime>
<BON>18.34</BON>
<StartPrice>$5.80</StartPrice>
<PIR>M/22</PIR>
<Split>4.90</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>5</FormBox>
<Weight>29.2</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>18May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>14.00L</Margin>
<FirstSecond>"Scarlet Twice"</FirstSecond>
<DogTime>24.08</DogTime>
<WinTime>23.11</WinTime>
<BON>22.43</BON>
<StartPrice>$18.50</StartPrice>
<PIR>M/66</PIR>
<Split>8.81</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>2</FormBox>
<Weight>29.3</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>25May17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>2.00L</Margin>
<FirstSecond>"Joyce's Choice"</FirstSecond>
<DogTime>23.45</DogTime>
<WinTime>23.32</WinTime>
<BON>22.60</BON>
<StartPrice>$15.00</StartPrice>
<PIR>M/21</PIR>
<Split>8.47</Split>
</Form>
</Dog>
<Dog id="1184090003">
<RaceBox>5</RaceBox>
<DogName>SARGENT</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 5-0-0-3</StartsTOT>
<StartsTTD>Trk/Dst 4-0-0-3</StartsTTD>
<Trainer id="119398">Susan Corrigan</Trainer>
<Suburb>clyde</Suburb>
<Owner>Joseph Abela</Owner>
<Sire id="-210522">Cosmic Rumble</Sire>
<Dam id="-331835">Kercem</Dam>
<Colour>BKW</Colour>
<Sex>D</Sex>
<Whelped>29 Sep 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>210</DogPRIZE>
<Form>
<Place>3rd</Place>
<FormBox>2</FormBox>
<Weight>33.8</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>29Sep16</FormDate>
<FormGrade>All Maiden</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Brandeen Beauty"</FirstSecond>
<DogTime>23.34</DogTime>
<WinTime>22.88</WinTime>
<BON>22.88</BON>
<StartPrice>$3.80</StartPrice>
<PIR>S/33</PIR>
<Split>8.70</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>6</FormBox>
<Weight>33.5</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>11Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>12.00L</Margin>
<FirstSecond>"Tito Mojito"</FirstSecond>
<DogTime>26.86</DogTime>
<WinTime>26.08</WinTime>
<BON>25.67</BON>
<StartPrice>$24.10</StartPrice>
<PIR>S/867</PIR>
<Split>6.84</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>8</FormBox>
<Weight>34.8</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>06Apr17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>2.75L</Margin>
<FirstSecond>"Adala Prince/Jetyra Eruption"</FirstSecond>
<DogTime>23.22</DogTime>
<WinTime>23.03</WinTime>
<BON>22.55</BON>
<StartPrice>$2.60</StartPrice>
<PIR>M/55</PIR>
<Split>8.65</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>4</FormBox>
<Weight>34.4</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>13Apr17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>27.00L</Margin>
<FirstSecond>"Aminya Shadow"</FirstSecond>
<DogTime>24.93</DogTime>
<WinTime>23.09</WinTime>
<BON>22.58</BON>
<StartPrice>$2.40</StartPrice>
<PIR>M/88</PIR>
<Split>9.11</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>3</FormBox>
<Weight>34.2</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>27Apr17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>12.00L</Margin>
<FirstSecond>"Major Think"</FirstSecond>
<DogTime>23.59</DogTime>
<WinTime>22.76</WinTime>
<BON>22.76</BON>
<StartPrice>$6.20</StartPrice>
<PIR>M/44</PIR>
<Split>8.58</Split>
</Form>
</Dog>
<Dog id="1698360026">
<RaceBox>6</RaceBox>
<DogName>SHOGUN SAMMY</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 11-0-0-2</StartsTOT>
<StartsTTD>Trk/Dst 1-0-0-0</StartsTTD>
<Trainer id="105747">Deborah Churchill</Trainer>
<Suburb>Allambee</Suburb>
<Owner>Deborah Churchill</Owner>
<Sire id="-88028">Premier Boloney</Sire>
<Dam id="-722007">Treadstone Daisy</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>24 Apr 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>140</DogPRIZE>
<Form>
<Place>3rd</Place>
<FormBox>8</FormBox>
<Weight>28.9</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>01May17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>4.75L</Margin>
<FirstSecond>"Right Off Spot"</FirstSecond>
<DogTime>18.82</DogTime>
<WinTime>18.50</WinTime>
<BON>18.29</BON>
<StartPrice>$13.20</StartPrice>
<PIR>M/23</PIR>
<Split>4.98</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>5</FormBox>
<Weight>28.5</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>05May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>11.00L</Margin>
<FirstSecond>"Jurassic Saphire"</FirstSecond>
<DogTime>19.22</DogTime>
<WinTime>18.46</WinTime>
<BON>17.88</BON>
<StartPrice>$15.30</StartPrice>
<PIR>S/64</PIR>
<Split>5.01</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>4</FormBox>
<Weight>28.8</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>08May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>5.50L</Margin>
<FirstSecond>"Where's Marcia"</FirstSecond>
<DogTime>19.00</DogTime>
<WinTime>18.64</WinTime>
<BON>18.34</BON>
<StartPrice>$7.60</StartPrice>
<PIR>M/53</PIR>
<Split>5.00</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>6</FormBox>
<Weight>28.8</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>395</FormDistance>
<FormDate>12May17</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>21.00L</Margin>
<FirstSecond>"Select Danger"</FirstSecond>
<DogTime>24.62</DogTime>
<WinTime>23.18</WinTime>
<BON>22.85</BON>
<StartPrice>$9.20</StartPrice>
<PIR>M/777</PIR>
<Split>5.23</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>2</FormBox>
<Weight>29.2</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>29May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>8.00L</Margin>
<FirstSecond>"Dukestar"</FirstSecond>
<DogTime>19.06</DogTime>
<WinTime>18.50</WinTime>
<BON>18.28</BON>
<StartPrice>$13.70</StartPrice>
<PIR>M/53</PIR>
<Split>5.00</Split>
</Form>
</Dog>
<Dog id="1549980022">
<RaceBox>7</RaceBox>
<DogName>TAIL INSPECTOR</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 12-0-0-1</StartsTOT>
<StartsTTD>Trk/Dst 2-0-0-0</StartsTTD>
<Trainer id="66678">Jordan Carrodus-Nagy</Trainer>
<Suburb>Traralgon</Suburb>
<Owner>Jordan Carrodus-Nagy</Owner>
<Sire id="-88028">Premier Boloney</Sire>
<Dam id="-630529">Tabby's Tiger</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>27 Mar 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>70</DogPRIZE>
<Form>
<Place>4th</Place>
<FormBox>1</FormBox>
<Weight>28.2</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>16Feb17</FormDate>
<FormGrade>All Maiden</FormGrade>
<FormHandicap />
<Margin>8.50L</Margin>
<FirstSecond>"Battle Hook"</FirstSecond>
<DogTime>23.63</DogTime>
<WinTime>23.04</WinTime>
<BON>22.78</BON>
<StartPrice>$17.20</StartPrice>
<PIR>M/75</PIR>
<Split>8.79</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>3</FormBox>
<Weight>28.7</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>26Feb17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>23.00L</Margin>
<FirstSecond>"Contemptuous"</FirstSecond>
<DogTime>26.99</DogTime>
<WinTime>25.39</WinTime>
<BON>24.94</BON>
<StartPrice>$30.70</StartPrice>
<PIR>S/888</PIR>
<Split>5.64</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>3</FormBox>
<Weight>28.8</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>11Mar17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>11.00L</Margin>
<FirstSecond>"Apila Moola"</FirstSecond>
<DogTime>19.01</DogTime>
<WinTime>18.28</WinTime>
<BON>17.88</BON>
<StartPrice>$27.70</StartPrice>
<PIR>S/76</PIR>
<Split>5.05</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>1</FormBox>
<Weight>29.2</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>08May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>9.00L</Margin>
<FirstSecond>"Zipping Penny"</FirstSecond>
<DogTime>19.20</DogTime>
<WinTime>18.57</WinTime>
<BON>18.34</BON>
<StartPrice>$16.80</StartPrice>
<PIR>S/77</PIR>
<Split>5.14</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>8</FormBox>
<Weight>29.0</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>15May17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>3.00L</Margin>
<FirstSecond>"Blue Addiction"</FirstSecond>
<DogTime>19.23</DogTime>
<WinTime>19.04</WinTime>
<BON>18.39</BON>
<StartPrice>$27.70</StartPrice>
<PIR>S/74</PIR>
<Split>5.09</Split>
</Form>
</Dog>
<Dog id="778670054">
<RaceBox>8</RaceBox>
<DogName>PARIE SHIRAZ</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 42-1-6-2</StartsTOT>
<StartsTTD>Trk/Dst 4-0-1-1</StartsTTD>
<Trainer id="198680">Sharlene Whitford</Trainer>
<Suburb>willow Grove</Suburb>
<Owner>Trevor Whitford</Owner>
<Sire id="-309259">El Grand Senor</Sire>
<Dam id="-725753">New Moon Rising</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>09 Feb 14</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>1480</DogPRIZE>
<Form>
<Place>2nd</Place>
<FormBox>6</FormBox>
<Weight>35.0</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>04May17</FormDate>
<FormGrade>All Maiden</FormGrade>
<FormHandicap />
<Margin>1.25L</Margin>
<FirstSecond>"Galloping Benny"</FirstSecond>
<DogTime>23.27</DogTime>
<WinTime>23.19</WinTime>
<BON>22.85</BON>
<StartPrice>$29.30</StartPrice>
<PIR>S/52</PIR>
<Split>8.84</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>2</FormBox>
<Weight>34.8</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>11May17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>3.25L</Margin>
<FirstSecond>"Zara's Pride"</FirstSecond>
<DogTime>23.67</DogTime>
<WinTime>23.46</WinTime>
<BON>22.76</BON>
<StartPrice>$14.30</StartPrice>
<PIR>S/75</PIR>
<Split>8.96</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>2</FormBox>
<Weight>34.8</Weight>
<TrackCode>BEN</TrackCode>
<FormDistance>425</FormDistance>
<FormDate>17May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>4.50L</Margin>
<FirstSecond>"Duty Sheet"</FirstSecond>
<DogTime>24.80</DogTime>
<WinTime>24.49</WinTime>
<BON>23.82</BON>
<StartPrice>$12.90</StartPrice>
<PIR>S/886</PIR>
<Split>7.22</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>7</FormBox>
<Weight>35.0</Weight>
<TrackCode>HVL</TrackCode>
<FormDistance>350</FormDistance>
<FormDate>26May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>1.00L</Margin>
<FirstSecond>"Folding Green"</FirstSecond>
<DogTime>19.97</DogTime>
<WinTime>19.90</WinTime>
<BON>19.28</BON>
<StartPrice>$9.60</StartPrice>
<PIR>M/4</PIR>
<Split>6.84</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>3</FormBox>
<Weight>34.7</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>395</FormDistance>
<FormDate>29May17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>1.75L</Margin>
<FirstSecond>"Sunset Queen"</FirstSecond>
<DogTime>23.47</DogTime>
<WinTime>23.47</WinTime>
<BON>22.94</BON>
<StartPrice>$20.80</StartPrice>
<PIR>S/654</PIR>
<Split>5.12</Split>
</Form>
</Dog>
<Dog id="1698360025">
<RaceBox>9</RaceBox>
<DogName>ZAHHAK ZAC Res.</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 5-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 1-0-0-0</StartsTTD>
<Trainer id="105747">Deborah Churchill</Trainer>
<Suburb>Allambee</Suburb>
<Owner>Deborah Churchill</Owner>
<Sire id="-88028">Premier Boloney</Sire>
<Dam id="-722007">Treadstone Daisy</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>24 Apr 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>6th</Place>
<FormBox>6</FormBox>
<Weight>30.6</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>16Feb17</FormDate>
<FormGrade>All Maiden</FormGrade>
<FormHandicap />
<Margin>24.00L</Margin>
<FirstSecond>"On The Rebound"</FirstSecond>
<DogTime>24.48</DogTime>
<WinTime>22.86</WinTime>
<BON>22.78</BON>
<StartPrice>$6.00</StartPrice>
<PIR>S/56</PIR>
<Split>8.73</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>5</FormBox>
<Weight>29.9</Weight>
<TrackCode>HVL</TrackCode>
<FormDistance>300</FormDistance>
<FormDate>19Mar17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>11.00L</Margin>
<FirstSecond>"Peninsula Panda"</FirstSecond>
<DogTime>17.64</DogTime>
<WinTime>16.87</WinTime>
<BON>16.72</BON>
<StartPrice>$14.70</StartPrice>
<PIR>M/4</PIR>
<Split>4.07</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>2</FormBox>
<Weight>30.1</Weight>
<TrackCode>HVL</TrackCode>
<FormDistance>300</FormDistance>
<FormDate>24Mar17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>9.00L</Margin>
<FirstSecond>"Jaso"</FirstSecond>
<DogTime>17.65</DogTime>
<WinTime>17.05</WinTime>
<BON>16.70</BON>
<StartPrice>$24.40</StartPrice>
<PIR>M/4</PIR>
<Split>4.09</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>8</FormBox>
<Weight>30.2</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>03Apr17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>19.00L</Margin>
<FirstSecond>"Simbarea"</FirstSecond>
<DogTime>19.93</DogTime>
<WinTime>18.66</WinTime>
<BON>18.11</BON>
<StartPrice>$9.40</StartPrice>
<PIR>S/78</PIR>
<Split>5.07</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>4</FormBox>
<Weight>30.7</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>395</FormDistance>
<FormDate>15May17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>12.00L</Margin>
<FirstSecond>"Zelemar Cocoa"</FirstSecond>
<DogTime>24.19</DogTime>
<WinTime>23.38</WinTime>
<BON>23.08</BON>
<StartPrice>$33.40</StartPrice>
<PIR>M/576</PIR>
<Split>5.10</Split>
</Form>
</Dog>
<Dog id="1394990007">
<RaceBox>10</RaceBox>
<DogName>ATIGRADO Res.</DogName>
<BestTime>FSTD</BestTime>
<DogHandicap />
<StartsTOT>Starts 4-0-0-1</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="62311">Jeanette Imlach</Trainer>
<Suburb>Pearcedale</Suburb>
<Owner>Jeanette Imlach</Owner>
<Sire id="-498750">Traction Control</Sire>
<Dam id="-734805">My Girl Honey</Dam>
<Colour>BD</Colour>
<Sex>B</Sex>
<Whelped>09 Feb 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>140</DogPRIZE>
<Form>
<Place>7th</Place>
<FormBox>6</FormBox>
<Weight>22.5</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>16Feb17</FormDate>
<FormGrade>All Maiden</FormGrade>
<FormHandicap />
<Margin>27.00L</Margin>
<FirstSecond>"Rapanui Revival"</FirstSecond>
<DogTime>27.94</DogTime>
<WinTime>26.08</WinTime>
<BON>25.86</BON>
<StartPrice>$19.10</StartPrice>
<PIR>M/577</PIR>
<Split>6.95</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>2</FormBox>
<Weight>23.3</Weight>
<TrackCode>CRN</TrackCode>
<FormDistance>311</FormDistance>
<FormDate>22Mar17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Newfire Drewie"</FirstSecond>
<DogTime>18.47</DogTime>
<WinTime>18.04</WinTime>
<BON>17.80</BON>
<StartPrice>$35.00</StartPrice>
<PIR>M/32</PIR>
<Split>9.88</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>8</FormBox>
<Weight>23.6</Weight>
<TrackCode>CRN</TrackCode>
<FormDistance>311</FormDistance>
<FormDate>10Apr17</FormDate>
<FormGrade>Maiden Qualifying Heat</FormGrade>
<FormHandicap />
<Margin>2.00L</Margin>
<FirstSecond>"Elite Eliana"</FirstSecond>
<DogTime>18.38</DogTime>
<WinTime>18.38</WinTime>
<BON>18.09</BON>
<StartPrice />
<PIR />
<Split>9.97</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>7</FormBox>
<Weight>23.9</Weight>
<TrackCode>CRN</TrackCode>
<FormDistance>311</FormDistance>
<FormDate>19Apr17</FormDate>
<FormGrade>Maiden Quali Final</FormGrade>
<FormHandicap />
<Margin>7.00L</Margin>
<FirstSecond>"Always Alone"</FirstSecond>
<DogTime>18.44</DogTime>
<WinTime>17.98</WinTime>
<BON>17.76</BON>
<StartPrice>$20.00</StartPrice>
<PIR>M/44</PIR>
<Split>9.96</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>8</FormBox>
<Weight>24.0</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>27Apr17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>16.00L</Margin>
<FirstSecond>"Dreamy Julian"</FirstSecond>
<DogTime>27.27</DogTime>
<WinTime>26.20</WinTime>
<BON>26.06</BON>
<StartPrice>$12.20</StartPrice>
<PIR>M/534</PIR>
<Split>6.67</Split>
</Form>
</Dog>
</Race>
<Race id="225565742">
<RaceNum>2</RaceNum>
<RaceName>MORLAND'S MEATS</RaceName>
<RaceTime>12:30PM</RaceTime>
<RaceTimeDateUTC>01 Jun 17 02:30AM</RaceTimeDateUTC>
<Distance>460m</Distance>
<RaceGrade>Tier 3 - Maiden</RaceGrade>
<PrizeMoney1>$500</PrizeMoney1>
<PrizeMoney2>$140</PrizeMoney2>
<PrizeMoney3>$70</PrizeMoney3>
<PrizeMoney4 />
<PrizeMoney5 />
<PrizeMoney6 />
<PrizeMoney7 />
<PrizeMoney8 />
<GOBIS />
<Hurdle />
<Handicap />
<TAB>TRI/QUIN R/D EXACTA PICK4</TAB>
<GradeCode>T3-M</GradeCode>
<Dog id="1590380005">
<RaceBox>1</RaceBox>
<DogName>CHARLIE HAZE</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 18-0-4-3</StartsTOT>
<StartsTTD>Trk/Dst 4-0-0-2</StartsTTD>
<Trainer id="131936">Sharyn Combridge</Trainer>
<Suburb>Junction Village</Suburb>
<Owner>Sharyn Combridge</Owner>
<Sire id="-717288">Surf Mail</Sire>
<Dam id="-736107">Mrs. Crunkett</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>12 May 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>1130</DogPRIZE>
<Form>
<Place>2nd</Place>
<FormBox>1</FormBox>
<Weight>33.2</Weight>