<?xml version="1.0"?>
<!DOCTYPE Meet [<!ELEMENT Meet (Track,Date,Quali,Race+)>
<!ELEMENT Track (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Quali (#PCDATA)>
<!ELEMENT Race (RaceNum,RaceName,RaceTime,RaceTimeDateUTC,Distance,RaceGrade,PrizeMoney1,PrizeMoney2,PrizeMoney3,PrizeMoney4,PrizeMoney5,PrizeMoney6,PrizeMoney7,PrizeMoney8,GOBIS,Hurdle,Handicap,TAB,GradeCode,Dog+)>
<!ELEMENT RaceNum (#PCDATA)>
<!ELEMENT RaceName (#PCDATA)>
<!ELEMENT RaceTime (#PCDATA)>
<!ELEMENT RaceTimeDateUTC (#PCDATA)>
<!ELEMENT Distance (#PCDATA)>
<!ELEMENT RaceGrade (#PCDATA)>
<!ELEMENT PrizeMoney1 (#PCDATA)>
<!ELEMENT PrizeMoney2 (#PCDATA)>
<!ELEMENT PrizeMoney3 (#PCDATA)>
<!ELEMENT PrizeMoney4 (#PCDATA)>
<!ELEMENT PrizeMoney5 (#PCDATA)>
<!ELEMENT PrizeMoney6 (#PCDATA)>
<!ELEMENT PrizeMoney7 (#PCDATA)>
<!ELEMENT PrizeMoney8 (#PCDATA)>
<!ELEMENT GOBIS (#PCDATA)>
<!ELEMENT Hurdle (#PCDATA)>
<!ELEMENT Handicap (#PCDATA)>
<!ELEMENT TAB (#PCDATA)>
<!ELEMENT GradeCode (#PCDATA)>
<!ELEMENT Dog (RaceBox,DogName,BestTime,DogHandicap,StartsTOT,StartsTTD,Trainer,Suburb,Owner,Sire,Dam,Colour,Sex,Whelped,DogGrade,DogGOBIS,DogPRIZE,Form+)>
<!ELEMENT RaceBox (#PCDATA)>
<!ELEMENT DogName (#PCDATA)>
<!ELEMENT BestTime (#PCDATA)>
<!ELEMENT DogHandicap (#PCDATA)>
<!ELEMENT StartsTOT (#PCDATA)>
<!ELEMENT StartsTTD (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>
<!ELEMENT Suburb (#PCDATA)>
<!ELEMENT Owner (#PCDATA)>
<!ELEMENT Sire (#PCDATA)>
<!ELEMENT Dam (#PCDATA)>
<!ELEMENT Colour (#PCDATA)>
<!ELEMENT Sex (#PCDATA)>
<!ELEMENT Whelped (#PCDATA)>
<!ELEMENT DogGrade (#PCDATA)>
<!ELEMENT DogGOBIS (#PCDATA)>
<!ELEMENT DogPRIZE (#PCDATA)>
<!ELEMENT Form (Place,FormBox,Weight,TrackCode,FormDistance,FormDate,FormGrade,FormHandicap,Margin,FirstSecond,DogTime,WinTime,BON,StartPrice,PIR,Split)>
<!ELEMENT Place (#PCDATA)>
<!ELEMENT FormBox (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT TrackCode (#PCDATA)>
<!ELEMENT FormDistance (#PCDATA)>
<!ELEMENT FormDate (#PCDATA)>
<!ELEMENT FormGrade (#PCDATA)>
<!ELEMENT FormHandicap (#PCDATA)>
<!ELEMENT Margin (#PCDATA)>
<!ELEMENT FirstSecond (#PCDATA)>
<!ELEMENT DogTime (#PCDATA)>
<!ELEMENT WinTime (#PCDATA)>
<!ELEMENT BON (#PCDATA)>
<!ELEMENT StartPrice (#PCDATA)>
<!ELEMENT PIR (#PCDATA)>
<!ELEMENT Split (#PCDATA)>
]>
<Meet id="228125976">
<Track>Ballarat</Track>
<Date>29 Nov 17</Date>
<Quali />
<Race id="277640676">
<RaceNum>1</RaceNum>
<RaceName>ENERGIS SMART ENERGY SOLUTIONS</RaceName>
<RaceTime>06:58PM</RaceTime>
<RaceTimeDateUTC>29 Nov 17 07:58AM</RaceTimeDateUTC>
<Distance>545m</Distance>
<RaceGrade>Mixed 6/7</RaceGrade>
<PrizeMoney1>$1405</PrizeMoney1>
<PrizeMoney2>$400</PrizeMoney2>
<PrizeMoney3>$200</PrizeMoney3>
<PrizeMoney4 />
<PrizeMoney5 />
<PrizeMoney6 />
<PrizeMoney7 />
<PrizeMoney8 />
<GOBIS />
<Hurdle />
<Handicap />
<TAB>TRI/QUIN R/D EXACTA PICK4</TAB>
<GradeCode>X67</GradeCode>
<Dog id="1199510035">
<RaceBox>1</RaceBox>
<DogName>PURE CASCADE</DogName>
<BestTime>FSTD</BestTime>
<DogHandicap />
<StartsTOT>Starts 32-1-1-5</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="19286">Bradley Chapman</Trainer>
<Suburb>St Albans</Suburb>
<Owner>Blood Sweat And Beers Synd B Chapman,M Reid,N Hallinan,B Frater,C Venables</Owner>
<Sire id="-631999">Nolen</Sire>
<Dam id="-625606">Queen Of Black</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>03 Nov 14</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>1365</DogPRIZE>
<Form>
<Place>2nd</Place>
<FormBox>8</FormBox>
<Weight>27.7</Weight>
<TrackCode>CRN</TrackCode>
<FormDistance>311</FormDistance>
<FormDate>09Oct17</FormDate>
<FormGrade>Maiden Qualifying Heat</FormGrade>
<FormHandicap />
<Margin>1.00L</Margin>
<FirstSecond>"Dyna Misty"</FirstSecond>
<DogTime>18.39</DogTime>
<WinTime>18.32</WinTime>
<BON>18.04</BON>
<StartPrice />
<PIR />
<Split />
</Form>
<Form>
<Place>7th</Place>
<FormBox>5</FormBox>
<Weight>27.8</Weight>
<TrackCode>CRN</TrackCode>
<FormDistance>311</FormDistance>
<FormDate>18Oct17</FormDate>
<FormGrade>Maiden Final</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Crocodile Dunphy"</FirstSecond>
<DogTime>18.75</DogTime>
<WinTime>18.32</WinTime>
<BON>17.69</BON>
<StartPrice>$31.00</StartPrice>
<PIR>M/47</PIR>
<Split>10.16</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>4</FormBox>
<Weight>27.9</Weight>
<TrackCode>SHP</TrackCode>
<FormDistance>390</FormDistance>
<FormDate>30Oct17</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>9.00L</Margin>
<FirstSecond>"My Names Chelsea"</FirstSecond>
<DogTime>23.45</DogTime>
<WinTime>22.83</WinTime>
<BON>22.62</BON>
<StartPrice>$27.40</StartPrice>
<PIR>M/77</PIR>
<Split>9.13</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>1</FormBox>
<Weight>28.1</Weight>
<TrackCode>BEN</TrackCode>
<FormDistance>500</FormDistance>
<FormDate>08Nov17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>2.75L</Margin>
<FirstSecond>"Fairly Legal"</FirstSecond>
<DogTime>28.96</DogTime>
<WinTime>28.96</WinTime>
<BON>28.33</BON>
<StartPrice>$15.50</StartPrice>
<PIR>M/111</PIR>
<Split>6.75</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>7</FormBox>
<Weight>28.3</Weight>
<TrackCode>BEN</TrackCode>
<FormDistance>500</FormDistance>
<FormDate>15Nov17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>12.00L</Margin>
<FirstSecond>"Dynastic Ruler"</FirstSecond>
<DogTime>29.16</DogTime>
<WinTime>28.33</WinTime>
<BON>28.33</BON>
<StartPrice>$21.80</StartPrice>
<PIR>M/455</PIR>
<Split>6.86</Split>
</Form>
</Dog>
<Dog id="1474730039">
<RaceBox>2</RaceBox>
<DogName>BUCA DOLL</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 39-2-3-7</StartsTOT>
<StartsTTD>Trk/Dst 4-0-0-2</StartsTTD>
<Trainer id="122700">Jason Tolson</Trainer>
<Suburb>Adelaide Lead</Suburb>
<Owner>Jennifer Torr</Owner>
<Sire id="-107648">Cosmic Chief</Sire>
<Dam id="-109475">Chardonnay Doll</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>10 Dec 14</Whelped>
<DogGrade>6</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>2460</DogPRIZE>
<Form>
<Place>5th</Place>
<FormBox>7</FormBox>
<Weight>26.1</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>545</FormDistance>
<FormDate>16Oct17</FormDate>
<FormGrade>Tier 3 - Restricted Win</FormGrade>
<FormHandicap />
<Margin>7.50L</Margin>
<FirstSecond>"Strength To Wyn"</FirstSecond>
<DogTime>32.02</DogTime>
<WinTime>31.50</WinTime>
<BON>31.42</BON>
<StartPrice>$25.50</StartPrice>
<PIR>S/4455</PIR>
<Split>7.00</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>8</FormBox>
<Weight>26.0</Weight>
<TrackCode>BEN</TrackCode>
<FormDistance>500</FormDistance>
<FormDate>25Oct17</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin>0.50L</Margin>
<FirstSecond>"Sienna's Lilly"</FirstSecond>
<DogTime>28.99</DogTime>
<WinTime>28.96</WinTime>
<BON>28.54</BON>
<StartPrice>$13.20</StartPrice>
<PIR>M/543</PIR>
<Split>6.87</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>1</FormBox>
<Weight>26.0</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>545</FormDistance>
<FormDate>30Oct17</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin>4.25L</Margin>
<FirstSecond>"Cette To Dance"</FirstSecond>
<DogTime>32.04</DogTime>
<WinTime>31.75</WinTime>
<BON>31.75</BON>
<StartPrice>$9.60</StartPrice>
<PIR>S/3344</PIR>
<Split>6.94</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>5</FormBox>
<Weight>26.0</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>545</FormDistance>
<FormDate>06Nov17</FormDate>
<FormGrade>Tier 3 - Restricted Win</FormGrade>
<FormHandicap />
<Margin>2.75L</Margin>
<FirstSecond>"Swoop And Peck"</FirstSecond>
<DogTime>31.75</DogTime>
<WinTime>31.57</WinTime>
<BON>31.45</BON>
<StartPrice>$15.60</StartPrice>
<PIR>M/4444</PIR>
<Split>6.94</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>6</FormBox>
<Weight>26.5</Weight>
<TrackCode>BEN</TrackCode>
<FormDistance>500</FormDistance>
<FormDate>24Nov17</FormDate>
<FormGrade>Mixed 6/7 Heat</FormGrade>
<FormHandicap />
<Margin>22.00L</Margin>
<FirstSecond>"Soda Kid"</FirstSecond>
<DogTime>29.45</DogTime>
<WinTime>27.96</WinTime>
<BON>27.96</BON>
<StartPrice>$44.10</StartPrice>
<PIR>S/887</PIR>
<Split>7.19</Split>
</Form>
</Dog>
<Dog id="1540960002">
<RaceBox>3</RaceBox>
<DogName>I'M A PRINCESS</DogName>
<BestTime>FSTD</BestTime>
<DogHandicap />
<StartsTOT>Starts 14-2-2-4</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="108961">Dustin Drew</Trainer>
<Suburb>Dennington</Suburb>
<Owner>Robert Walsh</Owner>
<Sire id="-558149">Cape Hawke</Sire>
<Dam id="-319863">Jamaican Ruby</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>06 Apr 15</Whelped>
<DogGrade>6</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>5540</DogPRIZE>
<Form>
<Place>4th</Place>
<FormBox>4</FormBox>
<Weight>27.0</Weight>
<TrackCode>WBL</TrackCode>
<FormDistance>650</FormDistance>
<FormDate>31Aug17</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin>6.00L</Margin>
<FirstSecond>"Celestial Folk"</FirstSecond>
<DogTime>38.02</DogTime>
<WinTime>37.64</WinTime>
<BON>37.64</BON>
<StartPrice>$25.10</StartPrice>
<PIR>M/755</PIR>
<Split>18.95</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>3</FormBox>
<Weight>26.7</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>725</FormDistance>
<FormDate>20Sep17</FormDate>
<FormGrade>Novice Grade 7</FormGrade>
<FormHandicap />
<Margin>0.50L</Margin>
<FirstSecond>"Sprint Tee"</FirstSecond>
<DogTime>44.01</DogTime>
<WinTime>43.99</WinTime>
<BON>43.99</BON>
<StartPrice>$2.20</StartPrice>
<PIR>M/6664</PIR>
<Split>5.22</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>8</FormBox>
<Weight>26.4</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>715</FormDistance>
<FormDate>08Oct17</FormDate>
<FormGrade>Novice Grade 7</FormGrade>
<FormHandicap />
<Margin>21.00L</Margin>
<FirstSecond>"Jobes Return"</FirstSecond>
<DogTime>44.12</DogTime>
<WinTime>42.70</WinTime>
<BON>42.70</BON>
<StartPrice>$2.50</StartPrice>
<PIR>M/7476</PIR>
<Split>6.55</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>3</FormBox>
<Weight>26.8</Weight>
<TrackCode>WBL</TrackCode>
<FormDistance>650</FormDistance>
<FormDate>02Nov17</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin>1.25L</Margin>
<FirstSecond>"Star Fever"</FirstSecond>
<DogTime>37.85</DogTime>
<WinTime>37.85</WinTime>
<BON>37.77</BON>
<StartPrice>$4.10</StartPrice>
<PIR>M/543</PIR>
<Split>17.95</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>2</FormBox>
<Weight>26.8</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>660</FormDistance>
<FormDate>08Nov17</FormDate>
<FormGrade>Special Event</FormGrade>
<FormHandicap />
<Margin>2.00L</Margin>
<FirstSecond>"Packey Keeping"</FirstSecond>
<DogTime>38.52</DogTime>
<WinTime>38.38</WinTime>
<BON>38.38</BON>
<StartPrice>$23.00</StartPrice>
<PIR>M/6665</PIR>
<Split>13.45</Split>
</Form>
</Dog>
<Dog id="1540980015">
<RaceBox>4</RaceBox>
<DogName>ANNIE LAVA</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 14-2-3-2</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="132196">Raymond Drew</Trainer>
<Suburb>Dennington</Suburb>
<Owner>Lava Street Synd N Mugavin,J Mugavin,T Lee,J Mugavin</Owner>
<Sire id="404750001">Djays Octane</Sire>
<Dam id="-626721">Born On Lava</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>11 Feb 15</Whelped>
<DogGrade>6</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>3850</DogPRIZE>
<Form>
<Place>4th</Place>
<FormBox>6</FormBox>
<Weight>26.6</Weight>
<TrackCode>WBL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>19Oct17</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>7.00L</Margin>
<FirstSecond>"Far Sighted"</FirstSecond>
<DogTime>26.13</DogTime>
<WinTime>25.66</WinTime>
<BON>25.55</BON>
<StartPrice>$2.80</StartPrice>
<PIR>M/734</PIR>
<Split>6.94</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>2</FormBox>
<Weight>26.6</Weight>
<TrackCode>HOR</TrackCode>
<FormDistance>485</FormDistance>
<FormDate>24Oct17</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>8.00L</Margin>
<FirstSecond>"Tahleia Brae"</FirstSecond>
<DogTime>27.42</DogTime>
<WinTime>27.42</WinTime>
<BON>27.42</BON>
<StartPrice>$3.60</StartPrice>
<PIR>M/111</PIR>
<Split>6.64</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>3</FormBox>
<Weight>26.4</Weight>
<TrackCode>HOR</TrackCode>
<FormDistance>485</FormDistance>
<FormDate>01Nov17</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin>5.50L</Margin>
<FirstSecond>"Crymelon Idol"</FirstSecond>
<DogTime>28.04</DogTime>
<WinTime>27.68</WinTime>
<BON>27.34</BON>
<StartPrice>$7.60</StartPrice>
<PIR>M/433</PIR>
<Split>6.76</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>1</FormBox>
<Weight>26.1</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>08Nov17</FormDate>
<FormGrade>Mixed 6/7 Heat</FormGrade>
<FormHandicap />
<Margin>2.75L</Margin>
<FirstSecond>"Werner Bale"</FirstSecond>
<DogTime>30.58</DogTime>
<WinTime>30.39</WinTime>
<BON>30.02</BON>
<StartPrice>$2.40</StartPrice>
<PIR>Q/5344</PIR>
<Split>5.22</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>1</FormBox>
<Weight>26.2</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>595</FormDistance>
<FormDate>12Nov17</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>2.25L</Margin>
<FirstSecond>"Azkaban"</FirstSecond>
<DogTime>34.77</DogTime>
<WinTime>34.62</WinTime>
<BON>34.61</BON>
<StartPrice>$4.70</StartPrice>
<PIR>M/3343</PIR>
<Split>9.52</Split>
</Form>
</Dog>
<Dog id="2088850018">
<RaceBox>5</RaceBox>
<DogName>MUZZLE WELSH</DogName>
<BestTime>FSTD</BestTime>
<DogHandicap />
<StartsTOT>Starts 9-1-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="101886">Gary Mannion</Trainer>
<Suburb>Balliang</Suburb>
<Owner>Gover Borthwick Synd B Borthwick,M Gover</Owner>
<Sire id="-282383">Disintergrate</Sire>
<Dam id="-743097">Far West</Dam>
<Colour>RF</Colour>
<Sex>B</Sex>
<Whelped>18 Dec 15</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>500</DogPRIZE>
<Form>
<Place>7th</Place>
<FormBox>2</FormBox>
<Weight>24.7</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>24Oct17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>7.00L</Margin>
<FirstSecond>"Zipping Yoda"</FirstSecond>
<DogTime>26.79</DogTime>
<WinTime>26.30</WinTime>
<BON>26.27</BON>
<StartPrice>$14.60</StartPrice>
<PIR>M/888</PIR>
<Split>7.17</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>2</FormBox>
<Weight>24.8</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>28Oct17</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>4.50L</Margin>
<FirstSecond>"It's A Lie"</FirstSecond>
<DogTime>26.17</DogTime>
<WinTime>25.86</WinTime>
<BON>24.77</BON>
<StartPrice>$8.40</StartPrice>
<PIR>M/466</PIR>
<Split>5.43</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>7</FormBox>
<Weight>24.9</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>06Nov17</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>8.50L</Margin>
<FirstSecond>"Why Not Dean"</FirstSecond>
<DogTime>25.78</DogTime>
<WinTime>25.78</WinTime>
<BON>25.67</BON>
<StartPrice>$6.30</StartPrice>
<PIR>M/111</PIR>
<Split>6.70</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>8</FormBox>
<Weight>24.6</Weight>
<TrackCode>WBL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>14Nov17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>10.00L</Margin>
<FirstSecond>"Sena Bale"</FirstSecond>
<DogTime>26.34</DogTime>
<WinTime>25.65</WinTime>
<BON>25.48</BON>
<StartPrice>$3.70</StartPrice>
<PIR>M/855</PIR>
<Split>6.96</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>8</FormBox>
<Weight>24.4</Weight>
<TrackCode>WBL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>16Nov17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>14.00L</Margin>
<FirstSecond>"Barwell Boy"</FirstSecond>
<DogTime>26.33</DogTime>
<WinTime>25.36</WinTime>
<BON>25.36</BON>
<StartPrice>$29.00</StartPrice>
<PIR>M/767</PIR>
<Split>6.81</Split>
</Form>
</Dog>
<Dog id="114244061">
<RaceBox>6</RaceBox>
<DogName>CHADDY WHACKER</DogName>
<BestTime>FSTD</BestTime>
<DogHandicap />
<StartsTOT>Starts 10-1-0-1</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="289343">Michael Bewley</Trainer>
<Suburb>Pentland Hills</Suburb>
<Owner>Cucubeno Synd M Bewley,M Cunningham,A Cunningham,J Norton</Owner>
<Sire id="257880175">Paddy Whacker</Sire>
<Dam id="-625339">Daintree Sugar</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>09 Dec 15</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>595</DogPRIZE>
<Form>
<Place>5th</Place>
<FormBox>7</FormBox>
<Weight>33.5</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>22Sep17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>5.50L</Margin>
<FirstSecond>"Dyna Denver"</FirstSecond>
<DogTime>26.40</DogTime>
<WinTime>26.04</WinTime>
<BON>25.51</BON>
<StartPrice>$44.60</StartPrice>
<PIR>M/666</PIR>
<Split>6.79</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>8</FormBox>
<Weight>33.2</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>09Oct17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>4.00L</Margin>
<FirstSecond>"Mabuti Miss"</FirstSecond>
<DogTime>26.26</DogTime>
<WinTime>25.99</WinTime>
<BON>25.77</BON>
<StartPrice>$2.80</StartPrice>
<PIR>M/534</PIR>
<Split>6.75</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>7</FormBox>
<Weight>33.1</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>17Oct17</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>5.00L</Margin>
<FirstSecond>"Rattle Gate"</FirstSecond>
<DogTime>27.33</DogTime>
<WinTime>26.98</WinTime>
<BON>26.07</BON>
<StartPrice>$3.90</StartPrice>
<PIR>M/444</PIR>
<Split>6.72</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>4</FormBox>
<Weight>33.0</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>24Oct17</FormDate>
<FormGrade>Tier 3 - Grade 7</FormGrade>
<FormHandicap />
<Margin>11.00L</Margin>
<FirstSecond>"Shi The One"</FirstSecond>
<DogTime>27.05</DogTime>
<WinTime>26.31</WinTime>
<BON>26.27</BON>
<StartPrice>$10.40</StartPrice>
<PIR>M/477</PIR>
<Split>6.77</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>4</FormBox>
<Weight>33.5</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>22Nov17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Belt Up Bubbs"</FirstSecond>
<DogTime>26.53</DogTime>
<WinTime>26.08</WinTime>
<BON>25.09</BON>
<StartPrice>$67.70</StartPrice>
<PIR>M/777</PIR>
<Split>6.78</Split>
</Form>
</Dog>
<Dog id="118781088">
<RaceBox>7</RaceBox>
<DogName>MAGIC WILL</DogName>
<BestTime>31.13</BestTime>
<DogHandicap />
<StartsTOT>Starts 6-2-0-0</StartsTOT>
<StartsTTD>Trk/Dst 1-1-0-0</StartsTTD>
<Trainer id="118232">Joe Borg</Trainer>
<Suburb>Maryborough</Suburb>
<Owner>Kevin Dillon</Owner>
<Sire id="-53757">Vapour Whirl</Sire>
<Dam id="-722267">Uno Sprite</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>09 Jan 16</Whelped>
<DogGrade>6</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>2395</DogPRIZE>
<Form>
<Place>7th</Place>
<FormBox>7</FormBox>
<Weight>28.5</Weight>
<TrackCode>BEN</TrackCode>
<FormDistance>500</FormDistance>
<FormDate>25Aug17</FormDate>
<FormGrade>Maiden Final</FormGrade>
<FormHandicap />
<Margin>16.00L</Margin>
<FirstSecond>"Pawesome Nelly"</FirstSecond>
<DogTime>29.65</DogTime>
<WinTime>28.54</WinTime>
<BON>28.04</BON>
<StartPrice>$1.30</StartPrice>
<PIR>M/566</PIR>
<Split>7.06</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>8</FormBox>
<Weight>28.7</Weight>
<TrackCode>HOR</TrackCode>
<FormDistance>485</FormDistance>
<FormDate>05Sep17</FormDate>
<FormGrade>Mixed 6/7 Heat</FormGrade>
<FormHandicap />
<Margin>6.00L</Margin>
<FirstSecond>"Spring Baker"</FirstSecond>
<DogTime>28.41</DogTime>
<WinTime>28.01</WinTime>
<BON>27.57</BON>
<StartPrice>$3.00</StartPrice>
<PIR>S/78</PIR>
<Split>6.56</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>2</FormBox>
<Weight>28.8</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>13Sep17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>13.00L</Margin>
<FirstSecond>"Alannah's Gem"</FirstSecond>
<DogTime>31.66</DogTime>
<WinTime>30.79</WinTime>
<BON>30.23</BON>
<StartPrice>$1.30</StartPrice>
<PIR>M/3777</PIR>
<Split>5.32</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>8</FormBox>
<Weight>29.0</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>08Nov17</FormDate>
<FormGrade>Mixed 6/7 Heat</FormGrade>
<FormHandicap />
<Margin>9.50L</Margin>
<FirstSecond>"King Colt"</FirstSecond>
<DogTime>31.04</DogTime>
<WinTime>30.39</WinTime>
<BON>30.02</BON>
<StartPrice>$5.10</StartPrice>
<PIR>S/5777</PIR>
<Split>5.31</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>5</FormBox>
<Weight>28.2</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>545</FormDistance>
<FormDate>15Nov17</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin>4.50L</Margin>
<FirstSecond>"Bacardi Breezer"</FirstSecond>
<DogTime>31.13</DogTime>
<WinTime>31.13</WinTime>
<BON>31.13</BON>
<StartPrice>$3.90</StartPrice>
<PIR>S/3333</PIR>
<Split>6.99</Split>
</Form>
</Dog>
<Dog id="1490820017">
<RaceBox>8</RaceBox>
<DogName>ME BROS BAD</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 22-1-2-3</StartsTOT>
<StartsTTD>Trk/Dst 3-0-0-0</StartsTTD>
<Trainer id="117601">Max Zammit</Trainer>
<Suburb>Exford</Suburb>
<Owner>Max Zammit</Owner>
<Sire id="-710494">Barcia Bale</Sire>
<Dam id="-630161">Creative Mojo</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>10 Mar 15</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>1585</DogPRIZE>
<Form>
<Place>7th</Place>
<FormBox>8</FormBox>
<Weight>27.4</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>01Nov17</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin>11.00L</Margin>
<FirstSecond>"Hillside Lady"</FirstSecond>
<DogTime>30.94</DogTime>
<WinTime>30.20</WinTime>
<BON>30.09</BON>
<StartPrice>$19.00</StartPrice>
<PIR>M/6777</PIR>
<Split>5.32</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>8</FormBox>
<Weight>27.6</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>545</FormDistance>
<FormDate>06Nov17</FormDate>
<FormGrade>Tier 3 - Grade 7</FormGrade>
<FormHandicap />
<Margin>9.00L</Margin>
<FirstSecond>"Nareen"</FirstSecond>
<DogTime>32.07</DogTime>
<WinTime>31.45</WinTime>
<BON>31.45</BON>
<StartPrice>$10.30</StartPrice>
<PIR>M/5766</PIR>
<Split>7.01</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>2</FormBox>
<Weight>27.7</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>08Nov17</FormDate>
<FormGrade>Mixed 6/7 Heat</FormGrade>
<FormHandicap />
<Margin>7.50L</Margin>
<FirstSecond>"Too The Nail"</FirstSecond>
<DogTime>26.11</DogTime>
<WinTime>25.62</WinTime>
<BON>25.13</BON>
<StartPrice>$70.00</StartPrice>
<PIR>M/785</PIR>
<Split>6.82</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>8</FormBox>
<Weight>28.4</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>545</FormDistance>
<FormDate>15Nov17</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin>21.00L</Margin>
<FirstSecond>"Magic Will"</FirstSecond>
<DogTime>32.54</DogTime>
<WinTime>31.13</WinTime>
<BON>31.13</BON>
<StartPrice>$35.10</StartPrice>
<PIR>S/7777</PIR>
<Split>7.37</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>1</FormBox>
<Weight>28.1</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>545</FormDistance>
<FormDate>20Nov17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>6.00L</Margin>
<FirstSecond>"Kowari"</FirstSecond>
<DogTime>32.31</DogTime>
<WinTime>31.91</WinTime>
<BON>31.71</BON>
<StartPrice>$4.00</StartPrice>
<PIR>M/3333</PIR>
<Split>7.15</Split>
</Form>
</Dog>
<Dog id="">
<RaceBox>9</RaceBox>
<DogName />
<BestTime>* * * NO RESERVE * * *</BestTime>
<DogHandicap />
<StartsTOT />
<StartsTTD />
<Trainer id="" />
<Suburb />
<Owner />
<Sire id="" />
<Dam id="" />
<Colour />
<Sex />
<Whelped />
<DogGrade />
<DogGOBIS />
<DogPRIZE />
<Form />
<Form />
<Form />
<Form />
<Form />
</Dog>
<Dog id="">
<RaceBox>10</RaceBox>
<DogName />
<BestTime>* * * NO RESERVE * * *</BestTime>
<DogHandicap />
<StartsTOT />
<StartsTTD />
<Trainer id="" />
<Suburb />
<Owner />
<Sire id="" />
<Dam id="" />
<Colour />
<Sex />
<Whelped />
<DogGrade />
<DogGOBIS />
<DogPRIZE />
<Form />
<Form />
<Form />
<Form />
<Form />
</Dog>
</Race>
<Race id="277640683">
<RaceNum>2</RaceNum>
<RaceName>$30 CHRISTMAS BUFFET DECEMBER 2ND</RaceName>
<RaceTime>07:20PM</RaceTime>
<RaceTimeDateUTC>29 Nov 17 08:20AM</RaceTimeDateUTC>
<Distance>450m</Distance>
<RaceGrade>Grade 7</RaceGrade>
<PrizeMoney1>$1405</PrizeMoney1>
<PrizeMoney2>$400</PrizeMoney2>
<PrizeMoney3>$200</PrizeMoney3>
<PrizeMoney4 />
<PrizeMoney5 />
<PrizeMoney6 />
<PrizeMoney7 />
<PrizeMoney8 />
<GOBIS />
<Hurdle />
<Handicap />
<TAB>TRI/QUIN R/D EXACTA PICK4</TAB>
<GradeCode>7</GradeCode>
<Dog id="110526617">
<RaceBox>1</RaceBox>
<DogName>BAD APPLE</DogName>
<BestTime>25.66</BestTime>
<DogHandicap />
<StartsTOT>Starts 5-1-2-0</StartsTOT>
<StartsTTD>Trk/Dst 2-1-1-0</StartsTTD>
<Trainer id="105534">Matthew Nash</Trainer>
<Suburb>Little River</Suburb>
<Owner>Matthew Nash</Owner>
<Sire id="-190839">Kilty Lad</Sire>
<Dam id="212550013">Taste Da Rainbow</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>08 Jan 16</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>1845</DogPRIZE>
<Form>
<Place>2nd</Place>
<FormBox>6</FormBox>
<Weight>28.2</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>13Sep17</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>0.25L</Margin>
<FirstSecond>"Crackerjack Blax"</FirstSecond>
<DogTime>26.05</DogTime>
<WinTime>26.04</WinTime>
<BON>25.13</BON>
<StartPrice>$22.90</StartPrice>
<PIR>M/112</PIR>
<Split>6.75</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>2</FormBox>
<Weight>28.2</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>20Sep17</FormDate>
<FormGrade>Maiden Final</FormGrade>
<FormHandicap />
<Margin>0.50L</Margin>
<FirstSecond>"Sammy Allen"</FirstSecond>
<DogTime>25.66</DogTime>
<WinTime>25.66</WinTime>
<BON>25.27</BON>
<StartPrice>$21.10</StartPrice>
<PIR>M/111</PIR>
<Split>6.64</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>7</FormBox>
<Weight>28.4</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>390</FormDistance>
<FormDate>18Oct17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>5.00L</Margin>
<FirstSecond>"Destini Pegasus"</FirstSecond>
<DogTime>22.68</DogTime>
<WinTime>22.34</WinTime>
<BON>21.83</BON>
<StartPrice>$3.30</StartPrice>
<PIR>M/44</PIR>
<Split>8.50</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>4</FormBox>
<Weight>28.1</Weight>
<TrackCode>SHP</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>23Oct17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>5.00L</Margin>
<FirstSecond>"Captain Marvel"</FirstSecond>
<DogTime>26.18</DogTime>
<WinTime>25.85</WinTime>
<BON>25.54</BON>
<StartPrice>$2.70</StartPrice>
<PIR>M/563</PIR>
<Split>6.88</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>7</FormBox>
<Weight>28.5</Weight>
<TrackCode>SHP</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>21Nov17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>1.00L</Margin>
<FirstSecond>"Miss Bea"</FirstSecond>
<DogTime>25.86</DogTime>
<WinTime>25.80</WinTime>
<BON>25.63</BON>
<StartPrice>$1.80</StartPrice>
<PIR>M/111</PIR>
<Split>6.65</Split>
</Form>
</Dog>
<Dog id="2099800065">
<RaceBox>2</RaceBox>
<DogName>MY BRO REGIS</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 9-1-2-4</StartsTOT>
<StartsTTD>Trk/Dst 4-0-1-2</StartsTTD>
<Trainer id="101324">Andrea Dailly</Trainer>
<Suburb>Anakie</Suburb>
<Owner>Treloar Synd B Treloar,S Treloar</Owner>
<Sire id="-741428">My Bro Fabio</Sire>
<Dam id="-730581">Pippa Shiraz</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>12 Dec 15</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>2425</DogPRIZE>
<Form>
<Place>2nd</Place>
<FormBox>8</FormBox>
<Weight>36.3</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>27Oct17</FormDate>
<FormGrade>Mixed 6/7 Heat</FormGrade>
<FormHandicap />
<Margin>1.00L</Margin>
<FirstSecond>"Doran's Ash"</FirstSecond>
<DogTime>22.73</DogTime>
<WinTime>22.67</WinTime>
<BON>22.40</BON>
<StartPrice>$5.30</StartPrice>
<PIR>S/33</PIR>
<Split>8.50</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>6</FormBox>
<Weight>36.1</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>03Nov17</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>4.25L</Margin>
<FirstSecond>"Feikuai George"</FirstSecond>
<DogTime>25.90</DogTime>
<WinTime>25.62</WinTime>
<BON>25.36</BON>
<StartPrice>$9.20</StartPrice>
<PIR>M/522</PIR>
<Split>6.70</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>7</FormBox>
<Weight>35.5</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>08Nov17</FormDate>
<FormGrade>Mixed 6/7 Heat</FormGrade>
<FormHandicap />
<Margin>7.50L</Margin>
<FirstSecond>"Feikuai George"</FirstSecond>
<DogTime>25.62</DogTime>
<WinTime>25.13</WinTime>
<BON>25.13</BON>
<StartPrice>$7.40</StartPrice>
<PIR>M/222</PIR>
<Split>6.66</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>1</FormBox>
<Weight>35.0</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>17Nov17</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>1.00L</Margin>
<FirstSecond>"Coco Spectre"</FirstSecond>
<DogTime>25.59</DogTime>
<WinTime>25.52</WinTime>
<BON>25.28</BON>
<StartPrice>$3.40</StartPrice>
<PIR>M/111</PIR>
<Split>6.57</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>8</FormBox>
<Weight>34.3</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>22Nov17</FormDate>