<?xml version="1.0"?>
<!DOCTYPE Meet [<!ELEMENT Meet (Track,Date,Quali,Race+)>
<!ELEMENT Track (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Quali (#PCDATA)>
<!ELEMENT Race (RaceNum,RaceName,RaceTime,RaceTimeDateUTC,Distance,RaceGrade,PrizeMoney1,PrizeMoney2,PrizeMoney3,PrizeMoney4,PrizeMoney5,PrizeMoney6,PrizeMoney7,PrizeMoney8,GOBIS,Hurdle,Handicap,TAB,GradeCode,VICGREYS,Dog+)>
<!ELEMENT RaceNum (#PCDATA)>
<!ELEMENT RaceName (#PCDATA)>
<!ELEMENT RaceTime (#PCDATA)>
<!ELEMENT RaceTimeDateUTC (#PCDATA)>
<!ELEMENT Distance (#PCDATA)>
<!ELEMENT RaceGrade (#PCDATA)>
<!ELEMENT PrizeMoney1 (#PCDATA)>
<!ELEMENT PrizeMoney2 (#PCDATA)>
<!ELEMENT PrizeMoney3 (#PCDATA)>
<!ELEMENT PrizeMoney4 (#PCDATA)>
<!ELEMENT PrizeMoney5 (#PCDATA)>
<!ELEMENT PrizeMoney6 (#PCDATA)>
<!ELEMENT PrizeMoney7 (#PCDATA)>
<!ELEMENT PrizeMoney8 (#PCDATA)>
<!ELEMENT GOBIS (#PCDATA)>
<!ELEMENT Hurdle (#PCDATA)>
<!ELEMENT Handicap (#PCDATA)>
<!ELEMENT TAB (#PCDATA)>
<!ELEMENT GradeCode (#PCDATA)>
<!ELEMENT VICGREYS (#PCDATA)>
<!ELEMENT Dog (RaceBox,DogName,BestTime,DogHandicap,StartsTOT,StartsTTD,Trainer,Suburb,Owner,Sire,Dam,Colour,Sex,Whelped,DogGrade,DogGOBIS,DogPRIZE,AgedPrizeMoney,Form+)>
<!ELEMENT RaceBox (#PCDATA)>
<!ELEMENT DogName (#PCDATA)>
<!ELEMENT BestTime (#PCDATA)>
<!ELEMENT DogHandicap (#PCDATA)>
<!ELEMENT StartsTOT (#PCDATA)>
<!ELEMENT StartsTTD (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>
<!ELEMENT Suburb (#PCDATA)>
<!ELEMENT Owner (#PCDATA)>
<!ELEMENT Sire (#PCDATA)>
<!ELEMENT Dam (#PCDATA)>
<!ELEMENT Colour (#PCDATA)>
<!ELEMENT Sex (#PCDATA)>
<!ELEMENT Whelped (#PCDATA)>
<!ELEMENT DogGrade (#PCDATA)>
<!ELEMENT DogGOBIS (#PCDATA)>
<!ELEMENT DogPRIZE (#PCDATA)>
<!ELEMENT AgedPrizeMoney (#PCDATA)>
<!ELEMENT Form (Place,FormBox,Weight,TrackCode,FormDistance,FormDate,FormGrade,FormHandicap,Margin,FirstSecond,DogTime,WinTime,BON,StartPrice,PIR,Split)>
<!ELEMENT Place (#PCDATA)>
<!ELEMENT FormBox (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT TrackCode (#PCDATA)>
<!ELEMENT FormDistance (#PCDATA)>
<!ELEMENT FormDate (#PCDATA)>
<!ELEMENT FormGrade (#PCDATA)>
<!ELEMENT FormHandicap (#PCDATA)>
<!ELEMENT Margin (#PCDATA)>
<!ELEMENT FirstSecond (#PCDATA)>
<!ELEMENT DogTime (#PCDATA)>
<!ELEMENT WinTime (#PCDATA)>
<!ELEMENT BON (#PCDATA)>
<!ELEMENT StartPrice (#PCDATA)>
<!ELEMENT PIR (#PCDATA)>
<!ELEMENT Split (#PCDATA)>
]>
<Meet id="425062091">
<Track>The Meadows</Track>
<Date>25 Jan 20</Date>
<Quali />
<Race id="519253441">
<RaceNum>1</RaceNum>
<RaceName>GRV SUPPORTING THE BUSHFIRE APPEAL</RaceName>
<RaceTime>06:38PM</RaceTime>
<RaceTimeDateUTC>25 Jan 20 07:38AM</RaceTimeDateUTC>
<Distance>525m</Distance>
<RaceGrade>Grade 7</RaceGrade>
<PrizeMoney1>$5280</PrizeMoney1>
<PrizeMoney2>$1510</PrizeMoney2>
<PrizeMoney3>$760</PrizeMoney3>
<PrizeMoney4 />
<PrizeMoney5 />
<PrizeMoney6 />
<PrizeMoney7 />
<PrizeMoney8 />
<GOBIS />
<Hurdle />
<Handicap />
<TAB>TRI/QUIN R/D EXACTA PICK4</TAB>
<GradeCode>7</GradeCode>
<VICGREYS />
<Dog id="336122414">
<RaceBox>1</RaceBox>
<DogName>HALWES</DogName>
<BestTime>30.04</BestTime>
<DogHandicap />
<StartsTOT>Starts 9-1-2-1</StartsTOT>
<StartsTTD>Trk/Dst 7-1-2-1</StartsTTD>
<Trainer id="306069">Darren Kee</Trainer>
<Suburb>Moolap</Suburb>
<Owner>Darren Kee</Owner>
<Sire id="-218465">Go Wild Teddy</Sire>
<Dam id="-632024">Leprechaun Macey</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>05 Apr 18</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>3435</DogPRIZE>
<AgedPrizeMoney>1861</AgedPrizeMoney>
<Form>
<Place>5th</Place>
<FormBox>7</FormBox>
<Weight>30.0</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>11Dec19</FormDate>
<FormGrade>Mixed 6/7 Heat</FormGrade>
<FormHandicap />
<Margin>6.00L</Margin>
<FirstSecond>"Bartholomew Bale"</FirstSecond>
<DogTime>30.77</DogTime>
<WinTime>30.37</WinTime>
<BON>30.03</BON>
<StartPrice>$3.20</StartPrice>
<PIR>M/6555</PIR>
<Split>5.33</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>1</FormBox>
<Weight>29.6</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>21Dec19</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>8.50L</Margin>
<FirstSecond>"Circumstance"</FirstSecond>
<DogTime>30.90</DogTime>
<WinTime>30.31</WinTime>
<BON>29.67</BON>
<StartPrice>$2.10</StartPrice>
<PIR>M/5555</PIR>
<Split>5.36</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>7</FormBox>
<Weight>29.9</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>29Dec19</FormDate>
<FormGrade>Mixed 6/7 Heat</FormGrade>
<FormHandicap />
<Margin>3.5L</Margin>
<FirstSecond>"Weblec Wizz"</FirstSecond>
<DogTime>30.17</DogTime>
<WinTime>29.94</WinTime>
<BON>29.35</BON>
<StartPrice>$10.30</StartPrice>
<PIR>M/2344</PIR>
<Split>5.18</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>7</FormBox>
<Weight>30.1</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>01Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Boombox Charlie"</FirstSecond>
<DogTime>30.86</DogTime>
<WinTime>30.43</WinTime>
<BON>29.83</BON>
<StartPrice>$12.40</StartPrice>
<PIR>M/7445</PIR>
<Split>5.30</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>8</FormBox>
<Weight>29.7</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>22Jan20</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>2.00L</Margin>
<FirstSecond>"Galena Bale"</FirstSecond>
<DogTime>30.85</DogTime>
<WinTime>30.71</WinTime>
<BON>29.91</BON>
<StartPrice>$4.20</StartPrice>
<PIR>M/2122</PIR>
<Split>5.16</Split>
</Form>
</Dog>
<Dog id="317052370">
<RaceBox>2</RaceBox>
<DogName>DELANCY BALE</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 11-1-5-2</StartsTOT>
<StartsTTD>Trk/Dst 3-0-2-1</StartsTTD>
<Trainer id="10566">Brandyn Grenfell</Trainer>
<Suburb>Mount Wallace</Suburb>
<Owner>Brendan Wheeler</Owner>
<Sire id="-728090">Allen Deed</Sire>
<Dam id="385460024">Ivy Bale</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>11 Jan 18</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>4590</DogPRIZE>
<AgedPrizeMoney>4198</AgedPrizeMoney>
<Form>
<Place>3rd</Place>
<FormBox>5</FormBox>
<Weight>28.8</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>01Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>4.00L</Margin>
<FirstSecond>"Boombox Charlie"</FirstSecond>
<DogTime>30.70</DogTime>
<WinTime>30.43</WinTime>
<BON>29.83</BON>
<StartPrice>$53.20</StartPrice>
<PIR>M/6332</PIR>
<Split>5.28</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>5</FormBox>
<Weight>28.9</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>05Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>16.00L</Margin>
<FirstSecond>"You Tell Me"</FirstSecond>
<DogTime>30.58</DogTime>
<WinTime>29.49</WinTime>
<BON>29.49</BON>
<StartPrice>$9.40</StartPrice>
<PIR>M/5644</PIR>
<Split>5.30</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>1</FormBox>
<Weight>29.0</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>08Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>1.00L</Margin>
<FirstSecond>"Bea The Queen"</FirstSecond>
<DogTime>30.47</DogTime>
<WinTime>30.41</WinTime>
<BON>29.92</BON>
<StartPrice>$7.70</StartPrice>
<PIR>M/2311</PIR>
<Split>5.21</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>1</FormBox>
<Weight>28.6</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>18Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>0.10L</Margin>
<FirstSecond>"Gemma Blue"</FirstSecond>
<DogTime>30.44</DogTime>
<WinTime>30.43</WinTime>
<BON>29.99</BON>
<StartPrice>$6.80</StartPrice>
<PIR>M/2211</PIR>
<Split>5.19</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>3</FormBox>
<Weight>28.6</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>21Jan20</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>10.00L</Margin>
<FirstSecond>"Weblec Smoke"</FirstSecond>
<DogTime>26.70</DogTime>
<WinTime>26.02</WinTime>
<BON>26.02</BON>
<StartPrice>$8.00</StartPrice>
<PIR>M/655</PIR>
<Split>6.74</Split>
</Form>
</Dog>
<Dog id="336122416">
<RaceBox>3</RaceBox>
<DogName>CAPTAIN CHAPPY</DogName>
<BestTime>30.76</BestTime>
<DogHandicap />
<StartsTOT>Starts 3-1-1-1</StartsTOT>
<StartsTTD>Trk/Dst 3-1-1-1</StartsTTD>
<Trainer id="118735">Paul Bartolo</Trainer>
<Suburb>Little River</Suburb>
<Owner>Diane Bartolo</Owner>
<Sire id="-218465">Go Wild Teddy</Sire>
<Dam id="-632024">Leprechaun Macey</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>05 Apr 18</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>6915</DogPRIZE>
<AgedPrizeMoney>6415</AgedPrizeMoney>
<Form>
<Place>2nd</Place>
<FormBox>8</FormBox>
<Weight>29.3</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>01Jan20</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>5.00L</Margin>
<FirstSecond>"Junk Food Junkie"</FirstSecond>
<DogTime>30.44</DogTime>
<WinTime>30.10</WinTime>
<BON>29.83</BON>
<StartPrice>$7.80</StartPrice>
<PIR>S/6522</PIR>
<Split>5.37</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>7</FormBox>
<Weight>29.1</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>10Jan20</FormDate>
<FormGrade>Maiden Final</FormGrade>
<FormHandicap />
<Margin>3.00L</Margin>
<FirstSecond>"Shinjuku"</FirstSecond>
<DogTime>30.76</DogTime>
<WinTime>30.76</WinTime>
<BON>29.91</BON>
<StartPrice>$5.60</StartPrice>
<PIR>M/5533</PIR>
<Split>5.28</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>2</FormBox>
<Weight>29.3</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>18Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>1.25L</Margin>
<FirstSecond>"Gemma Blue"</FirstSecond>
<DogTime>30.52</DogTime>
<WinTime>30.43</WinTime>
<BON>29.99</BON>
<StartPrice>$2.60</StartPrice>
<PIR>M/4333</PIR>
<Split>5.24</Split>
</Form>
<Form />
<Form />
</Dog>
<Dog id="359349806">
<RaceBox>4</RaceBox>
<DogName>ROCKSTAR BRASS</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 5-1-0-1</StartsTOT>
<StartsTTD>Trk/Dst 2-0-0-0</StartsTTD>
<Trainer id="101324">Andrea Dailly</Trainer>
<Suburb>Anakie</Suburb>
<Owner>Nutt Evans Synd C Nutt,S Evans</Owner>
<Sire id="1744350003">Mepunga Blazer</Sire>
<Dam id="98640307">Bekim Rose</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>11 May 18</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>1525</DogPRIZE>
<AgedPrizeMoney>1260</AgedPrizeMoney>
<Form>
<Place>1st</Place>
<FormBox>4</FormBox>
<Weight>29.9</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>18Dec19</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>1.5L</Margin>
<FirstSecond>"Ashby Swift"</FirstSecond>
<DogTime>25.35</DogTime>
<WinTime>25.35</WinTime>
<BON>25.17</BON>
<StartPrice>$14.20</StartPrice>
<PIR>M/222</PIR>
<Split>6.77</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>8</FormBox>
<Weight>29.8</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>26Dec19</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>4.00L</Margin>
<FirstSecond>"Rose Royce"</FirstSecond>
<DogTime>25.88</DogTime>
<WinTime>25.61</WinTime>
<BON>25.31</BON>
<StartPrice>$5.80</StartPrice>
<PIR>M/323</PIR>
<Split>6.74</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>4</FormBox>
<Weight>29.6</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>01Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>5.50L</Margin>
<FirstSecond>"Boombox Charlie"</FirstSecond>
<DogTime>30.81</DogTime>
<WinTime>30.43</WinTime>
<BON>29.83</BON>
<StartPrice>$8.40</StartPrice>
<PIR>M/2224</PIR>
<Split>5.19</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>1</FormBox>
<Weight>30.0</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>08Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>8.50L</Margin>
<FirstSecond>"Stretch Butler"</FirstSecond>
<DogTime>30.86</DogTime>
<WinTime>30.27</WinTime>
<BON>29.92</BON>
<StartPrice>$4.00</StartPrice>
<PIR>M/3555</PIR>
<Split>5.25</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>3</FormBox>
<Weight>30.1</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>22Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>4.50L</Margin>
<FirstSecond>"Superstitious"</FirstSecond>
<DogTime>25.58</DogTime>
<WinTime>25.27</WinTime>
<BON>25.14</BON>
<StartPrice>$3.70</StartPrice>
<PIR>M/223</PIR>
<Split>6.77</Split>
</Form>
</Dog>
<Dog id="328634967">
<RaceBox>5</RaceBox>
<DogName>HURRY HARRY</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 2-1-0-1</StartsTOT>
<StartsTTD>Trk/Dst 1-0-0-1</StartsTTD>
<Trainer id="291004">Bryce Templeton</Trainer>
<Suburb>Trafalgar</Suburb>
<Owner>Bryce Templeton</Owner>
<Sire id="-309259">El Grand Senor</Sire>
<Dam id="959330043">Mix Off Harmony</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>13 Mar 18</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>2335</DogPRIZE>
<AgedPrizeMoney>2085</AgedPrizeMoney>
<Form>
<Place>1st</Place>
<FormBox>2</FormBox>
<Weight>31.6</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>03Jan20</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>3.75L</Margin>
<FirstSecond>"Outlaw Legend"</FirstSecond>
<DogTime>22.60</DogTime>
<WinTime>22.60</WinTime>
<BON>22.53</BON>
<StartPrice>$12.80</StartPrice>
<PIR>Q/11</PIR>
<Split>8.41</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>1</FormBox>
<Weight>31.8</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>18Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>7.50L</Margin>
<FirstSecond>"Rockstar Quinn"</FirstSecond>
<DogTime>30.74</DogTime>
<WinTime>30.24</WinTime>
<BON>29.99</BON>
<StartPrice>$4.70</StartPrice>
<PIR>M/2243</PIR>
<Split>5.12</Split>
</Form>
<Form />
<Form />
<Form />
</Dog>
<Dog id="317053378">
<RaceBox>6</RaceBox>
<DogName>NATSU BALE</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 18-1-4-4</StartsTOT>
<StartsTTD>Trk/Dst 3-0-0-1</StartsTTD>
<Trainer id="7683">Correy Grenfell</Trainer>
<Suburb>Mount Wallace</Suburb>
<Owner>Janice Wheeler</Owner>
<Sire id="641490370">Dyna Double One</Sire>
<Dam id="1206250156">Daithy Allen</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>01 Jan 18</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>3315</DogPRIZE>
<AgedPrizeMoney>2840</AgedPrizeMoney>
<Form>
<Place>4th</Place>
<FormBox>8</FormBox>
<Weight>26.8</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>07Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>2.50L</Margin>
<FirstSecond>"Our Manny"</FirstSecond>
<DogTime>26.70</DogTime>
<WinTime>26.53</WinTime>
<BON>26.05</BON>
<StartPrice>$5.60</StartPrice>
<PIR>M/734</PIR>
<Split>6.86</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>8</FormBox>
<Weight>26.5</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>10Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>5.00L</Margin>
<FirstSecond>"Our Manny"</FirstSecond>
<DogTime>31.03</DogTime>
<WinTime>30.68</WinTime>
<BON>29.91</BON>
<StartPrice>$26.80</StartPrice>
<PIR>M/7333</PIR>
<Split>5.29</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>5</FormBox>
<Weight>26.7</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>390</FormDistance>
<FormDate>13Jan20</FormDate>
<FormGrade>Tier 3 - Grade 7</FormGrade>
<FormHandicap />
<Margin>12.00L</Margin>
<FirstSecond>"Big Plans"</FirstSecond>
<DogTime>23.10</DogTime>
<WinTime>22.32</WinTime>
<BON>22.18</BON>
<StartPrice>$3.70</StartPrice>
<PIR>M/66</PIR>
<Split>8.96</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>2</FormBox>
<Weight>26.3</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>17Jan20</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>2.50L</Margin>
<FirstSecond>"Zambora Lion"</FirstSecond>
<DogTime>26.50</DogTime>
<WinTime>26.34</WinTime>
<BON>25.89</BON>
<StartPrice>$15.10</StartPrice>
<PIR>M/644</PIR>
<Split>6.78</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>6</FormBox>
<Weight>26.9</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>21Jan20</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>5.50L</Margin>
<FirstSecond>"Weblec Smoke"</FirstSecond>
<DogTime>26.39</DogTime>
<WinTime>26.02</WinTime>
<BON>26.02</BON>
<StartPrice>$25.70</StartPrice>
<PIR>M/332</PIR>
<Split>6.69</Split>
</Form>
</Dog>
<Dog id="328328352">
<RaceBox>7</RaceBox>
<DogName>DIAMA MISS</DogName>
<BestTime>30.40</BestTime>
<DogHandicap />
<StartsTOT>Starts 17-1-3-2</StartsTOT>
<StartsTTD>Trk/Dst 7-1-2-0</StartsTTD>
<Trainer id="18676">Jessica Sharp</Trainer>
<Suburb>Avalon</Suburb>
<Owner>Allan Lie</Owner>
<Sire id="-168350">Collision</Sire>
<Dam id="1092430060">Diama Bale</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>12 Feb 18</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>2715</DogPRIZE>
<AgedPrizeMoney>1762</AgedPrizeMoney>
<Form>
<Place>5th</Place>
<FormBox>4</FormBox>
<Weight>29.1</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>14Dec19</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>8.00L</Margin>
<FirstSecond>"Galena Bale"</FirstSecond>
<DogTime>30.86</DogTime>
<WinTime>30.33</WinTime>
<BON>29.93</BON>
<StartPrice>$7.80</StartPrice>
<PIR>Q/2775</PIR>
<Split>5.20</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>1</FormBox>
<Weight>28.6</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>27Dec19</FormDate>
<FormGrade>Mixed 6/7 Heat</FormGrade>
<FormHandicap />
<Margin>4.25L</Margin>
<FirstSecond>"Absolute Ruby"</FirstSecond>
<DogTime>23.14</DogTime>
<WinTime>22.85</WinTime>
<BON>22.73</BON>
<StartPrice>$6.30</StartPrice>
<PIR>M/55</PIR>
<Split>8.75</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>2</FormBox>
<Weight>28.2</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>400</FormDistance>
<FormDate>03Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>10.00L</Margin>
<FirstSecond>"Pair Of Nines"</FirstSecond>
<DogTime>23.29</DogTime>
<WinTime>22.59</WinTime>
<BON>22.59</BON>
<StartPrice>$11.40</StartPrice>
<PIR>M/66</PIR>
<Split>8.96</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>1</FormBox>
<Weight>28.4</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>10Jan20</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin>4.00L</Margin>
<FirstSecond>"Corazon De Leon"</FirstSecond>
<DogTime>26.64</DogTime>
<WinTime>26.37</WinTime>
<BON>25.77</BON>
<StartPrice>$9.10</StartPrice>
<PIR>Q/222</PIR>
<Split>6.84</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>4</FormBox>
<Weight>28.7</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>21Jan20</FormDate>
<FormGrade>Mixed 6/7</FormGrade>
<FormHandicap />
<Margin>12.00L</Margin>
<FirstSecond>"Weblec Smoke"</FirstSecond>
<DogTime>26.85</DogTime>
<WinTime>26.02</WinTime>
<BON>26.02</BON>
<StartPrice>$7.30</StartPrice>
<PIR>M/787</PIR>
<Split>6.86</Split>
</Form>
</Dog>
<Dog id="359349805">
<RaceBox>8</RaceBox>
<DogName>ROCKSTAR STANLEY</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 5-1-3-0</StartsTOT>
<StartsTTD>Trk/Dst 3-0-2-0</StartsTTD>
<Trainer id="101324">Andrea Dailly</Trainer>
<Suburb>Anakie</Suburb>
<Owner>Nutt Evans Synd C Nutt,S Evans</Owner>
<Sire id="1744350003">Mepunga Blazer</Sire>
<Dam id="98640307">Bekim Rose</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>11 May 18</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>3610</DogPRIZE>
<AgedPrizeMoney>3535</AgedPrizeMoney>
<Form>
<Place>2nd</Place>
<FormBox>8</FormBox>
<Weight>33.7</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>18Dec19</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>4.50L</Margin>
<FirstSecond>"Rockstar Quinn"</FirstSecond>
<DogTime>25.48</DogTime>
<WinTime>25.17</WinTime>
<BON>25.17</BON>
<StartPrice>$15.40</StartPrice>
<PIR>M/333</PIR>
<Split>6.66</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>7</FormBox>
<Weight>33.3</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>27Dec19</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>0.75L</Margin>
<FirstSecond>"Elvisa Bale"</FirstSecond>
<DogTime>26.37</DogTime>
<WinTime>26.37</WinTime>
<BON>26.02</BON>
<StartPrice>$1.80</StartPrice>
<PIR>M/531</PIR>
<Split>6.91</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>2</FormBox>
<Weight>33.2</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>01Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>17.00L</Margin>
<FirstSecond>"Boombox Charlie"</FirstSecond>
<DogTime>31.55</DogTime>
<WinTime>30.43</WinTime>
<BON>29.83</BON>
<StartPrice>$6.40</StartPrice>
<PIR>M/3777</PIR>
<Split>5.26</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>3</FormBox>
<Weight>33.5</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>08Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>1.5L</Margin>
<FirstSecond>"Stretch Butler"</FirstSecond>
<DogTime>30.38</DogTime>
<WinTime>30.27</WinTime>
<BON>29.92</BON>
<StartPrice>$4.50</StartPrice>
<PIR>M/4222</PIR>
<Split>5.32</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>6</FormBox>
<Weight>34.1</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>18Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>1.00L</Margin>
<FirstSecond>"Rockstar Quinn"</FirstSecond>
<DogTime>30.30</DogTime>
<WinTime>30.24</WinTime>
<BON>29.99</BON>
<StartPrice>$6.20</StartPrice>
<PIR>M/4322</PIR>
<Split>5.28</Split>
</Form>
</Dog>
<Dog id="336122418">
<RaceBox>9</RaceBox>
<DogName>TEDDY TOO Res.</DogName>
<BestTime>30.59</BestTime>
<DogHandicap />
<StartsTOT>Starts 2-1-0-0</StartsTOT>
<StartsTTD>Trk/Dst 2-1-0-0</StartsTTD>
<Trainer id="118735">Paul Bartolo</Trainer>
<Suburb>Little River</Suburb>
<Owner>Diane Bartolo</Owner>
<Sire id="-218465">Go Wild Teddy</Sire>
<Dam id="-632024">Leprechaun Macey</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>05 Apr 18</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>1325</DogPRIZE>
<AgedPrizeMoney>1325</AgedPrizeMoney>
<Form>
<Place>1st</Place>
<FormBox>4</FormBox>
<Weight>31.2</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>01Jan20</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>3.25L</Margin>
<FirstSecond>"Fleur Burger"</FirstSecond>
<DogTime>30.59</DogTime>
<WinTime>30.59</WinTime>
<BON>29.83</BON>
<StartPrice>$4.20</StartPrice>
<PIR>M/3111</PIR>
<Split>5.22</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>2</FormBox>
<Weight>30.8</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>10Jan20</FormDate>
<FormGrade>Maiden Final</FormGrade>
<FormHandicap />
<Margin>7.50L</Margin>
<FirstSecond>"Captain Chappy"</FirstSecond>
<DogTime>31.28</DogTime>
<WinTime>30.76</WinTime>
<BON>29.91</BON>
<StartPrice>$4.50</StartPrice>
<PIR>M/3355</PIR>
<Split>5.22</Split>
</Form>
<Form />
<Form />
<Form />
</Dog>
<Dog id="359349801">
<RaceBox>10</RaceBox>
<DogName>ROCKSTAR GARETH Res.</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 6-1-2-0</StartsTOT>
<StartsTTD>Trk/Dst 3-0-1-0</StartsTTD>
<Trainer id="101324">Andrea Dailly</Trainer>
<Suburb>Anakie</Suburb>
<Owner>Nutt Evans Synd C Nutt,S Evans</Owner>
<Sire id="1744350003">Mepunga Blazer</Sire>
<Dam id="98640307">Bekim Rose</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>11 May 18</Whelped>
<DogGrade>7</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>2125</DogPRIZE>
<AgedPrizeMoney>1725</AgedPrizeMoney>
<Form>
<Place>1st</Place>
<FormBox>4</FormBox>
<Weight>31.0</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>27Dec19</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>3.25L</Margin>
<FirstSecond>"Jagger's Joss"</FirstSecond>
<DogTime>26.08</DogTime>
<WinTime>26.08</WinTime>
<BON>26.02</BON>
<StartPrice>$4.60</StartPrice>
<PIR>M/221</PIR>
<Split>6.68</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>6</FormBox>
<Weight>31.2</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>01Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>3.00L</Margin>
<FirstSecond>"Boombox Charlie"</FirstSecond>
<DogTime>30.63</DogTime>
<WinTime>30.43</WinTime>
<BON>29.83</BON>
<StartPrice>$16.70</StartPrice>
<PIR>S/8553</PIR>
<Split>5.37</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>3</FormBox>
<Weight>31.8</Weight>
<TrackCode>MEP</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>08Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>4.50L</Margin>
<FirstSecond>"Bea The Queen"</FirstSecond>
<DogTime>30.71</DogTime>
<WinTime>30.41</WinTime>
<BON>29.92</BON>
<StartPrice>$2.10</StartPrice>
<PIR>S/6556</PIR>
<Split>5.35</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>8</FormBox>
<Weight>32.3</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>18Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>9.00L</Margin>
<FirstSecond>"Rockstar Quinn"</FirstSecond>
<DogTime>30.86</DogTime>
<WinTime>30.24</WinTime>
<BON>29.99</BON>
<StartPrice>$5.80</StartPrice>
<PIR>S/5556</PIR>
<Split>5.28</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>2</FormBox>
<Weight>32.3</Weight>
<TrackCode>BAL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>22Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>2.25L</Margin>
<FirstSecond>"Superstitious"</FirstSecond>
<DogTime>25.41</DogTime>
<WinTime>25.27</WinTime>
<BON>25.14</BON>
<StartPrice>$7.10</StartPrice>
<PIR>M/332</PIR>
<Split>6.77</Split>
</Form>
</Dog>
</Race>
<Race id="519253440">
<RaceNum>2</RaceNum>
<RaceName>$15 LAMB ROAST &amp; PAV TONIGHT</RaceName>
<RaceTime>07:02PM</RaceTime>
<RaceTimeDateUTC>25 Jan 20 08:02AM</RaceTimeDateUTC>
<Distance>525m</Distance>
<RaceGrade>Grade 6</RaceGrade>
<PrizeMoney1>$5280</PrizeMoney1>
<PrizeMoney2>$1510</PrizeMoney2>
<PrizeMoney3>$760</PrizeMoney3>
<PrizeMoney4 />
<PrizeMoney5 />
<PrizeMoney6 />
<PrizeMoney7 />
<PrizeMoney8 />
<GOBIS />
<Hurdle />
<Handicap />
<TAB>TRI/QUIN R/D EXACTA PICK4</TAB>
<GradeCode>6G</GradeCode>
<VICGREYS />
<Dog id="342840815">
<RaceBox>1</RaceBox>
<DogName>RESTRICTED</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 4-2-1-0</StartsTOT>
<StartsTTD>Trk/Dst 1-0-1-0</StartsTTD>
<Trainer id="22387">Vince Tullio</Trainer>
<Suburb>Taylors Lakes</Suburb>
<Owner>Amanda Tullio</Owner>
<Sire id="497050001">Moreira</Sire>
<Dam id="-749295">Veetee Saharrah</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>17 Apr 18</Whelped>
<DogGrade>6</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>4240</DogPRIZE>
<AgedPrizeMoney>3710</AgedPrizeMoney>
<Form>
<Place>1st</Place>
<FormBox>6</FormBox>
<Weight>33.5</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>17Nov19</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>4.00L</Margin>
<FirstSecond>"Sweet Coconut"</FirstSecond>
<DogTime>29.78</DogTime>
<WinTime>29.78</WinTime>
<BON>29.33</BON>
<StartPrice>$1.90</StartPrice>
<PIR>M/2111</PIR>
<Split>5.16</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>5</FormBox>
<Weight>33.1</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>24Nov19</FormDate>
<FormGrade>Maiden Semi Final</FormGrade>
<FormHandicap />
<Margin>11.00L</Margin>
<FirstSecond>"Better Watch Out"</FirstSecond>
<DogTime>30.27</DogTime>
<WinTime>29.55</WinTime>
<BON>29.55</BON>
<StartPrice>$2.40</StartPrice>
<PIR>M/2435</PIR>
<Split>5.15</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>1</FormBox>
<Weight>34.6</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>10Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>1.25L</Margin>
<FirstSecond>"Our Manny"</FirstSecond>
<DogTime>30.76</DogTime>
<WinTime>30.68</WinTime>
<BON>29.91</BON>
<StartPrice>$1.20</StartPrice>
<PIR>M/2111</PIR>
<Split>5.21</Split>
</Form>
<Form>
<Place>1st</Place>
<FormBox>8</FormBox>
<Weight>34.0</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>19Jan20</FormDate>
<FormGrade>Grade 7</FormGrade>
<FormHandicap />
<Margin>5.50L</Margin>
<FirstSecond>"Aston Alessio"</FirstSecond>
<DogTime>29.58</DogTime>
<WinTime>29.58</WinTime>
<BON>29.28</BON>
<StartPrice>$2.10</StartPrice>
<PIR>M/1111</PIR>
<Split>5.20</Split>
</Form>
<Form />
</Dog>
<Dog id="265157258">
<RaceBox>2</RaceBox>
<DogName>DUSTIFICATION</DogName>
<BestTime>30.54</BestTime>
<DogHandicap />
<StartsTOT>Starts 29-2-3-8</StartsTOT>
<StartsTTD>Trk/Dst 10-1-2-1</StartsTTD>
<Trainer id="18676">Jessica Sharp</Trainer>
<Suburb>Avalon</Suburb>
<Owner>Noble Men Racing Synd T Dray,R Mayes</Owner>
<Sire id="366070013">Kayda Shae</Sire>
<Dam id="497050007">Four Secrets</Dam>
<Colour>BD</Colour>
<Sex>B</Sex>
<Whelped>01 Aug 17</Whelped>
<DogGrade>6</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>8685</DogPRIZE>
<AgedPrizeMoney>5871</AgedPrizeMoney>
<Form>
<Place>3rd</Place>
<FormBox>8</FormBox>
<Weight>28.2</Weight>
<TrackCode>SAP</TrackCode>
<FormDistance>515</FormDistance>
<FormDate>22Dec19</FormDate>
<FormGrade>Restricted Win</FormGrade>
<FormHandicap />
<Margin>1.00L</Margin>
<FirstSecond>"Invictus Roy"</FirstSecond>
<DogTime>29.87</DogTime>
<WinTime>29.81</WinTime>
<BON>29.28</BON>
<StartPrice>$4.50</StartPrice>
<PIR>M/4433</PIR>
<Split>5.24</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>6</FormBox>
<Weight>27.8</Weight>
<TrackCode>MEA</TrackCode>
<FormDistance>525</FormDistance>