<?xml version="1.0"?>
<!DOCTYPE Meet [<!ELEMENT Meet (Track,Date,Quali,Race+)>
<!ELEMENT Track (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Quali (#PCDATA)>
<!ELEMENT Race (RaceNum,RaceName,RaceTime,RaceTimeDateUTC,Distance,RaceGrade,PrizeMoney1,PrizeMoney2,PrizeMoney3,PrizeMoney4,PrizeMoney5,PrizeMoney6,PrizeMoney7,PrizeMoney8,GOBIS,Hurdle,Handicap,TAB,GradeCode,Dog+)>
<!ELEMENT RaceNum (#PCDATA)>
<!ELEMENT RaceName (#PCDATA)>
<!ELEMENT RaceTime (#PCDATA)>
<!ELEMENT RaceTimeDateUTC (#PCDATA)>
<!ELEMENT Distance (#PCDATA)>
<!ELEMENT RaceGrade (#PCDATA)>
<!ELEMENT PrizeMoney1 (#PCDATA)>
<!ELEMENT PrizeMoney2 (#PCDATA)>
<!ELEMENT PrizeMoney3 (#PCDATA)>
<!ELEMENT PrizeMoney4 (#PCDATA)>
<!ELEMENT PrizeMoney5 (#PCDATA)>
<!ELEMENT PrizeMoney6 (#PCDATA)>
<!ELEMENT PrizeMoney7 (#PCDATA)>
<!ELEMENT PrizeMoney8 (#PCDATA)>
<!ELEMENT GOBIS (#PCDATA)>
<!ELEMENT Hurdle (#PCDATA)>
<!ELEMENT Handicap (#PCDATA)>
<!ELEMENT TAB (#PCDATA)>
<!ELEMENT GradeCode (#PCDATA)>
<!ELEMENT Dog (RaceBox,DogName,BestTime,DogHandicap,StartsTOT,StartsTTD,Trainer,Suburb,Owner,Sire,Dam,Colour,Sex,Whelped,DogGrade,DogGOBIS,DogPRIZE,Form+)>
<!ELEMENT RaceBox (#PCDATA)>
<!ELEMENT DogName (#PCDATA)>
<!ELEMENT BestTime (#PCDATA)>
<!ELEMENT DogHandicap (#PCDATA)>
<!ELEMENT StartsTOT (#PCDATA)>
<!ELEMENT StartsTTD (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>
<!ELEMENT Suburb (#PCDATA)>
<!ELEMENT Owner (#PCDATA)>
<!ELEMENT Sire (#PCDATA)>
<!ELEMENT Dam (#PCDATA)>
<!ELEMENT Colour (#PCDATA)>
<!ELEMENT Sex (#PCDATA)>
<!ELEMENT Whelped (#PCDATA)>
<!ELEMENT DogGrade (#PCDATA)>
<!ELEMENT DogGOBIS (#PCDATA)>
<!ELEMENT DogPRIZE (#PCDATA)>
<!ELEMENT Form (Place,FormBox,Weight,TrackCode,FormDistance,FormDate,FormGrade,FormHandicap,Margin,FirstSecond,DogTime,WinTime,BON,StartPrice,PIR,Split)>
<!ELEMENT Place (#PCDATA)>
<!ELEMENT FormBox (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT TrackCode (#PCDATA)>
<!ELEMENT FormDistance (#PCDATA)>
<!ELEMENT FormDate (#PCDATA)>
<!ELEMENT FormGrade (#PCDATA)>
<!ELEMENT FormHandicap (#PCDATA)>
<!ELEMENT Margin (#PCDATA)>
<!ELEMENT FirstSecond (#PCDATA)>
<!ELEMENT DogTime (#PCDATA)>
<!ELEMENT WinTime (#PCDATA)>
<!ELEMENT BON (#PCDATA)>
<!ELEMENT StartPrice (#PCDATA)>
<!ELEMENT PIR (#PCDATA)>
<!ELEMENT Split (#PCDATA)>
]>
<Meet id="145515522">
<Track>Sale</Track>
<Date>30 Oct 16</Date>
<Quali />
<Race id="166114590">
<RaceNum>1</RaceNum>
<RaceName>MORELLI FURNITURE &amp; BEDTIME</RaceName>
<RaceTime>05:38PM</RaceTime>
<RaceTimeDateUTC>30 Oct 16 06:38AM</RaceTimeDateUTC>
<Distance>440m</Distance>
<RaceGrade>Maiden</RaceGrade>
<PrizeMoney1>$990</PrizeMoney1>
<PrizeMoney2>$285</PrizeMoney2>
<PrizeMoney3>$140</PrizeMoney3>
<PrizeMoney4 />
<PrizeMoney5 />
<PrizeMoney6 />
<PrizeMoney7 />
<PrizeMoney8 />
<GOBIS />
<Hurdle />
<Handicap />
<TAB>TRI/QUIN R/D EXACTA PICK4</TAB>
<GradeCode>M</GradeCode>
<Dog id="1306460029">
<RaceBox>1</RaceBox>
<DogName>CRUMP'S HUSSLER</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 12-0-0-4</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="18676">Jessica Sharp</Trainer>
<Suburb>Lara</Suburb>
<Owner>Rounds And Sharp Synd L Rounds,J Sharp</Owner>
<Sire id="-631172">Crump</Sire>
<Dam id="-171344">Inside Trader</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>30 Dec 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>610</DogPRIZE>
<Form>
<Place>3rd</Place>
<FormBox>1</FormBox>
<Weight>27.1</Weight>
<TrackCode>SHP</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>29Sep16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>2.75L</Margin>
<FirstSecond>"Out On Parole"</FirstSecond>
<DogTime>26.25</DogTime>
<WinTime>26.07</WinTime>
<BON>25.32</BON>
<StartPrice>$12.30</StartPrice>
<PIR>M/322</PIR>
<Split>6.81</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>7</FormBox>
<Weight>27.4</Weight>
<TrackCode>SHP</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>06Oct16</FormDate>
<FormGrade>Maiden Semi Final</FormGrade>
<FormHandicap />
<Margin>5.50L</Margin>
<FirstSecond>"Finn's Entity"</FirstSecond>
<DogTime>26.09</DogTime>
<WinTime>25.73</WinTime>
<BON>25.20</BON>
<StartPrice>$44.10</StartPrice>
<PIR>S/333</PIR>
<Split>6.97</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>2</FormBox>
<Weight>27.1</Weight>
<TrackCode>GEL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>14Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>8.50L</Margin>
<FirstSecond>"Oshkosh Jay"</FirstSecond>
<DogTime>26.64</DogTime>
<WinTime>26.07</WinTime>
<BON>25.52</BON>
<StartPrice>$5.50</StartPrice>
<PIR>M/886</PIR>
<Split>7.19</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>7</FormBox>
<Weight>26.7</Weight>
<TrackCode>WBL</TrackCode>
<FormDistance>450</FormDistance>
<FormDate>20Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Smashing Serena"</FirstSecond>
<DogTime>26.00</DogTime>
<WinTime>25.57</WinTime>
<BON>25.19</BON>
<StartPrice>$9.50</StartPrice>
<PIR>S/865</PIR>
<Split>7.08</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>6</FormBox>
<Weight>27.0</Weight>
<TrackCode>CRN</TrackCode>
<FormDistance>520</FormDistance>
<FormDate>26Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>21.00L</Margin>
<FirstSecond>"Spring Rain"</FirstSecond>
<DogTime>32.20</DogTime>
<WinTime>30.77</WinTime>
<BON>30.18</BON>
<StartPrice>$13.40</StartPrice>
<PIR>S/8887</PIR>
<Split>5.84</Split>
</Form>
</Dog>
<Dog id="1237400035">
<RaceBox>2</RaceBox>
<DogName>KIMBA KATANI</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 3-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="276391">Martin Long</Trainer>
<Suburb>Officer</Suburb>
<Owner>Ross St Racers Synd M Long,V Robottom</Owner>
<Sire id="-622231">Bekim Bale</Sire>
<Dam id="-350195">Katathani</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>28 Nov 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>5th</Place>
<FormBox>1</FormBox>
<Weight>26.8</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>29Jul16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>6.00L</Margin>
<FirstSecond>"Can't Be Caught"</FirstSecond>
<DogTime>19.12</DogTime>
<WinTime>18.72</WinTime>
<BON>18.29</BON>
<StartPrice>$7.30</StartPrice>
<PIR>M/25</PIR>
<Split>5.01</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>4</FormBox>
<Weight>27.7</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>315</FormDistance>
<FormDate>19Sep16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>14.00L</Margin>
<FirstSecond>"Select Opal"</FirstSecond>
<DogTime>19.22</DogTime>
<WinTime>18.26</WinTime>
<BON>18.10</BON>
<StartPrice>$13.40</StartPrice>
<PIR>M/55</PIR>
<Split>5.24</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>2</FormBox>
<Weight>28.2</Weight>
<TrackCode>CRN</TrackCode>
<FormDistance>520</FormDistance>
<FormDate>27Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>15.00L</Margin>
<FirstSecond>"Latifi Nick Nack"</FirstSecond>
<DogTime>31.81</DogTime>
<WinTime>30.80</WinTime>
<BON>29.97</BON>
<StartPrice>$12.00</StartPrice>
<PIR>Q/2344</PIR>
<Split>5.58</Split>
</Form>
<Form />
<Form />
</Dog>
<Dog id="1362060005">
<RaceBox>3</RaceBox>
<DogName>SHOOT THE MOON</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 2-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="115228">Ross Stephens</Trainer>
<Suburb>Drouin West</Suburb>
<Owner>Jane Stephens</Owner>
<Sire id="-323942">Lochinvar Marlow</Sire>
<Dam id="-221264">Jezzadora</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>23 Jan 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>7th</Place>
<FormBox>5</FormBox>
<Weight>24.7</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>18Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>20.00L</Margin>
<FirstSecond>"Permafrost"</FirstSecond>
<DogTime>27.38</DogTime>
<WinTime>26.02</WinTime>
<BON>25.86</BON>
<StartPrice>$20.40</StartPrice>
<PIR>M/678</PIR>
<Split>6.75</Split>
</Form>
<Form>
<Place>8th</Place>
<FormBox>7</FormBox>
<Weight>24.6</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>22Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>14.00L</Margin>
<FirstSecond>"Dr. Walter"</FirstSecond>
<DogTime>32.10</DogTime>
<WinTime>31.13</WinTime>
<BON>30.64</BON>
<StartPrice>$13.40</StartPrice>
<PIR>S/5678</PIR>
<Split>5.07</Split>
</Form>
<Form />
<Form />
<Form />
</Dog>
<Dog id="1441310015">
<RaceBox>4</RaceBox>
<DogName>WITCH TALKING</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 0-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="109078">Graeme Vening</Trainer>
<Suburb>Wonwron</Suburb>
<Owner>Graeme Vening</Owner>
<Sire id="-577371">Spring Gun</Sire>
<Dam id="-145505">Gruesome</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>26 Jan 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form />
<Form />
<Form />
<Form />
<Form />
</Dog>
<Dog id="1044040187">
<RaceBox>5</RaceBox>
<DogName>CUT AND DRIED</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 1-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 1-0-0-0</StartsTTD>
<Trainer id="115806">Brian Alford</Trainer>
<Suburb>Yarram</Suburb>
<Owner>Brian Alford</Owner>
<Sire id="-339746">Magic Sprite</Sire>
<Dam id="-193085">Lorralai</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>01 Sep 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>5th</Place>
<FormBox>3</FormBox>
<Weight>31.1</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>23Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>15.00L</Margin>
<FirstSecond>"Mister Heeney"</FirstSecond>
<DogTime>26.72</DogTime>
<WinTime>25.70</WinTime>
<BON>25.21</BON>
<StartPrice>$9.30</StartPrice>
<PIR>Q/255</PIR>
<Split>5.53</Split>
</Form>
<Form />
<Form />
<Form />
<Form />
</Dog>
<Dog id="851640000">
<RaceBox>6</RaceBox>
<DogName>ROMAN LAD</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 14-0-1-3</StartsTOT>
<StartsTTD>Trk/Dst 12-0-1-2</StartsTTD>
<Trainer id="130097">Robert Wynd</Trainer>
<Suburb>Sale</Suburb>
<Owner>Brad Wynd</Owner>
<Sire id="-339746">Magic Sprite</Sire>
<Dam id="-45367">Live On Reality</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>03 Mar 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>705</DogPRIZE>
<Form>
<Place>2nd</Place>
<FormBox>5</FormBox>
<Weight>29.4</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>11Sep16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>2.00L</Margin>
<FirstSecond>"Captain Cranky"</FirstSecond>
<DogTime>25.70</DogTime>
<WinTime>25.56</WinTime>
<BON>24.79</BON>
<StartPrice>$31.50</StartPrice>
<PIR>M/222</PIR>
<Split>5.39</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>2</FormBox>
<Weight>29.5</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>25Sep16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Cailah Rose"</FirstSecond>
<DogTime>26.19</DogTime>
<WinTime>25.74</WinTime>
<BON>24.84</BON>
<StartPrice>$4.80</StartPrice>
<PIR>M/855</PIR>
<Split>5.68</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>8</FormBox>
<Weight>29.6</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>07Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Banjo Shark"</FirstSecond>
<DogTime>25.74</DogTime>
<WinTime>25.28</WinTime>
<BON>25.05</BON>
<StartPrice>$21.50</StartPrice>
<PIR>M/633</PIR>
<Split>5.47</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>1</FormBox>
<Weight>29.5</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>14Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>12.00L</Margin>
<FirstSecond>"Select Scott"</FirstSecond>
<DogTime>26.25</DogTime>
<WinTime>25.43</WinTime>
<BON>25.09</BON>
<StartPrice>$4.00</StartPrice>
<PIR>S/666</PIR>
<Split>5.55</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>1</FormBox>
<Weight>29.7</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>16Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>7.50L</Margin>
<FirstSecond>"Fancy Minter"</FirstSecond>
<DogTime>25.63</DogTime>
<WinTime>25.13</WinTime>
<BON>24.62</BON>
<StartPrice>$14.70</StartPrice>
<PIR>M/233</PIR>
<Split>5.47</Split>
</Form>
</Dog>
<Dog id="872550019">
<RaceBox>7</RaceBox>
<DogName>MISS FLINDERS</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 1-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 1-0-0-0</StartsTTD>
<Trainer id="24014">Adrian Smit</Trainer>
<Suburb>Longford</Suburb>
<Owner>Adrian Smit</Owner>
<Sire id="-107648">Cosmic Chief</Sire>
<Dam id="-160105">Collinda Ella</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>26 Feb 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>4th</Place>
<FormBox>8</FormBox>
<Weight>26.4</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>23Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>3.00L</Margin>
<FirstSecond>"Orataya"</FirstSecond>
<DogTime>26.33</DogTime>
<WinTime>26.13</WinTime>
<BON>25.21</BON>
<StartPrice>$12.20</StartPrice>
<PIR>M/744</PIR>
<Split>5.62</Split>
</Form>
<Form />
<Form />
<Form />
<Form />
</Dog>
<Dog id="1263700028">
<RaceBox>8</RaceBox>
<DogName>SON OF STEVE</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 2-0-1-0</StartsTOT>
<StartsTTD>Trk/Dst 1-0-1-0</StartsTTD>
<Trainer id="8974">David Selby</Trainer>
<Suburb>Bunyip North</Suburb>
<Owner>Captain Carlton Synd P Hart,D Selby,D Hart</Owner>
<Sire id="-628897">Banjo Boy</Sire>
<Dam id="-726162">Simply Cosmic</Dam>
<Colour>BE</Colour>
<Sex>D</Sex>
<Whelped>05 Dec 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>285</DogPRIZE>
<Form>
<Place>5th</Place>
<FormBox>8</FormBox>
<Weight>30.5</Weight>
<TrackCode>CRN</TrackCode>
<FormDistance>311</FormDistance>
<FormDate>05Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>13.00L</Margin>
<FirstSecond>"Riccarton"</FirstSecond>
<DogTime>18.94</DogTime>
<WinTime>18.09</WinTime>
<BON>17.73</BON>
<StartPrice>$7.80</StartPrice>
<PIR>S/67</PIR>
<Split>10.32</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>5</FormBox>
<Weight>30.8</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>23Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>0.50L</Margin>
<FirstSecond>"Orataya"</FirstSecond>
<DogTime>26.16</DogTime>
<WinTime>26.13</WinTime>
<BON>25.21</BON>
<StartPrice>$16.40</StartPrice>
<PIR>M/322</PIR>
<Split>5.54</Split>
</Form>
<Form />
<Form />
<Form />
</Dog>
<Dog id="1152760032">
<RaceBox>9</RaceBox>
<DogName>DREAM GOAL Res.</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 0-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="285378">Travis Howell</Trainer>
<Suburb>Pakenham</Suburb>
<Owner>Travis Howell</Owner>
<Sire id="-722870">Fabregas</Sire>
<Dam id="-208620">Dream Chick</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>24 Sep 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form />
<Form />
<Form />
<Form />
<Form />
</Dog>
<Dog id="688090038">
<RaceBox>10</RaceBox>
<DogName>WESTCOAST BOY Res.</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 0-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="204334">Martyn Empson</Trainer>
<Suburb>Drouin</Suburb>
<Owner>Martyn Empson</Owner>
<Sire id="-113260">Oaks Road</Sire>
<Dam id="-282385">So Blessed</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>30 Nov 13</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form />
<Form />
<Form />
<Form />
<Form />
</Dog>
</Race>
<Race id="166114591">
<RaceNum>2</RaceNum>
<RaceName>GOLD 1242</RaceName>
<RaceTime>06:02PM</RaceTime>
<RaceTimeDateUTC>30 Oct 16 07:02AM</RaceTimeDateUTC>
<Distance>440m</Distance>
<RaceGrade>Maiden</RaceGrade>
<PrizeMoney1>$990</PrizeMoney1>
<PrizeMoney2>$285</PrizeMoney2>
<PrizeMoney3>$140</PrizeMoney3>
<PrizeMoney4 />
<PrizeMoney5 />
<PrizeMoney6 />
<PrizeMoney7 />
<PrizeMoney8 />
<GOBIS />
<Hurdle />
<Handicap />
<TAB>TRI/QUIN R/D EXACTA PICK4</TAB>
<GradeCode>M</GradeCode>
<Dog id="1263700023">
<RaceBox>1</RaceBox>
<DogName>KRUZIN' CRIPPS</DogName>
<BestTime>FSH</BestTime>
<DogHandicap />
<StartsTOT>Starts 0-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 0-0-0-0</StartsTTD>
<Trainer id="8974">David Selby</Trainer>
<Suburb>Bunyip North</Suburb>
<Owner>The Weekenders Synd D Selby,P Hart,S Saniga,R Saniga,B Spieth</Owner>
<Sire id="-129690">Nobody's Fool</Sire>
<Dam id="-729187">Verbalize</Dam>
<Colour>F</Colour>
<Sex>B</Sex>
<Whelped>01 Dec 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form />
<Form />
<Form />
<Form />
<Form />
</Dog>
<Dog id="1474730034">
<RaceBox>2</RaceBox>
<DogName>CARO'S ARROW</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 2-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 2-0-0-0</StartsTTD>
<Trainer id="130058">Chris Johannsen</Trainer>
<Suburb>Devon Meadows</Suburb>
<Owner>Matthew Clark</Owner>
<Sire id="-622231">Bekim Bale</Sire>
<Dam id="-632020">Kapalos</Dam>
<Colour>BK</Colour>
<Sex>B</Sex>
<Whelped>15 Mar 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>6th</Place>
<FormBox>4</FormBox>
<Weight>29.5</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>16Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>14.00L</Margin>
<FirstSecond>"Fancy Minter"</FirstSecond>
<DogTime>26.06</DogTime>
<WinTime>25.13</WinTime>
<BON>24.62</BON>
<StartPrice>$6.50</StartPrice>
<PIR>M/866</PIR>
<Split>5.71</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>8</FormBox>
<Weight>29.4</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>23Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>13.00L</Margin>
<FirstSecond>"Cosmic Odette"</FirstSecond>
<DogTime>26.14</DogTime>
<WinTime>25.26</WinTime>
<BON>25.21</BON>
<StartPrice>$8.20</StartPrice>
<PIR>S/865</PIR>
<Split>5.72</Split>
</Form>
<Form />
<Form />
<Form />
</Dog>
<Dog id="1263700021">
<RaceBox>3</RaceBox>
<DogName>COME BACK EDDIE</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 1-0-0-0</StartsTOT>
<StartsTTD>Trk/Dst 1-0-0-0</StartsTTD>
<Trainer id="8974">David Selby</Trainer>
<Suburb>Bunyip North</Suburb>
<Owner>Captain Carlton Synd P Hart,D Selby,D Hart</Owner>
<Sire id="-129690">Nobody's Fool</Sire>
<Dam id="-729187">Verbalize</Dam>
<Colour>F</Colour>
<Sex>D</Sex>
<Whelped>01 Dec 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>0</DogPRIZE>
<Form>
<Place>5th</Place>
<FormBox>1</FormBox>
<Weight>32.7</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>23Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>18.00L</Margin>
<FirstSecond>"Good Girl Sandy"</FirstSecond>
<DogTime>26.48</DogTime>
<WinTime>25.26</WinTime>
<BON>25.21</BON>
<StartPrice>$10.90</StartPrice>
<PIR>M/234</PIR>
<Split>5.53</Split>
</Form>
<Form />
<Form />
<Form />
<Form />
</Dog>
<Dog id="768040000">
<RaceBox>4</RaceBox>
<DogName>READY SEBI GO</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 14-0-4-0</StartsTOT>
<StartsTTD>Trk/Dst 4-0-1-0</StartsTTD>
<Trainer id="6418">Donald Rhodes</Trainer>
<Suburb>Heyfield</Suburb>
<Owner>Donald Rhodes</Owner>
<Sire id="-117041">Dyna Tron</Sire>
<Dam id="-477542">Bonegilla Flash</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>23 Jan 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>705</DogPRIZE>
<Form>
<Place>6th</Place>
<FormBox>4</FormBox>
<Weight>32.2</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>28Jul16</FormDate>
<FormGrade>All Maiden</FormGrade>
<FormHandicap />
<Margin>14.00L</Margin>
<FirstSecond>"Softie Sue"</FirstSecond>
<DogTime>27.17</DogTime>
<WinTime>26.22</WinTime>
<BON>26.22</BON>
<StartPrice>$5.50</StartPrice>
<PIR>M/447</PIR>
<Split>6.76</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>1</FormBox>
<Weight>32.0</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>11Aug16</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>11.00L</Margin>
<FirstSecond>"Mitch's Delight"</FirstSecond>
<DogTime>27.08</DogTime>
<WinTime>26.34</WinTime>
<BON>26.11</BON>
<StartPrice>$3.10</StartPrice>
<PIR>M/337</PIR>
<Split>6.61</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>3</FormBox>
<Weight>32.0</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>21Aug16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>13.00L</Margin>
<FirstSecond>"Allen Eamon"</FirstSecond>
<DogTime>25.83</DogTime>
<WinTime>24.97</WinTime>
<BON>24.97</BON>
<StartPrice>$46.50</StartPrice>
<PIR>M/744</PIR>
<Split>5.73</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>3</FormBox>
<Weight>32.2</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>01Sep16</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>7.00L</Margin>
<FirstSecond>"Rosco Fields"</FirstSecond>
<DogTime>26.74</DogTime>
<WinTime>26.26</WinTime>
<BON>26.26</BON>
<StartPrice>$6.70</StartPrice>
<PIR>M/224</PIR>
<Split>6.67</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>5</FormBox>
<Weight>32.2</Weight>
<TrackCode>WGL</TrackCode>
<FormDistance>460</FormDistance>
<FormDate>15Sep16</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>3.75L</Margin>
<FirstSecond>"Black Eclipse"</FirstSecond>
<DogTime>26.62</DogTime>
<WinTime>26.36</WinTime>
<BON>26.14</BON>
<StartPrice>$19.70</StartPrice>
<PIR>M/113</PIR>
<Split>6.54</Split>
</Form>
</Dog>
<Dog id="1478420121">
<RaceBox>5</RaceBox>
<DogName>HANNAH BEAR</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 6-0-2-2</StartsTOT>
<StartsTTD>Trk/Dst 5-0-2-2</StartsTTD>
<Trainer id="68809">John Lindrea</Trainer>
<Suburb>Stratford</Suburb>
<Owner>Joshua Jones</Owner>
<Sire id="-210522">Cosmic Rumble</Sire>
<Dam id="-744386">Enlightment</Dam>
<Colour>RF</Colour>
<Sex>B</Sex>
<Whelped>11 Mar 15</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>850</DogPRIZE>
<Form>
<Place>3rd</Place>
<FormBox>1</FormBox>
<Weight>24.8</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>11Sep16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>4.25L</Margin>
<FirstSecond>"Flying Magnum"</FirstSecond>
<DogTime>25.61</DogTime>
<WinTime>25.31</WinTime>
<BON>24.79</BON>
<StartPrice>$8.90</StartPrice>
<PIR>M/222</PIR>
<Split>5.36</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>7</FormBox>
<Weight>24.3</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>25Sep16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>1.00L</Margin>
<FirstSecond>"Cailah Rose"</FirstSecond>
<DogTime>25.81</DogTime>
<WinTime>25.74</WinTime>
<BON>24.84</BON>
<StartPrice>$7.90</StartPrice>
<PIR>M/533</PIR>
<Split>5.53</Split>
</Form>
<Form>
<Place>6th</Place>
<FormBox>5</FormBox>
<Weight>24.5</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>03Oct16</FormDate>
<FormGrade>Tier 3 - Maiden</FormGrade>
<FormHandicap />
<Margin>18.00L</Margin>
<FirstSecond>"McNeo"</FirstSecond>
<DogTime>31.81</DogTime>
<WinTime>30.58</WinTime>
<BON>30.58</BON>
<StartPrice>$5.00</StartPrice>
<PIR>M/1348</PIR>
<Split>4.83</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>3</FormBox>
<Weight>24.5</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>16Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>12.00L</Margin>
<FirstSecond>"Annabelle's Boy"</FirstSecond>
<DogTime>25.41</DogTime>
<WinTime>24.62</WinTime>
<BON>24.62</BON>
<StartPrice>$25.80</StartPrice>
<PIR>M/322</PIR>
<Split>5.39</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>5</FormBox>
<Weight>25.1</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>23Oct16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>14.00L</Margin>
<FirstSecond>"Good Girl Sandy"</FirstSecond>
<DogTime>26.21</DogTime>
<WinTime>25.26</WinTime>
<BON>25.21</BON>
<StartPrice>$7.90</StartPrice>
<PIR>M/343</PIR>
<Split>5.58</Split>
</Form>
</Dog>
<Dog id="784300059">
<RaceBox>6</RaceBox>
<DogName>SIMBAREA</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 20-0-4-5</StartsTOT>
<StartsTTD>Trk/Dst 13-0-2-3</StartsTTD>
<Trainer id="111137">Gary McMillan</Trainer>
<Suburb>Nambrok</Suburb>
<Owner>Gary McMillan</Owner>
<Sire id="-720426">Milldean Panther</Sire>
<Dam id="-368305">Our Movie Star</Dam>
<Colour>BEBD</Colour>
<Sex>D</Sex>
<Whelped>30 Dec 13</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>N</DogGOBIS>
<DogPRIZE>1840</DogPRIZE>
<Form>
<Place>5th</Place>
<FormBox>6</FormBox>
<Weight>32.7</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>04Sep16</FormDate>
<FormGrade>Maiden Final</FormGrade>
<FormHandicap />
<Margin>11.00L</Margin>
<FirstSecond>"Tambo Flash"</FirstSecond>
<DogTime>26.04</DogTime>
<WinTime>25.32</WinTime>
<BON>24.82</BON>
<StartPrice>$51.20</StartPrice>
<PIR>M/334</PIR>
<Split>5.45</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>5</FormBox>
<Weight>33.0</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>12Sep16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>2.50L</Margin>
<FirstSecond>"Audacious Poppy"</FirstSecond>
<DogTime>31.08</DogTime>
<WinTime>30.90</WinTime>
<BON>30.48</BON>
<StartPrice>$8.40</StartPrice>
<PIR>M/2222</PIR>
<Split>5.03</Split>
</Form>
<Form>
<Place>3rd</Place>
<FormBox>2</FormBox>
<Weight>33.1</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>520</FormDistance>
<FormDate>18Sep16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Totally Fab"</FirstSecond>
<DogTime>30.59</DogTime>
<WinTime>30.15</WinTime>
<BON>29.83</BON>
<StartPrice>$6.70</StartPrice>
<PIR>M/333</PIR>
<Split>9.85</Split>
</Form>
<Form>
<Place>2nd</Place>
<FormBox>3</FormBox>
<Weight>33.3</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>520</FormDistance>
<FormDate>25Sep16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>0.10L</Margin>
<FirstSecond>"Gym Boots"</FirstSecond>
<DogTime>30.36</DogTime>
<WinTime>30.36</WinTime>
<BON>29.92</BON>
<StartPrice>$5.60</StartPrice>
<PIR>M/222</PIR>
<Split>9.77</Split>
</Form>
<Form>
<Place>7th</Place>
<FormBox>8</FormBox>
<Weight>33.7</Weight>
<TrackCode>TRA</TrackCode>
<FormDistance>525</FormDistance>
<FormDate>15Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>9.00L</Margin>
<FirstSecond>"Akina Dee Jay"</FirstSecond>
<DogTime>31.85</DogTime>
<WinTime>31.25</WinTime>
<BON>30.37</BON>
<StartPrice>$8.60</StartPrice>
<PIR>M/2666</PIR>
<Split>5.01</Split>
</Form>
</Dog>
<Dog id="959350019">
<RaceBox>7</RaceBox>
<DogName>RASLEIGH BANSER</DogName>
<BestTime>NBT</BestTime>
<DogHandicap />
<StartsTOT>Starts 10-0-0-4</StartsTOT>
<StartsTTD>Trk/Dst 10-0-0-4</StartsTTD>
<Trainer id="63536">Warren Stevens</Trainer>
<Suburb>Myrtlebank</Suburb>
<Owner>Warren Stevens</Owner>
<Sire id="-722870">Fabregas</Sire>
<Dam id="-632415">Penny Banser</Dam>
<Colour>BK</Colour>
<Sex>D</Sex>
<Whelped>08 Jun 14</Whelped>
<DogGrade>M</DogGrade>
<DogGOBIS>Y</DogGOBIS>
<DogPRIZE>560</DogPRIZE>
<Form>
<Place>6th</Place>
<FormBox>2</FormBox>
<Weight>32.4</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>01May16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>6.00L</Margin>
<FirstSecond>"King Mischief"</FirstSecond>
<DogTime>25.99</DogTime>
<WinTime>25.57</WinTime>
<BON>25.00</BON>
<StartPrice>$18.30</StartPrice>
<PIR>M/445</PIR>
<Split>5.49</Split>
</Form>
<Form>
<Place>5th</Place>
<FormBox>4</FormBox>
<Weight>32.9</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>06May16</FormDate>
<FormGrade>Maiden Heat</FormGrade>
<FormHandicap />
<Margin>6.50L</Margin>
<FirstSecond>"Angry Alley"</FirstSecond>
<DogTime>25.89</DogTime>
<WinTime>25.46</WinTime>
<BON>24.68</BON>
<StartPrice>$20.30</StartPrice>
<PIR>M/765</PIR>
<Split>5.59</Split>
</Form>
<Form>
<Place>F</Place>
<FormBox>5</FormBox>
<Weight>31.4</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>19Jun16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin />
<FirstSecond>"Benny The Jet"</FirstSecond>
<DogTime>0.00</DogTime>
<WinTime>25.41</WinTime>
<BON>25.03</BON>
<StartPrice>$29.70</StartPrice>
<PIR>M/6</PIR>
<Split>5.54</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>6</FormBox>
<Weight>34.8</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>07Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>1.5L</Margin>
<FirstSecond>"Freedom Fire"</FirstSecond>
<DogTime>25.64</DogTime>
<WinTime>25.54</WinTime>
<BON>25.05</BON>
<StartPrice>$7.40</StartPrice>
<PIR>S/622</PIR>
<Split>5.52</Split>
</Form>
<Form>
<Place>4th</Place>
<FormBox>4</FormBox>
<Weight>34.8</Weight>
<TrackCode>SLE</TrackCode>
<FormDistance>440</FormDistance>
<FormDate>14Oct16</FormDate>
<FormGrade>Maiden</FormGrade>
<FormHandicap />
<Margin>9.50L</Margin>
<FirstSecond>"Select Scott"</FirstSecond>
<DogTime>26.07</DogTime>
<WinTime>25.43</WinTime>
<BON>25.09</BON>
<StartPrice>$6.60</StartPrice>
<PIR>S/855</PIR>
<Split>5.61</Split>
</Form>
</Dog>
<Dog id="959350015">
<RaceBox>8</RaceBox>