<?xml version="1.0"?>
<!DOCTYPE Meet [<!ELEMENT Meet (Track,Date,Race+)>
<!ELEMENT Track (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Race (RaceNum,RaceName,RaceTime,Distance,RaceGrade,Dog+,Times+,Dividends+,Exotics+)>
<!ELEMENT RaceNum (#PCDATA)>
<!ELEMENT RaceName (#PCDATA)>
<!ELEMENT RaceTime (#PCDATA)>
<!ELEMENT Distance (#PCDATA)>
<!ELEMENT RaceGrade (#PCDATA)>
<!ELEMENT Dog (Place,DogName,Trainer,Box,Rug,Weight,StartPrice,Handicap,Margin1,Margin2,PIR,SplitMargin,RunTime)>
<!ELEMENT Place (#PCDATA)>
<!ELEMENT DogName (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>
<!ELEMENT Box (#PCDATA)>
<!ELEMENT Rug (#PCDATA)>
<!ELEMENT Race (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT StartPrice (#PCDATA)>
<!ELEMENT Handicap (#PCDATA)>
<!ELEMENT Margin1 (#PCDATA)>
<!ELEMENT Margin2 (#PCDATA)>
<!ELEMENT PIR (#PCDATA)>
<!ELEMENT SplitMargin (#PCDATA)>
<!ELEMENT RunTime (#PCDATA)>
<!ELEMENT Times (WinTime,Split1Time,Split1Rug,Split2Time,Split2Rug,Split3Time,Split3Rug)>
<!ELEMENT WinTime (#PCDATA)>
<!ELEMENT Split1Time (#PCDATA)>
<!ELEMENT Split1Rug (#PCDATA)>
<!ELEMENT Split2Time (#PCDATA)>
<!ELEMENT Split2Rug (#PCDATA)>
<!ELEMENT Split3Time (#PCDATA)>
<!ELEMENT Split3Rug (#PCDATA)>
<!ELEMENT Dividends (WinDiv,Place1Div,Place2Div,Place3Div)>
<!ELEMENT WinDiv (#PCDATA)>
<!ELEMENT Place1Div (#PCDATA)>
<!ELEMENT Place2Div (#PCDATA)>
<!ELEMENT Place3Div (#PCDATA)>
<!ELEMENT Exotics (Quin,Exacta,Trifecta,Pick4,RD,DD,Quad)>
<!ELEMENT Quin (#PCDATA)>
<!ELEMENT Exacta (#PCDATA)>
<!ELEMENT Trifecta (#PCDATA)>
<!ELEMENT Pick4 (#PCDATA)>
<!ELEMENT RD (#PCDATA)>
<!ELEMENT DD (#PCDATA)>
<!ELEMENT Quad (#PCDATA)>
]>
<Meet id="565711060">
<Track>Ballarat</Track>
<Date>17 May 21</Date>
<Race id="670117070">
<RaceNum>1</RaceNum>
<RaceName>BACKMANS PET FOODS</RaceName>
<RaceTime>03:04PM</RaceTime>
<Distance>450m</Distance>
<RaceGrade>Tier 3 - Maiden</RaceGrade>
<Dog id="482775631">
<Place>1</Place>
<DogName>WYNTON BALE</DogName>
<Trainer id="313432">D Gibbons</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>33.2</Weight>
<StartPrice>$3.40</StartPrice>
<Handicap />
<Margin1>3.39</Margin1>
<Margin2 />
<PIR>M/111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.75</SplitMargin>
<RunTime>25.78</RunTime>
<Prizemoney />
</Dog>
<Dog id="482776729">
<Place>2</Place>
<DogName>FEROCIOUS PEDRO</DogName>
<Trainer id="101886">G Mannion</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>31.0</Weight>
<StartPrice>$11.30</StartPrice>
<Handicap />
<Margin1>3.39</Margin1>
<Margin2>3.39</Margin2>
<PIR>M/222</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.75</SplitMargin>
<RunTime>26.01</RunTime>
<Prizemoney />
</Dog>
<Dog id="482775636">
<Place>3</Place>
<DogName>OSEYE BALE</DogName>
<Trainer id="311867">R Gibbons</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>27.4</Weight>
<StartPrice>$2.80F</StartPrice>
<Handicap />
<Margin1>4.31</Margin1>
<Margin2>0.93</Margin2>
<PIR>M/653</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>7.03</SplitMargin>
<RunTime>26.08</RunTime>
<Prizemoney />
</Dog>
<Dog id="366590803">
<Place>4</Place>
<DogName>RIVAL WIGGY</DogName>
<Trainer id="100636">D Leathan</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>35.1</Weight>
<StartPrice>$76.20</StartPrice>
<Handicap />
<Margin1>5.56</Margin1>
<Margin2>1.24</Margin2>
<PIR>Q/334</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.82</SplitMargin>
<RunTime>26.16</RunTime>
<Prizemoney />
</Dog>
<Dog id="476825252">
<Place>5</Place>
<DogName>ASTON ELLIOT</DogName>
<Trainer id="311867">R Gibbons</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>31.7</Weight>
<StartPrice>$3.70</StartPrice>
<Handicap />
<Margin1>6.80</Margin1>
<Margin2>1.24</Margin2>
<PIR>M/565</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>6.93</SplitMargin>
<RunTime>26.25</RunTime>
<Prizemoney />
</Dog>
<Dog id="454587361">
<Place>6</Place>
<DogName>HEART OF GOLD</DogName>
<Trainer id="130041">N Walsh</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>27.4</Weight>
<StartPrice>$15.30</StartPrice>
<Handicap />
<Margin1>14.21</Margin1>
<Margin2>7.41</Margin2>
<PIR>M/877</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>7.14</SplitMargin>
<RunTime>26.77</RunTime>
<Prizemoney />
</Dog>
<Dog id="451716135">
<Place>7</Place>
<DogName>BLUE CHERRY MISS</DogName>
<Trainer id="306610">N Hunt</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>29.7</Weight>
<StartPrice>$14.00</StartPrice>
<Handicap />
<Margin1>14.36</Margin1>
<Margin2>0.14</Margin2>
<PIR>M/446</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.91</SplitMargin>
<RunTime>26.78</RunTime>
<Prizemoney />
</Dog>
<Dog id="460430025">
<Place>8</Place>
<DogName>SEABROOK BAKER</DogName>
<Trainer id="119837">C Stanton</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>31.1</Weight>
<StartPrice>$50.60</StartPrice>
<Handicap />
<Margin1>16.53</Margin1>
<Margin2>2.17</Margin2>
<PIR>M/788</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>7.03</SplitMargin>
<RunTime>26.93</RunTime>
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>25.78</WinTime>
<Split1Time>6.75</Split1Time>
<Split1Rug>4</Split1Rug>
<Split2Time>11.56</Split2Time>
<Split2Rug>4</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>3.40</WinDiv>
<Place1Div>1.04</Place1Div>
<Place2Div>2.40</Place2Div>
<Place3Div>1.50</Place3Div>
</Dividends>
<Exotics>
<Quin>8.90</Quin>
<Exacta>26.80</Exacta>
<Trifecta>54.40</Trifecta>
<Pick4>370.00</Pick4>
<RD />
<DD />
<Quad />
</Exotics>
</Race>
<Race id="670117066">
<RaceNum>2</RaceNum>
<RaceName>STEVE TUDOR ELECTRICAL</RaceName>
<RaceTime>03:22PM</RaceTime>
<Distance>390m</Distance>
<RaceGrade>Tier 3 - Maiden</RaceGrade>
<Dog id="461109380">
<Place>1</Place>
<DogName>PHOENIX FLIGHT</DogName>
<Trainer id="177661">T Boehmke</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>28.6</Weight>
<StartPrice>$69.80</StartPrice>
<Handicap />
<Margin1>0.34</Margin1>
<Margin2 />
<PIR>M/42</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>8.85</SplitMargin>
<RunTime>22.96</RunTime>
<Prizemoney />
</Dog>
<Dog id="476825255">
<Place>2</Place>
<DogName>ASTON HARRISON</DogName>
<Trainer id="311867">R Gibbons</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>26.9</Weight>
<StartPrice>$2.10F</StartPrice>
<Handicap />
<Margin1>0.34</Margin1>
<Margin2>0.34</Margin2>
<PIR>S/21</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>8.75</SplitMargin>
<RunTime>22.98</RunTime>
<Prizemoney />
</Dog>
<Dog id="416441225">
<Place>3</Place>
<DogName>MISS MARLEE MOO</DogName>
<Trainer id="313516">D Robertson </Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>27.9</Weight>
<StartPrice>$3.60</StartPrice>
<Handicap />
<Margin1>1.61</Margin1>
<Margin2>1.27</Margin2>
<PIR>M/33</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>8.82</SplitMargin>
<RunTime>23.07</RunTime>
<Prizemoney />
</Dog>
<Dog id="456021224">
<Place>4</Place>
<DogName>EVIDENT</DogName>
<Trainer id="108647">M Lloyd</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>28.5</Weight>
<StartPrice>$3.50</StartPrice>
<Handicap />
<Margin1>5.50</Margin1>
<Margin2>3.89</Margin2>
<PIR>M/56</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>8.97</SplitMargin>
<RunTime>23.34</RunTime>
<Prizemoney />
</Dog>
<Dog id="482776251">
<Place>5</Place>
<DogName>ONLY DREAM</DogName>
<Trainer id="101167">S Mannion</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>26.1</Weight>
<StartPrice>$28.40</StartPrice>
<Handicap />
<Margin1>5.86</Margin1>
<Margin2>0.36</Margin2>
<PIR>M/67</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>8.98</SplitMargin>
<RunTime>23.37</RunTime>
<Prizemoney />
</Dog>
<Dog id="337358874">
<Place>6</Place>
<DogName>MIDNIGHT POMPEII</DogName>
<Trainer id="19286">B Chapman</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>32.6</Weight>
<StartPrice>$42.10</StartPrice>
<Handicap />
<Margin1>6.41</Margin1>
<Margin2>0.56</Margin2>
<PIR>Q/14</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>8.74</SplitMargin>
<RunTime>23.40</RunTime>
<Prizemoney />
</Dog>
<Dog id="405296980">
<Place>7</Place>
<DogName>PLAY A TUNE</DogName>
<Trainer id="100398">N Wynd</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>25.6</Weight>
<StartPrice>$37.60</StartPrice>
<Handicap />
<Margin1>6.61</Margin1>
<Margin2>0.20</Margin2>
<PIR>M/75</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>9.10</SplitMargin>
<RunTime>23.42</RunTime>
<Prizemoney />
</Dog>
<Dog id="437915092">
<Place>8</Place>
<DogName>UNIQUE FAITH</DogName>
<Trainer id="306223">S Brincat</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>25.5</Weight>
<StartPrice>$21.50</StartPrice>
<Handicap />
<Margin1>8.46</Margin1>
<Margin2>1.84</Margin2>
<PIR>Q/88</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>9.16</SplitMargin>
<RunTime>23.55</RunTime>
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>22.96</WinTime>
<Split1Time>8.74</Split1Time>
<Split1Rug>1</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>69.80</WinDiv>
<Place1Div>7.70</Place1Div>
<Place2Div>1.20</Place2Div>
<Place3Div>1.20</Place3Div>
</Dividends>
<Exotics>
<Quin>54.40</Quin>
<Exacta>450.30</Exacta>
<Trifecta>497.70</Trifecta>
<Pick4>3840.30</Pick4>
<RD>56.50</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="670117067">
<RaceNum>3</RaceNum>
<RaceName>REVOLUTION PRINT</RaceName>
<RaceTime>03:45PM</RaceTime>
<Distance>390m</Distance>
<RaceGrade>Tier 3 - Maiden</RaceGrade>
<Dog id="450196604">
<Place>1</Place>
<DogName>LONELY JENNY</DogName>
<Trainer id="106282">E Lloyd</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>25.1</Weight>
<StartPrice>$8.70</StartPrice>
<Handicap />
<Margin1>0.27</Margin1>
<Margin2 />
<PIR>M/33</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>8.64</SplitMargin>
<RunTime>22.81</RunTime>
<Prizemoney />
</Dog>
<Dog id="461109383">
<Place>2</Place>
<DogName>STELLA'S MEMORY</DogName>
<Trainer id="177661">T Boehmke</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>25.6</Weight>
<StartPrice>$9.60</StartPrice>
<Handicap />
<Margin1>0.27</Margin1>
<Margin2>0.27</Margin2>
<PIR>M/11</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>8.57</SplitMargin>
<RunTime>22.83</RunTime>
<Prizemoney />
</Dog>
<Dog id="476716035">
<Place>3</Place>
<DogName>GET AROUND ME</DogName>
<Trainer id="313431">B Garrick</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>26.6</Weight>
<StartPrice>$3.30</StartPrice>
<Handicap />
<Margin1>0.36</Margin1>
<Margin2>0.09</Margin2>
<PIR>M/22</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>8.57</SplitMargin>
<RunTime>22.84</RunTime>
<Prizemoney />
</Dog>
<Dog id="402464334">
<Place>4</Place>
<DogName>VENOMOUS YAALA</DogName>
<Trainer id="278982">J Wickham</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>30.2</Weight>
<StartPrice>$2.00F</StartPrice>
<Handicap />
<Margin1>1.39</Margin1>
<Margin2>1.03</Margin2>
<PIR>M/44</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>8.73</SplitMargin>
<RunTime>22.91</RunTime>
<Prizemoney />
</Dog>
<Dog id="460723612">
<Place>5</Place>
<DogName>GO FLO</DogName>
<Trainer id="211676">F Terry</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>22.7</Weight>
<StartPrice>$11.50</StartPrice>
<Handicap />
<Margin1>4.87</Margin1>
<Margin2>3.49</Margin2>
<PIR>M/55</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>8.75</SplitMargin>
<RunTime>23.15</RunTime>
<Prizemoney />
</Dog>
<Dog id="411693745">
<Place>6</Place>
<DogName>TAKE A DAFFODIL</DogName>
<Trainer id="109237">S Jack</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>26.7</Weight>
<StartPrice>$50.30</StartPrice>
<Handicap />
<Margin1>7.51</Margin1>
<Margin2>2.64</Margin2>
<PIR>S/86</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>8.96</SplitMargin>
<RunTime>23.34</RunTime>
<Prizemoney />
</Dog>
<Dog id="461109381">
<Place>7</Place>
<DogName>MISS MOLLY MAY</DogName>
<Trainer id="177661">T Boehmke</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>25.2</Weight>
<StartPrice>$28.80</StartPrice>
<Handicap />
<Margin1>7.60</Margin1>
<Margin2>0.09</Margin2>
<PIR>M/77</PIR>
<Checks>6</Checks>
<Comments />
<SplitMargin>8.85</SplitMargin>
<RunTime>23.34</RunTime>
<Prizemoney />
</Dog>
<Dog id="405296981">
<Place>8</Place>
<DogName>NAWALA BANJO</DogName>
<Trainer id="100398">N Wynd</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>25.0</Weight>
<StartPrice>$67.20</StartPrice>
<Handicap />
<Margin1>7.74</Margin1>
<Margin2>0.14</Margin2>
<PIR>M/68</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>8.85</SplitMargin>
<RunTime>23.35</RunTime>
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>22.81</WinTime>
<Split1Time>8.57</Split1Time>
<Split1Rug>8</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>8.70</WinDiv>
<Place1Div>1.90</Place1Div>
<Place2Div>1.40</Place2Div>
<Place3Div>1.60</Place3Div>
</Dividends>
<Exotics>
<Quin>33.30</Quin>
<Exacta>54.10</Exacta>
<Trifecta>230.20</Trifecta>
<Pick4>561.00</Pick4>
<RD>0.00</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="670117064">
<RaceNum>4</RaceNum>
<RaceName>3BA/POWER FM</RaceName>
<RaceTime>04:12PM</RaceTime>
<Distance>390m</Distance>
<RaceGrade>Grade 5 T3</RaceGrade>
<Dog id="322237190">
<Place>1</Place>
<DogName>KNUCKLE BUSTER</DogName>
<Trainer id="115898">M Meyer</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>32.2</Weight>
<StartPrice>$2.40F</StartPrice>
<Handicap />
<Margin1>3.29</Margin1>
<Margin2 />
<PIR>M/11</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>8.44</SplitMargin>
<RunTime>22.62</RunTime>
<Prizemoney />
</Dog>
<Dog id="248106226">
<Place>2</Place>
<DogName>MY MASCARA</DogName>
<Trainer id="68044">R Fisher</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>29.4</Weight>
<StartPrice>$2.80</StartPrice>
<Handicap />
<Margin1>3.29</Margin1>
<Margin2>3.29</Margin2>
<PIR>M/32</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>8.65</SplitMargin>
<RunTime>22.85</RunTime>
<Prizemoney />
</Dog>
<Dog id="203248211">
<Place>3</Place>
<DogName>DODGE COUPE</DogName>
<Trainer id="130146">A Wood</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>29.5</Weight>
<StartPrice>$3.90</StartPrice>
<Handicap />
<Margin1>4.07</Margin1>
<Margin2>0.79</Margin2>
<PIR>M/44</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>8.70</SplitMargin>
<RunTime>22.90</RunTime>
<Prizemoney />
</Dog>
<Dog id="2099820003">
<Place>4</Place>
<DogName>RINGCRAFT</DogName>
<Trainer id="132684">D Craven</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>32.9</Weight>
<StartPrice>$7.50</StartPrice>
<Handicap />
<Margin1>4.23</Margin1>
<Margin2>0.16</Margin2>
<PIR>M/23</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>8.58</SplitMargin>
<RunTime>22.91</RunTime>
<Prizemoney />
</Dog>
<Dog id="293542919">
<Place>5</Place>
<DogName>PRANJIP COMET</DogName>
<Trainer id="320677">M Formosa</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>31.9</Weight>
<StartPrice>$37.20</StartPrice>
<Handicap />
<Margin1>10.06</Margin1>
<Margin2>5.83</Margin2>
<PIR>M/55</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>8.84</SplitMargin>
<RunTime>23.32</RunTime>
<Prizemoney />
</Dog>
<Dog id="319716674">
<Place>S</Place>
<DogName>AL'S VIXEN</DogName>
<Trainer id="99808">L Farquhar</Trainer>
<Box />
<Rug>7</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>22.62</WinTime>
<Split1Time>8.44</Split1Time>
<Split1Rug>8</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.40</WinDiv>
<Place1Div>1.60</Place1Div>
<Place2Div>2.00</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>2.90</Quin>
<Exacta>2.70</Exacta>
<Trifecta>9.20</Trifecta>
<Pick4>9.00</Pick4>
<RD>18.40</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="670117068">
<RaceNum>5</RaceNum>
<RaceName>GPP 3300 LASER</RaceName>
<RaceTime>04:27PM</RaceTime>
<Distance>450m</Distance>
<RaceGrade>Grade 5 T3</RaceGrade>
<Dog id="323686080">
<Place>1</Place>
<DogName>CHICKEN SCHNITTY</DogName>
<Trainer id="309138">A Formosa</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>31.9</Weight>
<StartPrice>$5.70</StartPrice>
<Handicap />
<Margin1>0.44</Margin1>
<Margin2 />
<PIR>M/222</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.74</SplitMargin>
<RunTime>25.79</RunTime>
<Prizemoney />
</Dog>
<Dog id="373613237">
<Place>2</Place>
<DogName>TAKE A SUNFLOWER</DogName>
<Trainer id="109237">S Jack</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>28.7</Weight>
<StartPrice>$5.00</StartPrice>
<Handicap />
<Margin1>0.44</Margin1>
<Margin2>0.44</Margin2>
<PIR>M/333</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.74</SplitMargin>
<RunTime>25.82</RunTime>
<Prizemoney />
</Dog>
<Dog id="413630620">
<Place>3</Place>
<DogName>SUPERIOR DIGBY</DogName>
<Trainer id="120257">D Condon</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>32.8</Weight>
<StartPrice>$3.20F</StartPrice>
<Handicap />
<Margin1>0.56</Margin1>
<Margin2>0.11</Margin2>
<PIR>M/111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.62</SplitMargin>
<RunTime>25.83</RunTime>
<Prizemoney />
</Dog>
<Dog id="422990807">
<Place>4</Place>
<DogName>YAZID BALE</DogName>
<Trainer id="108684">L Harris</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>35.4</Weight>
<StartPrice>$4.80</StartPrice>
<Handicap />
<Margin1>0.94</Margin1>
<Margin2>0.39</Margin2>
<PIR>M/544</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.82</SplitMargin>
<RunTime>25.85</RunTime>
<Prizemoney />
</Dog>
<Dog id="264507960">
<Place>5</Place>
<DogName>PYRENEES STEELE</DogName>
<Trainer id="131120">I Robinson</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>32.5</Weight>
<StartPrice>$7.80</StartPrice>
<Handicap />
<Margin1>1.09</Margin1>
<Margin2>0.14</Margin2>
<PIR>S/666</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>7.01</SplitMargin>
<RunTime>25.86</RunTime>
<Prizemoney />
</Dog>
<Dog id="349412936">
<Place>6</Place>
<DogName>UNIQUELY MINE</DogName>
<Trainer id="101726">S Daniliuk</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>29.0</Weight>
<StartPrice>$6.40</StartPrice>
<Handicap />
<Margin1>1.34</Margin1>
<Margin2>0.26</Margin2>
<PIR>Q/455</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.75</SplitMargin>
<RunTime>25.88</RunTime>
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>25.79</WinTime>
<Split1Time>6.62</Split1Time>
<Split1Rug>1</Split1Rug>
<Split2Time>11.42</Split2Time>
<Split2Rug>1</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>5.70</WinDiv>
<Place1Div>3.30</Place1Div>
<Place2Div>2.70</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>12.30</Quin>
<Exacta>17.70</Exacta>
<Trifecta>123.30</Trifecta>
<Pick4>178.60</Pick4>
<RD>29.40</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="670117061">
<RaceNum>6</RaceNum>
<RaceName>EUREKA CONCRETE (1-2 WINS)</RaceName>
<RaceTime>04:44PM</RaceTime>
<Distance>450m</Distance>
<RaceGrade>Tier 3 - Restricted Win</RaceGrade>
<Dog id="476716064">
<Place>1</Place>
<DogName>SIMPLY SLICK</DogName>
<Trainer id="67151">M Marshall</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>32.9</Weight>
<StartPrice>$3.10F</StartPrice>
<Handicap />
<Margin1>2.96</Margin1>
<Margin2 />
<PIR>M/111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.68</SplitMargin>
<RunTime>25.73</RunTime>
<Prizemoney />
</Dog>
<Dog id="440001762">
<Place>2</Place>
<DogName>MS. LUCKY LEAVES</DogName>
<Trainer id="130121">D Jarvis</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>26.2</Weight>
<StartPrice>$25.60</StartPrice>
<Handicap />
<Margin1>2.96</Margin1>
<Margin2>2.96</Margin2>
<PIR>M/322</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.79</SplitMargin>
<RunTime>25.94</RunTime>
<Prizemoney />
</Dog>
<Dog id="445017827">
<Place>3</Place>
<DogName>JAFAR BALE</DogName>
<Trainer id="108684">L Harris</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>34.7</Weight>
<StartPrice>$12.50</StartPrice>
<Handicap />
<Margin1>5.50</Margin1>
<Margin2>2.54</Margin2>
<PIR>Q/233</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.73</SplitMargin>
<RunTime>26.12</RunTime>
<Prizemoney />
</Dog>
<Dog id="414032415">
<Place>4</Place>
<DogName>SHIM'S HEART</DogName>
<Trainer id="108647">M Lloyd</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>30.0</Weight>
<StartPrice>$15.90</StartPrice>
<Handicap />
<Margin1>6.63</Margin1>
<Margin2>1.13</Margin2>
<PIR>M/454</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>6.84</SplitMargin>
<RunTime>26.19</RunTime>
<Prizemoney />
</Dog>
<Dog id="471040205">
<Place>5</Place>
<DogName>LOCH</DogName>
<Trainer id="100210">A Mooney</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>25.7</Weight>
<StartPrice>$3.60</StartPrice>
<Handicap />
<Margin1>7.63</Margin1>
<Margin2>1.00</Margin2>
<PIR>S/545</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.84</SplitMargin>
<RunTime>26.26</RunTime>
<Prizemoney />
</Dog>
<Dog id="293230298">
<Place>6</Place>
<DogName>BRIGHT BLUE</DogName>
<Trainer id="113850">C Hughes</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>26.2</Weight>
<StartPrice>$54.90</StartPrice>
<Handicap />
<Margin1>8.01</Margin1>
<Margin2>0.39</Margin2>
<PIR>M/787</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.99</SplitMargin>
<RunTime>26.29</RunTime>
<Prizemoney />
</Dog>
<Dog id="438216697">
<Place>7</Place>
<DogName>MAXIMUM COOK</DogName>
<Trainer id="100398">N Wynd</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>25.9</Weight>
<StartPrice>$3.40</StartPrice>
<Handicap />
<Margin1>9.91</Margin1>
<Margin2>1.90</Margin2>
<PIR>M/666</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.98</SplitMargin>
<RunTime>26.42</RunTime>
<Prizemoney />
</Dog>
<Dog id="347752134">
<Place>8</Place>
<DogName>MORBIUS</DogName>
<Trainer id="130146">A Wood</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>36.1</Weight>
<StartPrice>$10.70</StartPrice>
<Handicap />
<Margin1>10.46</Margin1>
<Margin2>0.54</Margin2>
<PIR>M/878</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>7.06</SplitMargin>
<RunTime>26.46</RunTime>
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>25.73</WinTime>
<Split1Time>6.68</Split1Time>
<Split1Rug>1</Split1Rug>
<Split2Time>11.49</Split2Time>
<Split2Rug>1</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>3.10</WinDiv>
<Place1Div>1.60</Place1Div>
<Place2Div>4.90</Place2Div>
<Place3Div>2.00</Place3Div>
</Dividends>
<Exotics>
<Quin>52.00</Quin>
<Exacta>65.40</Exacta>
<Trifecta>370.10</Trifecta>
<Pick4>2775.20</Pick4>
<RD>21.00</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="670117062">
<RaceNum>7</RaceNum>
<RaceName>GREYHOUND CLUBS VICTORIA</RaceName>
<RaceTime>05:00PM</RaceTime>
<Distance>390m</Distance>
<RaceGrade>Grade 5 T3</RaceGrade>
<Dog id="445020346">
<Place>1</Place>
<DogName>IRWIN BALE</DogName>
<Trainer id="66434">T Kennedy - Harris</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>34.9</Weight>
<StartPrice>$9.20</StartPrice>
<Handicap />
<Margin1>1.50</Margin1>
<Margin2 />
<PIR>M/43</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>8.74</SplitMargin>
<RunTime>22.60</RunTime>
<Prizemoney />
</Dog>
<Dog id="402464335">
<Place>2</Place>
<DogName>EXPLOSIVE YAALA</DogName>
<Trainer id="278982">J Wickham</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>30.2</Weight>
<StartPrice>$4.00</StartPrice>
<Handicap />
<Margin1>1.50</Margin1>
<Margin2>1.50</Margin2>
<PIR>M/22</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>8.62</SplitMargin>
<RunTime>22.71</RunTime>
<Prizemoney />
</Dog>
<Dog id="442568382">
<Place>3</Place>
<DogName>ROCKSTAR HARLEY</DogName>
<Trainer id="103412">P Pace</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>28.7</Weight>
<StartPrice>$1.70F</StartPrice>
<Handicap />
<Margin1>1.89</Margin1>
<Margin2>0.39</Margin2>
<PIR>M/11</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>8.48</SplitMargin>
<RunTime>22.73</RunTime>
<Prizemoney />
</Dog>
<Dog id="196374474">
<Place>4</Place>
<DogName>LINE TRIKE</DogName>
<Trainer id="309712">N Lavelle</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>34.2</Weight>
<StartPrice>$6.60</StartPrice>
<Handicap />
<Margin1>4.44</Margin1>
<Margin2>2.56</Margin2>
<PIR>M/34</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>8.74</SplitMargin>
<RunTime>22.91</RunTime>
<Prizemoney />
</Dog>
<Dog id="439250756">
<Place>5</Place>
<DogName>DIVA DOT</DogName>
<Trainer id="117228">J Formosa</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>29.7</Weight>
<StartPrice>$9.00</StartPrice>
<Handicap />
<Margin1>4.77</Margin1>
<Margin2>0.33</Margin2>
<PIR>M/55</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>8.78</SplitMargin>
<RunTime>22.93</RunTime>
<Prizemoney />
</Dog>
<Dog id="422658158">
<Place>S</Place>
<DogName>KAIDEN</DogName>
<Trainer id="309138">A Formosa</Trainer>
<Box />
<Rug>7</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>22.60</WinTime>
<Split1Time>8.48</Split1Time>
<Split1Rug>4</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>9.20</WinDiv>
<Place1Div>2.70</Place1Div>
<Place2Div>1.90</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>8.80</Quin>
<Exacta>11.00</Exacta>
<Trifecta>22.00</Trifecta>
<Pick4>29.50</Pick4>
<RD>7.80</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="670117069">
<RaceNum>8</RaceNum>
<RaceName>A1 SIGNAGE</RaceName>
<RaceTime>05:20PM</RaceTime>
<Distance>450m</Distance>
<RaceGrade>Grade 5 T3</RaceGrade>
<Dog id="383563100">
<Place>1</Place>
<DogName>COLOURFUL PAST</DogName>
<Trainer id="115898">M Meyer</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>29.6</Weight>
<StartPrice>$2.90</StartPrice>
<Handicap />
<Margin1>3.71</Margin1>
<Margin2 />
<PIR>M/211</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.68</SplitMargin>
<RunTime>25.66</RunTime>
<Prizemoney />
</Dog>
<Dog id="368137306">
<Place>2</Place>
<DogName>SEABROOK STACK</DogName>
<Trainer id="119837">C Stanton</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>28.8</Weight>
<StartPrice>$2.80F</StartPrice>
<Handicap />
<Margin1>3.71</Margin1>
<Margin2>3.71</Margin2>
<PIR>M/332</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.75</SplitMargin>
<RunTime>25.92</RunTime>
<Prizemoney />
</Dog>
<Dog id="190934621">
<Place>3</Place>
<DogName>SETTLED</DogName>
<Trainer id="66353">S Hamilton</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>33.9</Weight>
<StartPrice>$15.50</StartPrice>
<Handicap />
<Margin1>4.01</Margin1>
<Margin2>0.30</Margin2>
<PIR>M/666</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.94</SplitMargin>
<RunTime>25.94</RunTime>
<Prizemoney />
</Dog>
<Dog id="327379020">
<Place>4</Place>
<DogName>CLYDE JAKIT</DogName>
<Trainer id="130146">A Wood</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>34.9</Weight>
<StartPrice>$5.10</StartPrice>
<Handicap />
<Margin1>4.47</Margin1>
<Margin2>0.46</Margin2>
<PIR>M/554</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.89</SplitMargin>
<RunTime>25.98</RunTime>
<Prizemoney />
</Dog>
<Dog id="276161317">
<Place>5</Place>
<DogName>CLOSE ENCOUNTER</DogName>
<Trainer id="66732">D White</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>26.2</Weight>
<StartPrice>$6.10</StartPrice>
<Handicap />
<Margin1>7.24</Margin1>
<Margin2>2.77</Margin2>
<PIR>M/445</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.78</SplitMargin>
<RunTime>26.17</RunTime>
<Prizemoney />
</Dog>
<Dog id="402464337">
<Place>6</Place>
<DogName>BLUE YAALA</DogName>
<Trainer id="278982">J Wickham</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>26.2</Weight>
<StartPrice>$16.90</StartPrice>
<Handicap />
<Margin1>7.37</Margin1>
<Margin2>0.13</Margin2>
<PIR>M/123</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.66</SplitMargin>
<RunTime>26.18</RunTime>
<Prizemoney />
</Dog>
<Dog id="326538289">
<Place>S</Place>
<DogName>COOL STORY BRO</DogName>
<Trainer id="306610">N Hunt</Trainer>
<Box />
<Rug>7</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>25.66</WinTime>
<Split1Time>6.66</Split1Time>
<Split1Rug>3</Split1Rug>
<Split2Time>11.53</Split2Time>
<Split2Rug>2</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.90</WinDiv>
<Place1Div>1.60</Place1Div>
<Place2Div>1.70</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>3.60</Quin>
<Exacta>4.30</Exacta>
<Trifecta>44.80</Trifecta>
<Pick4>127.80</Pick4>
<RD>35.50</RD>
<DD>10.60</DD>
<Quad>352.50</Quad>
</Exotics>
</Race>
<Race id="670117065">
<RaceNum>9</RaceNum>
<RaceName>BALLARAT GAP CAFE</RaceName>
<RaceTime>05:38PM</RaceTime>
<Distance>390m</Distance>
<RaceGrade>Tier 3 - Grade 7</RaceGrade>
<Dog id="331345870">
<Place>1</Place>
<DogName>INTER VINCE</DogName>
<Trainer id="210120">J Interligi</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>36.4</Weight>
<StartPrice>$2.90F</StartPrice>
<Handicap />
<Margin1>0.57</Margin1>
<Margin2 />
<PIR>M/22</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>8.55</SplitMargin>
<RunTime>22.87</RunTime>
<Prizemoney />
</Dog>
<Dog id="434800429">
<Place>2</Place>
<DogName>CHARM OFFENSIVE</DogName>
<Trainer id="309138">A Formosa</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>27.2</Weight>
<StartPrice>$8.90</StartPrice>
<Handicap />
<Margin1>0.57</Margin1>
<Margin2>0.57</Margin2>
<PIR>M/61</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>8.77</SplitMargin>
<RunTime>22.91</RunTime>
<Prizemoney />
</Dog>
<Dog id="403640675">
<Place>3</Place>
<DogName>UNION MAN</DogName>
<Trainer id="106702">J Higgins</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>30.0</Weight>
<StartPrice>$4.30</StartPrice>
<Handicap />
<Margin1>1.16</Margin1>
<Margin2>0.59</Margin2>
<PIR>S/53</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>8.74</SplitMargin>
<RunTime>22.95</RunTime>
<Prizemoney />
</Dog>
<Dog id="214382428">
<Place>4</Place>
<DogName>INGA ASSALT</DogName>
<Trainer id="122090">L Wright</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>33.7</Weight>
<StartPrice>$4.80</StartPrice>
<Handicap />
<Margin1>2.77</Margin1>
<Margin2>1.61</Margin2>
<PIR>M/34</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>8.63</SplitMargin>
<RunTime>23.07</RunTime>
<Prizemoney />
</Dog>
<Dog id="439981707">
<Place>5</Place>
<DogName>HIGH BEAM</DogName>
<Trainer id="106702">J Higgins</Trainer>