<?xml version="1.0"?>
<!DOCTYPE Meet [<!ELEMENT Meet (Track,Date,Race+)>
<!ELEMENT Track (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Race (RaceNum,RaceName,RaceTime,Distance,RaceGrade,Dog+,Times+,Dividends+,Exotics+)>
<!ELEMENT RaceNum (#PCDATA)>
<!ELEMENT RaceName (#PCDATA)>
<!ELEMENT RaceTime (#PCDATA)>
<!ELEMENT Distance (#PCDATA)>
<!ELEMENT RaceGrade (#PCDATA)>
<!ELEMENT Dog (Place,DogName,Trainer,Box,Rug,Weight,StartPrice,Handicap,Margin1,Margin2,PIR,SplitMargin,RunTime)>
<!ELEMENT Place (#PCDATA)>
<!ELEMENT DogName (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>
<!ELEMENT Box (#PCDATA)>
<!ELEMENT Rug (#PCDATA)>
<!ELEMENT Race (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT StartPrice (#PCDATA)>
<!ELEMENT Handicap (#PCDATA)>
<!ELEMENT Margin1 (#PCDATA)>
<!ELEMENT Margin2 (#PCDATA)>
<!ELEMENT PIR (#PCDATA)>
<!ELEMENT SplitMargin (#PCDATA)>
<!ELEMENT RunTime (#PCDATA)>
<!ELEMENT Times (WinTime,Split1Time,Split1Rug,Split2Time,Split2Rug,Split3Time,Split3Rug)>
<!ELEMENT WinTime (#PCDATA)>
<!ELEMENT Split1Time (#PCDATA)>
<!ELEMENT Split1Rug (#PCDATA)>
<!ELEMENT Split2Time (#PCDATA)>
<!ELEMENT Split2Rug (#PCDATA)>
<!ELEMENT Split3Time (#PCDATA)>
<!ELEMENT Split3Rug (#PCDATA)>
<!ELEMENT Dividends (WinDiv,Place1Div,Place2Div,Place3Div)>
<!ELEMENT WinDiv (#PCDATA)>
<!ELEMENT Place1Div (#PCDATA)>
<!ELEMENT Place2Div (#PCDATA)>
<!ELEMENT Place3Div (#PCDATA)>
<!ELEMENT Exotics (Quin,Exacta,Trifecta,Pick4,RD,DD,Quad)>
<!ELEMENT Quin (#PCDATA)>
<!ELEMENT Exacta (#PCDATA)>
<!ELEMENT Trifecta (#PCDATA)>
<!ELEMENT Pick4 (#PCDATA)>
<!ELEMENT RD (#PCDATA)>
<!ELEMENT DD (#PCDATA)>
<!ELEMENT Quad (#PCDATA)>
]>
<Meet id="314370540">
<Track>Horsham</Track>
<Date>21 May 19</Date>
<Race id="436862515">
<RaceNum>1</RaceNum>
<RaceName>CRYMELON KENNELS</RaceName>
<RaceTime>03:24PM</RaceTime>
<Distance>410m</Distance>
<RaceGrade>Maiden</RaceGrade>
<Dog id="223670951">
<Place>1</Place>
<DogName>LEKTRA SWANK</DogName>
<Trainer id="110456">A Gurry</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>27.0</Weight>
<StartPrice>$3.50</StartPrice>
<Handicap />
<Margin1>0.19</Margin1>
<Margin2 />
<PIR>Q/11</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>10.36</SplitMargin>
<RunTime>23.69</RunTime>
<Prizemoney />
</Dog>
<Dog id="256281043">
<Place>2</Place>
<DogName>ELEGANT MALT</DogName>
<Trainer id="69575">R Glass</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>29.9</Weight>
<StartPrice>$3.30F</StartPrice>
<Handicap />
<Margin1>0.19</Margin1>
<Margin2>0.19</Margin2>
<PIR>M/22</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>10.57</SplitMargin>
<RunTime>23.70</RunTime>
<Prizemoney />
</Dog>
<Dog id="235409379">
<Place>3</Place>
<DogName>CLOSE TO CARNAGE</DogName>
<Trainer id="108248">P Carter</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>35.2</Weight>
<StartPrice>$5.30</StartPrice>
<Handicap />
<Margin1>1.03</Margin1>
<Margin2>0.84</Margin2>
<PIR>M/33</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>10.75</SplitMargin>
<RunTime>23.76</RunTime>
<Prizemoney />
</Dog>
<Dog id="278498892">
<Place>4</Place>
<DogName>JOFFA'S GALAXY</DogName>
<Trainer id="113062">S Fisher</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>27.0</Weight>
<StartPrice>$4.40</StartPrice>
<Handicap />
<Margin1>5.11</Margin1>
<Margin2>4.09</Margin2>
<PIR>M/44</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>10.92</SplitMargin>
<RunTime>24.05</RunTime>
<Prizemoney />
</Dog>
<Dog id="238578780">
<Place>5</Place>
<DogName>BARCIA MARINA</DogName>
<Trainer id="128450">S Topp</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>34.1</Weight>
<StartPrice>$10.40</StartPrice>
<Handicap />
<Margin1>12.24</Margin1>
<Margin2>7.13</Margin2>
<PIR>M/66</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>10.96</SplitMargin>
<RunTime>24.55</RunTime>
<Prizemoney />
</Dog>
<Dog id="204415070">
<Place>6</Place>
<DogName>BEFORE</DogName>
<Trainer id="106730">M Mellington</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>26.2</Weight>
<StartPrice>$11.30</StartPrice>
<Handicap />
<Margin1>12.90</Margin1>
<Margin2>0.66</Margin2>
<PIR>M/55</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>10.92</SplitMargin>
<RunTime>24.59</RunTime>
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>23.69</WinTime>
<Split1Time>10.36</Split1Time>
<Split1Rug>2</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>3.50</WinDiv>
<Place1Div>1.80</Place1Div>
<Place2Div>2.40</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>7.50</Quin>
<Exacta>9.60</Exacta>
<Trifecta>51.20</Trifecta>
<Pick4>91.80</Pick4>
<RD />
<DD />
<Quad />
</Exotics>
</Race>
<Race id="436862506">
<RaceNum>2</RaceNum>
<RaceName>GREYHOUND ADOPTION PROGRAM</RaceName>
<RaceTime>03:44PM</RaceTime>
<Distance>410m</Distance>
<RaceGrade>Mixed 6/7</RaceGrade>
<Dog id="264508970">
<Place>1</Place>
<DogName>KRAKEN BUSTER</DogName>
<Trainer id="110650">R Clark</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>32.8</Weight>
<StartPrice>$1.80F</StartPrice>
<Handicap />
<Margin1>4.39</Margin1>
<Margin2 />
<PIR>M/62</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>10.76</SplitMargin>
<RunTime>23.67</RunTime>
<Prizemoney />
</Dog>
<Dog id="248771084">
<Place>2</Place>
<DogName>FEARSOME ALLY</DogName>
<Trainer id="80143">T Salter</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>27.8</Weight>
<StartPrice>$18.30</StartPrice>
<Handicap />
<Margin1>4.39</Margin1>
<Margin2>4.39</Margin2>
<PIR>M/11</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>10.57</SplitMargin>
<RunTime>23.98</RunTime>
<Prizemoney />
</Dog>
<Dog id="228102294">
<Place>3</Place>
<DogName>ASTON EUREKA</DogName>
<Trainer id="66356">R Brittain</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>32.4</Weight>
<StartPrice>$12.10</StartPrice>
<Handicap />
<Margin1>4.71</Margin1>
<Margin2>0.33</Margin2>
<PIR>M/53</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>10.75</SplitMargin>
<RunTime>24.00</RunTime>
<Prizemoney />
</Dog>
<Dog id="230316217">
<Place>4</Place>
<DogName>KRAKEN PAT</DogName>
<Trainer id="70210">G Glass</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>29.0</Weight>
<StartPrice>$15.50</StartPrice>
<Handicap />
<Margin1>6.11</Margin1>
<Margin2>1.40</Margin2>
<PIR>Q/24</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>10.57</SplitMargin>
<RunTime>24.10</RunTime>
<Prizemoney />
</Dog>
<Dog id="231578736">
<Place>5</Place>
<DogName>CRACKERJACK SOC</DogName>
<Trainer id="134191">C Poulter</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>34.2</Weight>
<StartPrice>$19.30</StartPrice>
<Handicap />
<Margin1>8.81</Margin1>
<Margin2>2.70</Margin2>
<PIR>M/77</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>10.77</SplitMargin>
<RunTime>24.29</RunTime>
<Prizemoney />
</Dog>
<Dog id="197538326">
<Place>6</Place>
<DogName>KINLOCH BREEZE</DogName>
<Trainer id="129725">G Gledhill</Trainer>
<Box>3</Box>
<Rug>9</Rug>
<Weight>28.0</Weight>
<StartPrice>$8.70</StartPrice>
<Handicap />
<Margin1>9.49</Margin1>
<Margin2>0.67</Margin2>
<PIR>M/48</PIR>
<Checks>9</Checks>
<Comments />
<SplitMargin>10.68</SplitMargin>
<RunTime>24.33</RunTime>
<Prizemoney />
</Dog>
<Dog id="219045251">
<Place>7</Place>
<DogName>NIMBLE NALA</DogName>
<Trainer id="129725">G Gledhill</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>24.5</Weight>
<StartPrice>$25.40</StartPrice>
<Handicap />
<Margin1>15.26</Margin1>
<Margin2>5.77</Margin2>
<PIR>M/85</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>10.82</SplitMargin>
<RunTime>24.74</RunTime>
<Prizemoney />
</Dog>
<Dog id="235409382">
<Place>8</Place>
<DogName>OPENING BID</DogName>
<Trainer id="108248">P Carter</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>35.1</Weight>
<StartPrice>$4.50</StartPrice>
<Handicap />
<Margin1>19.41</Margin1>
<Margin2>4.16</Margin2>
<PIR>M/36</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>10.61</SplitMargin>
<RunTime>25.03</RunTime>
<Prizemoney />
</Dog>
<Dog id="240419885">
<Place>S</Place>
<DogName>SMOOTH ONYX</DogName>
<Trainer id="131197">D Keanelly</Trainer>
<Box />
<Rug>3</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="145196826">
<Place>R</Place>
<DogName>BELIEVE IN YOU</DogName>
<Trainer id="104390">M Fullerton</Trainer>
<Box />
<Rug>10</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Times>
<WinTime>23.67</WinTime>
<Split1Time>10.57</Split1Time>
<Split1Rug>6</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>1.80</WinDiv>
<Place1Div>1.20</Place1Div>
<Place2Div>3.00</Place2Div>
<Place3Div>2.80</Place3Div>
</Dividends>
<Exotics>
<Quin>19.40</Quin>
<Exacta>19.70</Exacta>
<Trifecta>256.30</Trifecta>
<Pick4>1695.40</Pick4>
<RD>6.40</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="436862511">
<RaceNum>3</RaceNum>
<RaceName>3WM/MIXX FM (1-3 WINS 250+ RANK)</RaceName>
<RaceTime>04:04PM</RaceTime>
<Distance>485m</Distance>
<RaceGrade>Restricted Win</RaceGrade>
<Dog id="238580210">
<Place>1</Place>
<DogName>TOO EASY JACK</DogName>
<Trainer id="132137">T Duncan</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>33.9</Weight>
<StartPrice>$2.10F</StartPrice>
<Handicap />
<Margin1>1.73</Margin1>
<Margin2 />
<PIR>M/222</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.85</SplitMargin>
<RunTime>27.65</RunTime>
<Prizemoney />
</Dog>
<Dog id="231578737">
<Place>2</Place>
<DogName>CRACKERJACK CASH</DogName>
<Trainer id="103950">J Cooper</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>33.0</Weight>
<StartPrice>$3.70</StartPrice>
<Handicap />
<Margin1>1.73</Margin1>
<Margin2>1.73</Margin2>
<PIR>M/111</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.76</SplitMargin>
<RunTime>27.77</RunTime>
<Prizemoney />
</Dog>
<Dog id="1634010000">
<Place>3</Place>
<DogName>BUDDY'S ENTITY</DogName>
<Trainer id="132137">T Duncan</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>34.2</Weight>
<StartPrice>$9.90</StartPrice>
<Handicap />
<Margin1>2.79</Margin1>
<Margin2>1.06</Margin2>
<PIR>M/333</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.85</SplitMargin>
<RunTime>27.84</RunTime>
<Prizemoney />
</Dog>
<Dog id="137766484">
<Place>4</Place>
<DogName>STEVIE JANE</DogName>
<Trainer id="163558">P Mathieson</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>37.0</Weight>
<StartPrice>$17.90</StartPrice>
<Handicap />
<Margin1>6.21</Margin1>
<Margin2>3.43</Margin2>
<PIR>M/555</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.96</SplitMargin>
<RunTime>28.08</RunTime>
<Prizemoney />
</Dog>
<Dog id="198169053">
<Place>5</Place>
<DogName>WICKED REASON</DogName>
<Trainer id="69616">J Chilcott</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>25.0</Weight>
<StartPrice>$20.30</StartPrice>
<Handicap />
<Margin1>7.61</Margin1>
<Margin2>1.40</Margin2>
<PIR>M/444</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>6.86</SplitMargin>
<RunTime>28.18</RunTime>
<Prizemoney />
</Dog>
<Dog id="190934632">
<Place>6</Place>
<DogName>SODA GEOFF</DogName>
<Trainer id="132137">T Duncan</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>33.0</Weight>
<StartPrice>$4.10</StartPrice>
<Handicap />
<Margin1>10.19</Margin1>
<Margin2>2.57</Margin2>
<PIR>S/666</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>7.38</SplitMargin>
<RunTime>28.36</RunTime>
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>27.65</WinTime>
<Split1Time>6.76</Split1Time>
<Split1Rug>2</Split1Rug>
<Split2Time>14.34</Split2Time>
<Split2Rug>2</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.10</WinDiv>
<Place1Div>1.10</Place1Div>
<Place2Div>1.90</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>2.60</Quin>
<Exacta>4.10</Exacta>
<Trifecta>23.00</Trifecta>
<Pick4>44.20</Pick4>
<RD>3.40</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="436862507">
<RaceNum>4</RaceNum>
<RaceName>WILKIE COURIERS PTY LTD</RaceName>
<RaceTime>04:19PM</RaceTime>
<Distance>410m</Distance>
<RaceGrade>Free For All</RaceGrade>
<Dog id="1550070067">
<Place>1</Place>
<DogName>KUNG FU HUSTLE</DogName>
<Trainer id="108932">A Debattista</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>25.9</Weight>
<StartPrice>$11.20</StartPrice>
<Handicap />
<Margin1>2.29</Margin1>
<Margin2 />
<PIR>M/11</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>10.37</SplitMargin>
<RunTime>23.37</RunTime>
<Prizemoney />
</Dog>
<Dog id="130879764">
<Place>2</Place>
<DogName>JAR MAN</DogName>
<Trainer id="130002">C Smith</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>30.6</Weight>
<StartPrice>$1.20F</StartPrice>
<Handicap />
<Margin1>2.29</Margin1>
<Margin2>2.29</Margin2>
<PIR>M/43</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>10.62</SplitMargin>
<RunTime>23.53</RunTime>
<Prizemoney />
</Dog>
<Dog id="2131500002">
<Place>3</Place>
<DogName>WOK FRIED YABBY</DogName>
<Trainer id="130002">C Smith</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>33.6</Weight>
<StartPrice>$18.70</StartPrice>
<Handicap />
<Margin1>2.74</Margin1>
<Margin2>0.46</Margin2>
<PIR>M/32</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>10.60</SplitMargin>
<RunTime>23.56</RunTime>
<Prizemoney />
</Dog>
<Dog id="197548331">
<Place>4</Place>
<DogName>CRUZIN'</DogName>
<Trainer id="69575">R Glass</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>26.5</Weight>
<StartPrice>$4.70</StartPrice>
<Handicap />
<Margin1>5.99</Margin1>
<Margin2>3.24</Margin2>
<PIR>M/24</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>10.53</SplitMargin>
<RunTime>23.79</RunTime>
<Prizemoney />
</Dog>
<Dog id="184236243">
<Place>S</Place>
<DogName>TANKALICIOUS</DogName>
<Trainer id="109579">N Lund</Trainer>
<Box />
<Rug>2</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="1490840005">
<Place>S</Place>
<DogName>TYE ME OVER</DogName>
<Trainer id="132105">R Martin</Trainer>
<Box />
<Rug>4</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>23.37</WinTime>
<Split1Time>10.37</Split1Time>
<Split1Rug>8</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>11.20</WinDiv>
<Place1Div>NPP</Place1Div>
<Place2Div>NPP</Place2Div>
<Place3Div>NPP</Place3Div>
</Dividends>
<Exotics>
<Quin>4.70</Quin>
<Exacta>39.40</Exacta>
<Trifecta>126.30</Trifecta>
<Pick4>94.50</Pick4>
<RD>34.00</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="436862512">
<RaceNum>5</RaceNum>
<RaceName>WIMMERA AQUATRAIL (1-3 WINS 250+ RANK)</RaceName>
<RaceTime>04:39PM</RaceTime>
<Distance>485m</Distance>
<RaceGrade>Restricted Win</RaceGrade>
<Dog id="149705820">
<Place>1</Place>
<DogName>NIMBLE LEO</DogName>
<Trainer id="131138">D Goudge</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>33.1</Weight>
<StartPrice>$2.80</StartPrice>
<Handicap />
<Margin1>3.61</Margin1>
<Margin2 />
<PIR>M/111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.74</SplitMargin>
<RunTime>27.77</RunTime>
<Prizemoney />
</Dog>
<Dog id="194920063">
<Place>2</Place>
<DogName>STEWIE DEEDS</DogName>
<Trainer id="119251">G Anders</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>34.2</Weight>
<StartPrice>$2.50F</StartPrice>
<Handicap />
<Margin1>3.61</Margin1>
<Margin2>3.61</Margin2>
<PIR>M/334</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.80</SplitMargin>
<RunTime>28.03</RunTime>
<Prizemoney />
</Dog>
<Dog id="198169054">
<Place>3</Place>
<DogName>CHILL OUT ISLA</DogName>
<Trainer id="101335">M Chilcott</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>26.3</Weight>
<StartPrice>$11.90</StartPrice>
<Handicap />
<Margin1>4.89</Margin1>
<Margin2>1.27</Margin2>
<PIR>M/222</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.75</SplitMargin>
<RunTime>28.12</RunTime>
<Prizemoney />
</Dog>
<Dog id="116900836">
<Place>4</Place>
<DogName>JOSHUA ROCKS</DogName>
<Trainer id="114867">N Lenehan</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>37.0</Weight>
<StartPrice>$3.70</StartPrice>
<Handicap />
<Margin1>5.07</Margin1>
<Margin2>0.19</Margin2>
<PIR>S/643</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.98</SplitMargin>
<RunTime>28.13</RunTime>
<Prizemoney />
</Dog>
<Dog id="250699414">
<Place>5</Place>
<DogName>UNITED LASS</DogName>
<Trainer id="68923">J Burow</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>27.0</Weight>
<StartPrice>$16.60</StartPrice>
<Handicap />
<Margin1>8.61</Margin1>
<Margin2>3.54</Margin2>
<PIR>M/466</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.82</SplitMargin>
<RunTime>28.38</RunTime>
<Prizemoney />
</Dog>
<Dog id="126751516">
<Place>6</Place>
<DogName>DOUBLE BIRDY</DogName>
<Trainer id="108932">A Debattista</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>25.6</Weight>
<StartPrice>$39.10</StartPrice>
<Handicap />
<Margin1>10.11</Margin1>
<Margin2>1.50</Margin2>
<PIR>S/555</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.82</SplitMargin>
<RunTime>28.48</RunTime>
<Prizemoney />
</Dog>
<Dog id="238580218">
<Place>S</Place>
<DogName>ROMAN RENEGADE</DogName>
<Trainer id="0" />
<Box />
<Rug>3</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>27.77</WinTime>
<Split1Time>6.74</Split1Time>
<Split1Rug>2</Split1Rug>
<Split2Time>14.48</Split2Time>
<Split2Rug>2</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.80</WinDiv>
<Place1Div>1.80</Place1Div>
<Place2Div>1.30</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>2.80</Quin>
<Exacta>6.40</Exacta>
<Trifecta>14.10</Trifecta>
<Pick4>30.80</Pick4>
<RD>45.20</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="436862508">
<RaceNum>6</RaceNum>
<RaceName>CHS GROUP (3-6 WINS) (VICGREYS)</RaceName>
<RaceTime>04:54PM</RaceTime>
<Distance>485m</Distance>
<RaceGrade>Restricted Win</RaceGrade>
<Dog id="222462540">
<Place>1</Place>
<DogName>RILEY'S PAIGE</DogName>
<Trainer id="68583">C Capuano</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>30.7</Weight>
<StartPrice>$2.60F</StartPrice>
<Handicap />
<Margin1>1.36</Margin1>
<Margin2 />
<PIR>Q/122</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.55</SplitMargin>
<RunTime>27.38</RunTime>
<Prizemoney />
</Dog>
<Dog id="226500600">
<Place>2</Place>
<DogName>BALLISTIC YAALA</DogName>
<Trainer id="108219">K Lloyd</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>35.9</Weight>
<StartPrice>$5.30</StartPrice>
<Handicap />
<Margin1>1.36</Margin1>
<Margin2>1.36</Margin2>
<PIR>M/211</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.57</SplitMargin>
<RunTime>27.47</RunTime>
<Prizemoney />
</Dog>
<Dog id="132913297">
<Place>3</Place>
<DogName>LIBERAL NUNNIO</DogName>
<Trainer id="170703">D Klemke</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>33.4</Weight>
<StartPrice>$43.00</StartPrice>
<Handicap />
<Margin1>4.60</Margin1>
<Margin2>3.24</Margin2>
<PIR>M/865</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.77</SplitMargin>
<RunTime>27.70</RunTime>
<Prizemoney />
</Dog>
<Dog id="204133454">
<Place>4</Place>
<DogName>YOU BLUE</DogName>
<Trainer id="129725">G Gledhill</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>34.2</Weight>
<StartPrice>$28.10</StartPrice>
<Handicap />
<Margin1>6.36</Margin1>
<Margin2>1.76</Margin2>
<PIR>M/753</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.69</SplitMargin>
<RunTime>27.82</RunTime>
<Prizemoney />
</Dog>
<Dog id="167542416">
<Place>5</Place>
<DogName>HOOKED ON YOU</DogName>
<Trainer id="58727">D Weightman</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>35.1</Weight>
<StartPrice>$3.90</StartPrice>
<Handicap />
<Margin1>6.41</Margin1>
<Margin2>0.06</Margin2>
<PIR>M/534</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.66</SplitMargin>
<RunTime>27.83</RunTime>
<Prizemoney />
</Dog>
<Dog id="256279540">
<Place>6</Place>
<DogName>NEIL'S GIRL</DogName>
<Trainer id="110650">R Clark</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>27.5</Weight>
<StartPrice>$5.70</StartPrice>
<Handicap />
<Margin1>6.63</Margin1>
<Margin2>0.21</Margin2>
<PIR>M/446</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.66</SplitMargin>
<RunTime>27.84</RunTime>
<Prizemoney />
</Dog>
<Dog id="256198381">
<Place>7</Place>
<DogName>VALLETTA SKY</DogName>
<Trainer id="131625">J Nicholls</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>27.6</Weight>
<StartPrice>$11.50</StartPrice>
<Handicap />
<Margin1>8.21</Margin1>
<Margin2>1.59</Margin2>
<PIR>M/388</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.62</SplitMargin>
<RunTime>27.95</RunTime>
<Prizemoney />
</Dog>
<Dog id="251075671">
<Place>8</Place>
<DogName>RED HOT CHANCE</DogName>
<Trainer id="309138">A Formosa</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>33.8</Weight>
<StartPrice>$30.60</StartPrice>
<Handicap />
<Margin1>10.11</Margin1>
<Margin2>1.90</Margin2>
<PIR>M/677</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.68</SplitMargin>
<RunTime>28.08</RunTime>
<Prizemoney />
</Dog>
<Dog id="204133455">
<Place>R</Place>
<DogName>THROUGH</DogName>
<Trainer id="129725">G Gledhill</Trainer>
<Box />
<Rug>9</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="126531073">
<Place>R</Place>
<DogName>SAVANNAH ICON</DogName>
<Trainer id="118743">D Fisher</Trainer>
<Box />
<Rug>10</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Times>
<WinTime>27.38</WinTime>
<Split1Time>6.55</Split1Time>
<Split1Rug>4</Split1Rug>
<Split2Time>14.12</Split2Time>
<Split2Rug>8</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.60</WinDiv>
<Place1Div>1.50</Place1Div>
<Place2Div>1.50</Place2Div>
<Place3Div>4.70</Place3Div>
</Dividends>
<Exotics>
<Quin>4.70</Quin>
<Exacta>8.50</Exacta>
<Trifecta>67.80</Trifecta>
<Pick4>566.50</Pick4>
<RD>9.90</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="436862513">
<RaceNum>7</RaceNum>
<RaceName>CEC HOPPER &amp; SONS</RaceName>
<RaceTime>05:14PM</RaceTime>
<Distance>410m</Distance>
<RaceGrade>Grade 5</RaceGrade>
<Dog id="127028581">
<Place>1</Place>
<DogName>PLACID WARRIOR</DogName>
<Trainer id="67975">S Cachia</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>31.2</Weight>
<StartPrice>$5.30</StartPrice>
<Handicap />
<Margin1>5.74</Margin1>
<Margin2 />
<PIR>M/11</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>10.44</SplitMargin>
<RunTime>23.31</RunTime>
<Prizemoney />
</Dog>
<Dog id="1906490007">
<Place>2</Place>
<DogName>OMINOUS WARNING</DogName>
<Trainer id="116957">P Smith</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>33.5</Weight>
<StartPrice>$3.60</StartPrice>
<Handicap />
<Margin1>5.74</Margin1>
<Margin2>5.74</Margin2>
<PIR>M/22</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>10.58</SplitMargin>
<RunTime>23.71</RunTime>
<Prizemoney />
</Dog>
<Dog id="1550070062">
<Place>3</Place>
<DogName>JACKIE JAI</DogName>
<Trainer id="304702">C Sriboon</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>31.3</Weight>
<StartPrice>$14.40</StartPrice>
<Handicap />
<Margin1>6.80</Margin1>
<Margin2>1.06</Margin2>
<PIR>M/34</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>10.63</SplitMargin>
<RunTime>23.79</RunTime>
<Prizemoney />
</Dog>
<Dog id="124885844">
<Place>4</Place>
<DogName>CASSIUS MONELLI</DogName>
<Trainer id="109579">N Lund</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>30.4</Weight>
<StartPrice>$10.40</StartPrice>
<Handicap />
<Margin1>7.11</Margin1>
<Margin2>0.31</Margin2>
<PIR>M/43</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>10.64</SplitMargin>
<RunTime>23.81</RunTime>
<Prizemoney />
</Dog>
<Dog id="1448580020">
<Place>5</Place>
<DogName>KALANI WILLOW</DogName>
<Trainer id="131138">D Goudge</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>26.9</Weight>
<StartPrice>$18.70</StartPrice>
<Handicap />
<Margin1>8.27</Margin1>
<Margin2>1.16</Margin2>
<PIR>M/55</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>10.73</SplitMargin>
<RunTime>23.89</RunTime>
<Prizemoney />
</Dog>
<Dog id="198170053">
<Place>6</Place>
<DogName>GO PIES</DogName>
<Trainer id="110650">R Clark</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>39.1</Weight>
<StartPrice>$3.40F</StartPrice>
<Handicap />
<Margin1>9.07</Margin1>
<Margin2>0.80</Margin2>
<PIR>S/66</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>10.90</SplitMargin>
<RunTime>23.95</RunTime>
<Prizemoney />
</Dog>
<Dog id="127028573">
<Place>7</Place>
<DogName>LITTLE WOMEN</DogName>
<Trainer id="13497">N Cachia</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>27.6</Weight>
<StartPrice>$6.60</StartPrice>
<Handicap />
<Margin1>18.73</Margin1>
<Margin2>9.66</Margin2>
<PIR>M/87</PIR>
<Checks>11</Checks>
<Comments />
<SplitMargin>10.92</SplitMargin>
<RunTime>24.62</RunTime>
<Prizemoney />
</Dog>
<Dog id="120344216">
<Place>F</Place>
<DogName>YOU RIPPA PIPPA</DogName>
<Trainer id="127317">S Bruce</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>26.4</Weight>
<StartPrice>$19.80</StartPrice>
<Handicap />
<Margin1 />
<Margin2 />
<PIR>M/7</PIR>
<Checks>11</Checks>
<Comments />
<SplitMargin>10.91</SplitMargin>
<RunTime />
<Prizemoney />
</Dog>
<Dog id="354609412">
<Place>R</Place>
<DogName>BLACK TESS</DogName>
<Trainer id="106282">E Lloyd</Trainer>
<Box />
<Rug>9</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="120344232">
<Place>R</Place>
<DogName>LEKTRA VIKI</DogName>
<Trainer id="114867">N Lenehan</Trainer>
<Box />
<Rug>10</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Times>
<WinTime>23.31</WinTime>
<Split1Time>10.44</Split1Time>
<Split1Rug>2</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>5.30</WinDiv>
<Place1Div>1.80</Place1Div>
<Place2Div>1.10</Place2Div>
<Place3Div>3.50</Place3Div>
</Dividends>
<Exotics>
<Quin>10.40</Quin>
<Exacta>25.10</Exacta>
<Trifecta>139.80</Trifecta>
<Pick4>819.00</Pick4>
<RD>43.40</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="436862505">
<RaceNum>8</RaceNum>
<RaceName>ON-SITE ENGINEERING</RaceName>
<RaceTime>05:34PM</RaceTime>
<Distance>485m</Distance>
<RaceGrade>Mixed 4/5</RaceGrade>
<Dog id="186628515">
<Place>1</Place>
<DogName>GO NATALIE GO</DogName>
<Trainer id="108840">F Meyer</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>27.3</Weight>
<StartPrice>$11.00</StartPrice>
<Handicap />
<Margin1>0.06</Margin1>
<Margin2 />
<PIR>M/122</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.57</SplitMargin>
<RunTime>27.65</RunTime>
<Prizemoney />
</Dog>
<Dog id="231587250">
<Place>2</Place>
<DogName>KNOCKOUT FANTASY</DogName>
<Trainer id="110650">R Clark</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>33.7</Weight>
<StartPrice>$2.00F</StartPrice>
<Handicap />
<Margin1>0.06</Margin1>
<Margin2>0.06</Margin2>
<PIR>M/211</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.58</SplitMargin>
<RunTime>27.65</RunTime>
<Prizemoney />
</Dog>
<Dog id="1460060042">
<Place>3</Place>
<DogName>MILKY JONES</DogName>
<Trainer id="137739">C Dew</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>35.0</Weight>
<StartPrice>$2.30</StartPrice>
<Handicap />
<Margin1>0.60</Margin1>
<Margin2>0.54</Margin2>
<PIR>M/433</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.66</SplitMargin>
<RunTime>27.69</RunTime>
<Prizemoney />
</Dog>
<Dog id="118702971">
<Place>4</Place>
<DogName>CINNAMON ROSE</DogName>
<Trainer id="309138">A Formosa</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>27.3</Weight>
<StartPrice>$17.00</StartPrice>
<Handicap />
<Margin1>2.57</Margin1>
<Margin2>1.97</Margin2>
<PIR>M/344</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.63</SplitMargin>
<RunTime>27.83</RunTime>
<Prizemoney />
</Dog>
<Dog id="121715965">
<Place>5</Place>
<DogName>FARADAY</DogName>
<Trainer id="113876">P Abela</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>36.3</Weight>
<StartPrice>$25.40</StartPrice>
<Handicap />
<Margin1>3.13</Margin1>
<Margin2>0.56</Margin2>
<PIR>S/867</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.93</SplitMargin>
<RunTime>27.87</RunTime>
<Prizemoney />
</Dog>
<Dog id="120344229">
<Place>6</Place>
<DogName>LEKTRA BRANDY</DogName>
<Trainer id="114867">N Lenehan</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>27.3</Weight>
<StartPrice>$35.70</StartPrice>
<Handicap />
<Margin1>4.80</Margin1>
<Margin2>1.67</Margin2>
<PIR>M/555</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>6.87</SplitMargin>
<RunTime>27.99</RunTime>
<Prizemoney />
</Dog>
<Dog id="133789546">
<Place>7</Place>
<DogName>BERELUKE</DogName>
<Trainer id="114195">N Stanley</Trainer>
<Box>3</Box>
<Rug>9</Rug>
<Weight>30.0</Weight>
<StartPrice>$38.80</StartPrice>
<Handicap />
<Margin1>7.14</Margin1>
<Margin2>2.34</Margin2>
<PIR>M/676</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.89</SplitMargin>
<RunTime>28.15</RunTime>
<Prizemoney />
</Dog>
<Dog id="2056920003">
<Place>T</Place>
<DogName>CLOUD COVER</DogName>
<Trainer id="163558">P Mathieson</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>35.0</Weight>
<StartPrice>$38.70</StartPrice>
<Handicap />
<Margin1 />
<Margin2 />
<PIR>M/788</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.93</SplitMargin>
<RunTime />
<Prizemoney />
</Dog>
<Dog id="1912510003">
<Place>S</Place>
<DogName>WILBUR DEEDS</DogName>
<Trainer id="119251">G Anders</Trainer>
<Box />
<Rug>3</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="139709867">
<Place>R</Place>
<DogName>RUSTY SPROCKET</DogName>
<Trainer id="105961">S Blacksell</Trainer>
<Box />
<Rug>10</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Times>
<WinTime>27.65</WinTime>
<Split1Time>6.57</Split1Time>
<Split1Rug>5</Split1Rug>