<?xml version="1.0"?>
<!DOCTYPE Meet [<!ELEMENT Meet (Track,Date,Race+)>
<!ELEMENT Track (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Race (RaceNum,RaceName,RaceTime,Distance,RaceGrade,Dog+,Times+,Dividends+,Exotics+)>
<!ELEMENT RaceNum (#PCDATA)>
<!ELEMENT RaceName (#PCDATA)>
<!ELEMENT RaceTime (#PCDATA)>
<!ELEMENT Distance (#PCDATA)>
<!ELEMENT RaceGrade (#PCDATA)>
<!ELEMENT Dog (Place,DogName,Trainer,Box,Rug,Weight,StartPrice,Handicap,Margin1,Margin2,PIR,SplitMargin,RunTime)>
<!ELEMENT Place (#PCDATA)>
<!ELEMENT DogName (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>
<!ELEMENT Box (#PCDATA)>
<!ELEMENT Rug (#PCDATA)>
<!ELEMENT Race (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT StartPrice (#PCDATA)>
<!ELEMENT Handicap (#PCDATA)>
<!ELEMENT Margin1 (#PCDATA)>
<!ELEMENT Margin2 (#PCDATA)>
<!ELEMENT PIR (#PCDATA)>
<!ELEMENT SplitMargin (#PCDATA)>
<!ELEMENT RunTime (#PCDATA)>
<!ELEMENT Times (WinTime,Split1Time,Split1Rug,Split2Time,Split2Rug,Split3Time,Split3Rug)>
<!ELEMENT WinTime (#PCDATA)>
<!ELEMENT Split1Time (#PCDATA)>
<!ELEMENT Split1Rug (#PCDATA)>
<!ELEMENT Split2Time (#PCDATA)>
<!ELEMENT Split2Rug (#PCDATA)>
<!ELEMENT Split3Time (#PCDATA)>
<!ELEMENT Split3Rug (#PCDATA)>
<!ELEMENT Dividends (WinDiv,Place1Div,Place2Div,Place3Div)>
<!ELEMENT WinDiv (#PCDATA)>
<!ELEMENT Place1Div (#PCDATA)>
<!ELEMENT Place2Div (#PCDATA)>
<!ELEMENT Place3Div (#PCDATA)>
<!ELEMENT Exotics (Quin,Exacta,Trifecta,Pick4,RD,DD,Quad)>
<!ELEMENT Quin (#PCDATA)>
<!ELEMENT Exacta (#PCDATA)>
<!ELEMENT Trifecta (#PCDATA)>
<!ELEMENT Pick4 (#PCDATA)>
<!ELEMENT RD (#PCDATA)>
<!ELEMENT DD (#PCDATA)>
<!ELEMENT Quad (#PCDATA)>
]>
<Meet id="228407019">
<Track>Bendigo</Track>
<Date>04 Oct 17</Date>
<Race id="261264515">
<RaceNum>1</RaceNum>
<RaceName>HIT 91.9 BENDIGO (300+RANK)</RaceName>
<RaceTime>03:04PM</RaceTime>
<Distance>425m</Distance>
<RaceGrade>Maiden</RaceGrade>
<Dog id="275790069">
<Place>1</Place>
<DogName>SWEET ANGEL</DogName>
<Trainer id="68026">P Triaca</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>25.2</Weight>
<StartPrice>$16.40</StartPrice>
<Handicap />
<Margin1>0.06</Margin1>
<Margin2 />
<PIR>M/211</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.76</SplitMargin>
<RunTime>24.64</RunTime>
<Prizemoney>500.00</Prizemoney>
</Dog>
<Dog id="1772800022">
<Place>2</Place>
<DogName>MOVE IT</DogName>
<Trainer id="129114">D Bunn</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>35.8</Weight>
<StartPrice>$2.00F</StartPrice>
<Handicap />
<Margin1>0.06</Margin1>
<Margin2>0.06</Margin2>
<PIR>M/332</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.81</SplitMargin>
<RunTime>24.64</RunTime>
<Prizemoney>140.00</Prizemoney>
</Dog>
<Dog id="1649540032">
<Place>3</Place>
<DogName>STELLA MCIVOR</DogName>
<Trainer id="97352">P Franklin</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>25.8</Weight>
<StartPrice>$3.00</StartPrice>
<Handicap />
<Margin1>1.66</Margin1>
<Margin2>1.60</Margin2>
<PIR>S/655</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.98</SplitMargin>
<RunTime>24.76</RunTime>
<Prizemoney>70.00</Prizemoney>
</Dog>
<Dog id="1237400000">
<Place>4</Place>
<DogName>BIG BOY ROCKET</DogName>
<Trainer id="111351">D Gehan</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>31.4</Weight>
<StartPrice>$9.90</StartPrice>
<Handicap />
<Margin1>3.83</Margin1>
<Margin2>2.17</Margin2>
<PIR>S/444</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.92</SplitMargin>
<RunTime>24.91</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1474670103">
<Place>5</Place>
<DogName>MACADAMIA ROSE</DogName>
<Trainer id="133311">L Anstee</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>26.7</Weight>
<StartPrice>$16.10</StartPrice>
<Handicap />
<Margin1>4.87</Margin1>
<Margin2>1.04</Margin2>
<PIR>M/123</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>6.69</SplitMargin>
<RunTime>24.98</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1649540025">
<Place>6</Place>
<DogName>LARRY MCIVOR</DogName>
<Trainer id="97352">P Franklin</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>33.0</Weight>
<StartPrice>$11.80</StartPrice>
<Handicap />
<Margin1>5.97</Margin1>
<Margin2>1.10</Margin2>
<PIR>M/566</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.97</SplitMargin>
<RunTime>25.06</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="892600003">
<Place>7</Place>
<DogName>BADELAIDE ROAD</DogName>
<Trainer id="107111">J Hall</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>28.8</Weight>
<StartPrice>$32.50</StartPrice>
<Handicap />
<Margin1>6.46</Margin1>
<Margin2>0.49</Margin2>
<PIR>S/887</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>7.08</SplitMargin>
<RunTime>25.09</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="754430081">
<Place>8</Place>
<DogName>LITTLE NOVA</DogName>
<Trainer id="103349">B Hall</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>26.5</Weight>
<StartPrice>$39.70</StartPrice>
<Handicap />
<Margin1>7.93</Margin1>
<Margin2>1.47</Margin2>
<PIR>M/778</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>7.05</SplitMargin>
<RunTime>25.20</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="763790012">
<Place>S</Place>
<DogName>CAITLIN LOUISE</DogName>
<Trainer id="77242">D Basile</Trainer>
<Box />
<Rug>9</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="1619850046">
<Place>R</Place>
<DogName>IZZY KYMTONY</DogName>
<Trainer id="121129">R Tolson</Trainer>
<Box />
<Rug>10</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Times>
<WinTime>24.64</WinTime>
<Split1Time>6.69</Split1Time>
<Split1Rug>1</Split1Rug>
<Split2Time>11.71</Split2Time>
<Split2Rug>3</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>16.40</WinDiv>
<Place1Div>3.80</Place1Div>
<Place2Div>1.40</Place2Div>
<Place3Div>1.04</Place3Div>
</Dividends>
<Exotics>
<Quin>13.10</Quin>
<Exacta>42.20</Exacta>
<Trifecta>112.00</Trifecta>
<Pick4>568.70</Pick4>
<RD />
<DD />
<Quad />
</Exotics>
</Race>
<Race id="261264514">
<RaceNum>2</RaceNum>
<RaceName>RAILWAY STATION HOTEL (300+RANK)</RaceName>
<RaceTime>03:22PM</RaceTime>
<Distance>425m</Distance>
<RaceGrade>Grade 7</RaceGrade>
<Dog id="1199510034">
<Place>1</Place>
<DogName>CRAINY'S WISH</DogName>
<Trainer id="10249">M Salvatore</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>31.2</Weight>
<StartPrice>$2.10F</StartPrice>
<Handicap />
<Margin1>6.07</Margin1>
<Margin2 />
<PIR>M/111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.59</SplitMargin>
<RunTime>23.95</RunTime>
<Prizemoney>660.00</Prizemoney>
</Dog>
<Dog id="109766111">
<Place>2</Place>
<DogName>SERENDIPITY GOLD</DogName>
<Trainer id="19694">S Elmes</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>31.8</Weight>
<StartPrice>$6.30</StartPrice>
<Handicap />
<Margin1>6.07</Margin1>
<Margin2>6.07</Margin2>
<PIR>M/322</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.70</SplitMargin>
<RunTime>24.38</RunTime>
<Prizemoney>190.00</Prizemoney>
</Dog>
<Dog id="1912510011">
<Place>3</Place>
<DogName>SAINT RAY</DogName>
<Trainer id="111351">D Gehan</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>31.9</Weight>
<StartPrice>$3.80</StartPrice>
<Handicap />
<Margin1>7.20</Margin1>
<Margin2>1.13</Margin2>
<PIR>M/233</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.66</SplitMargin>
<RunTime>24.46</RunTime>
<Prizemoney>95.00</Prizemoney>
</Dog>
<Dog id="1346610002">
<Place>4</Place>
<DogName>ALL INN YOUI</DogName>
<Trainer id="132137">T Duncan</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>33.5</Weight>
<StartPrice>$9.90</StartPrice>
<Handicap />
<Margin1>8.96</Margin1>
<Margin2>1.76</Margin2>
<PIR>M/444</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.75</SplitMargin>
<RunTime>24.58</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="738120016">
<Place>5</Place>
<DogName>WITH A WHISPER</DogName>
<Trainer id="104389">L Desmond</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>28.2</Weight>
<StartPrice>$22.20</StartPrice>
<Handicap />
<Margin1>9.24</Margin1>
<Margin2>0.29</Margin2>
<PIR>M/555</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.77</SplitMargin>
<RunTime>24.60</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1457180007">
<Place>6</Place>
<DogName>CUP HALF FULL</DogName>
<Trainer id="130403">J Torr</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>29.2</Weight>
<StartPrice>$7.20</StartPrice>
<Handicap />
<Margin1>11.36</Margin1>
<Margin2>2.11</Margin2>
<PIR>M/666</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.85</SplitMargin>
<RunTime>24.75</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1295030046">
<Place>S</Place>
<DogName>WAS A BANKER</DogName>
<Trainer id="77242">D Basile</Trainer>
<Box />
<Rug>2</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="894980011">
<Place>S</Place>
<DogName>CRACKERJACK BOOF</DogName>
<Trainer id="77242">D Basile</Trainer>
<Box />
<Rug>8</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>23.95</WinTime>
<Split1Time>6.59</Split1Time>
<Split1Rug>4</Split1Rug>
<Split2Time>11.49</Split2Time>
<Split2Rug>4</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.10</WinDiv>
<Place1Div>1.04</Place1Div>
<Place2Div>3.10</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>4.70</Quin>
<Exacta>9.20</Exacta>
<Trifecta>32.80</Trifecta>
<Pick4>51.20</Pick4>
<RD>61.30</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="261264519">
<RaceNum>3</RaceNum>
<RaceName>BENDIGO ADVERTISER (300+RANK)</RaceName>
<RaceTime>03:39PM</RaceTime>
<Distance>500m</Distance>
<RaceGrade>Grade 7</RaceGrade>
<Dog id="1258790022">
<Place>1</Place>
<DogName>AVATAR OCTANE</DogName>
<Trainer id="63125">R Boehm</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>32.6</Weight>
<StartPrice>$3.60</StartPrice>
<Handicap />
<Margin1>9.51</Margin1>
<Margin2 />
<PIR>M/111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.67</SplitMargin>
<RunTime>28.53</RunTime>
<Prizemoney>660.00</Prizemoney>
</Dog>
<Dog id="1462790015">
<Place>2</Place>
<DogName>MAC'S INTENTION</DogName>
<Trainer id="62891">K Bentley</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>33.8</Weight>
<StartPrice>$6.20</StartPrice>
<Handicap />
<Margin1>9.51</Margin1>
<Margin2>9.51</Margin2>
<PIR>M/322</PIR>
<Checks>3</Checks>
<Comments />
<SplitMargin>7.02</SplitMargin>
<RunTime>29.20</RunTime>
<Prizemoney>190.00</Prizemoney>
</Dog>
<Dog id="856390036">
<Place>3</Place>
<DogName>WINNIE</DogName>
<Trainer id="68026">P Triaca</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>24.4</Weight>
<StartPrice>$7.40</StartPrice>
<Handicap />
<Margin1>10.69</Margin1>
<Margin2>1.17</Margin2>
<PIR>S/543</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>7.08</SplitMargin>
<RunTime>29.28</RunTime>
<Prizemoney>95.00</Prizemoney>
</Dog>
<Dog id="999420002">
<Place>4</Place>
<DogName>SPORTS GAIRN</DogName>
<Trainer id="111351">D Gehan</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>31.6</Weight>
<StartPrice>$15.70</StartPrice>
<Handicap />
<Margin1>13.21</Margin1>
<Margin2>2.53</Margin2>
<PIR>M/754</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>7.20</SplitMargin>
<RunTime>29.46</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1092430206">
<Place>5</Place>
<DogName>ROCKSTAR BARNES</DogName>
<Trainer id="129172">B Kinder</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>36.1</Weight>
<StartPrice>$7.90</StartPrice>
<Handicap />
<Margin1>15.44</Margin1>
<Margin2>2.23</Margin2>
<PIR>M/435</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>7.07</SplitMargin>
<RunTime>29.61</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1805750012">
<Place>6</Place>
<DogName>DESTINI LIMA</DogName>
<Trainer id="132975">S Coates</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>37.6</Weight>
<StartPrice>$2.90F</StartPrice>
<Handicap />
<Margin1>17.81</Margin1>
<Margin2>2.37</Margin2>
<PIR>M/266</PIR>
<Checks>6</Checks>
<Comments />
<SplitMargin>6.90</SplitMargin>
<RunTime>29.78</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1247550019">
<Place>7</Place>
<DogName>JUST RED</DogName>
<Trainer id="117839">J Caulfield</Trainer>
<Box>2</Box>
<Rug>9</Rug>
<Weight>28.0</Weight>
<StartPrice>$14.10</StartPrice>
<Handicap />
<Margin1>19.40</Margin1>
<Margin2>1.59</Margin2>
<PIR>M/677</PIR>
<Checks>9</Checks>
<Comments />
<SplitMargin>7.11</SplitMargin>
<RunTime>29.89</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1158600001">
<Place>S</Place>
<DogName>AVATAR DJAY</DogName>
<Trainer id="63125">R Boehm</Trainer>
<Box />
<Rug>2</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="1426130003">
<Place>S</Place>
<DogName>BANJO SNOOPY</DogName>
<Trainer id="138164">J La Rosa</Trainer>
<Box />
<Rug>4</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Times>
<WinTime>28.53</WinTime>
<Split1Time>6.67</Split1Time>
<Split1Rug>7</Split1Rug>
<Split2Time>15.56</Split2Time>
<Split2Rug>7</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>3.60</WinDiv>
<Place1Div>2.40</Place1Div>
<Place2Div>3.60</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>11.70</Quin>
<Exacta>11.30</Exacta>
<Trifecta>171.30</Trifecta>
<Pick4>673.10</Pick4>
<RD>5.80</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="261264513">
<RaceNum>4</RaceNum>
<RaceName>GOLDEN CITY CONCRETE PUMPING (300+RANK)</RaceName>
<RaceTime>03:57PM</RaceTime>
<Distance>425m</Distance>
<RaceGrade>Grade 7</RaceGrade>
<Dog id="1595000034">
<Place>1</Place>
<DogName>NO LAYING BACK</DogName>
<Trainer id="129725">G Gledhill</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>26.3</Weight>
<StartPrice>$7.10</StartPrice>
<Handicap />
<Margin1>0.61</Margin1>
<Margin2 />
<PIR>Q/111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.58</SplitMargin>
<RunTime>24.37</RunTime>
<Prizemoney>660.00</Prizemoney>
</Dog>
<Dog id="1580930001">
<Place>2</Place>
<DogName>OUTTA AMMO</DogName>
<Trainer id="68044">R Fisher</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>31.6</Weight>
<StartPrice>$4.30</StartPrice>
<Handicap />
<Margin1>0.61</Margin1>
<Margin2>0.61</Margin2>
<PIR>M/333</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.81</SplitMargin>
<RunTime>24.41</RunTime>
<Prizemoney>190.00</Prizemoney>
</Dog>
<Dog id="1474670002">
<Place>3</Place>
<DogName>AVATAR DODGE</DogName>
<Trainer id="63125">R Boehm</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>30.1</Weight>
<StartPrice>$7.00</StartPrice>
<Handicap />
<Margin1>1.71</Margin1>
<Margin2>1.10</Margin2>
<PIR>M/222</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.79</SplitMargin>
<RunTime>24.49</RunTime>
<Prizemoney>95.00</Prizemoney>
</Dog>
<Dog id="1560320014">
<Place>4</Place>
<DogName>COOL AL</DogName>
<Trainer id="121129">R Tolson</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>34.9</Weight>
<StartPrice>$20.30</StartPrice>
<Handicap />
<Margin1>3.34</Margin1>
<Margin2>1.63</Margin2>
<PIR>M/544</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.86</SplitMargin>
<RunTime>24.60</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1812260004">
<Place>5</Place>
<DogName>PRINCE ROHNOMY</DogName>
<Trainer id="132641">J Burch</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>33.1</Weight>
<StartPrice>$2.80F</StartPrice>
<Handicap />
<Margin1>6.84</Margin1>
<Margin2>3.50</Margin2>
<PIR>M/765</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.91</SplitMargin>
<RunTime>24.84</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1435640033">
<Place>6</Place>
<DogName>JAI JAI AWAY</DogName>
<Trainer id="129725">G Gledhill</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>31.0</Weight>
<StartPrice>$13.50</StartPrice>
<Handicap />
<Margin1>10.61</Margin1>
<Margin2>3.77</Margin2>
<PIR>M/456</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.84</SplitMargin>
<RunTime>25.11</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1184050043">
<Place>7</Place>
<DogName>FINE WINE</DogName>
<Trainer id="7034">E Matthyssen</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>30.4</Weight>
<StartPrice>$5.60</StartPrice>
<Handicap />
<Margin1>13.47</Margin1>
<Margin2>2.86</Margin2>
<PIR>M/677</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>6.88</SplitMargin>
<RunTime>25.31</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>24.37</WinTime>
<Split1Time>6.58</Split1Time>
<Split1Rug>8</Split1Rug>
<Split2Time>11.46</Split2Time>
<Split2Rug>8</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>7.10</WinDiv>
<Place1Div>5.60</Place1Div>
<Place2Div>2.40</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>11.00</Quin>
<Exacta>33.20</Exacta>
<Trifecta>112.40</Trifecta>
<Pick4>1044.30</Pick4>
<RD>29.90</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="261264508">
<RaceNum>5</RaceNum>
<RaceName>CHASERS FUNCTION CENTRE (300+RANK)</RaceName>
<RaceTime>04:14PM</RaceTime>
<Distance>425m</Distance>
<RaceGrade>Grade 5</RaceGrade>
<Dog id="1429080002">
<Place>1</Place>
<DogName>EL GRAND KNOCKA</DogName>
<Trainer id="7045">R Nicholls</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>33.0</Weight>
<StartPrice>$10.80</StartPrice>
<Handicap />
<Margin1>2.06</Margin1>
<Margin2 />
<PIR>M/111</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.71</SplitMargin>
<RunTime>24.26</RunTime>
<Prizemoney>660.00</Prizemoney>
</Dog>
<Dog id="1554130006">
<Place>2</Place>
<DogName>MEENIYAN JET</DogName>
<Trainer id="132975">S Coates</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>32.3</Weight>
<StartPrice>$8.50</StartPrice>
<Handicap />
<Margin1>2.06</Margin1>
<Margin2>2.06</Margin2>
<PIR>M/222</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.73</SplitMargin>
<RunTime>24.40</RunTime>
<Prizemoney>190.00</Prizemoney>
</Dog>
<Dog id="1641950013">
<Place>3</Place>
<DogName>COSMIC NOSEY</DogName>
<Trainer id="132641">J Burch</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>28.4</Weight>
<StartPrice>$2.00F</StartPrice>
<Handicap />
<Margin1>2.73</Margin1>
<Margin2>0.67</Margin2>
<PIR>M/533</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.80</SplitMargin>
<RunTime>24.45</RunTime>
<Prizemoney>95.00</Prizemoney>
</Dog>
<Dog id="887800022">
<Place>4</Place>
<DogName>ALL INN TARA</DogName>
<Trainer id="132137">T Duncan</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>27.4</Weight>
<StartPrice>$8.50</StartPrice>
<Handicap />
<Margin1>3.37</Margin1>
<Margin2>0.64</Margin2>
<PIR>M/644</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.85</SplitMargin>
<RunTime>24.50</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="886340129">
<Place>5</Place>
<DogName>PADDY'S MIDNIGHT</DogName>
<Trainer id="121068">P Cusack</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>25.7</Weight>
<StartPrice>$22.50</StartPrice>
<Handicap />
<Margin1>4.81</Margin1>
<Margin2>1.44</Margin2>
<PIR>M/465</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.78</SplitMargin>
<RunTime>24.60</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1235880020">
<Place>6</Place>
<DogName>GONE RUSTY</DogName>
<Trainer id="129557">C Rose</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>27.0</Weight>
<StartPrice>$5.90</StartPrice>
<Handicap />
<Margin1>6.34</Margin1>
<Margin2>1.53</Margin2>
<PIR>M/756</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.87</SplitMargin>
<RunTime>24.70</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="743640020">
<Place>7</Place>
<DogName>MINCA MAN</DogName>
<Trainer id="94459">R Hayes</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>34.0</Weight>
<StartPrice>$23.30</StartPrice>
<Handicap />
<Margin1>6.47</Margin1>
<Margin2>0.13</Margin2>
<PIR>M/877</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.94</SplitMargin>
<RunTime>24.71</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1745540008">
<Place>8</Place>
<DogName>TOP ALCOHOL</DogName>
<Trainer id="190881">E Bowles</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>30.5</Weight>
<StartPrice>$10.20</StartPrice>
<Handicap />
<Margin1>8.61</Margin1>
<Margin2>2.14</Margin2>
<PIR>M/388</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.75</SplitMargin>
<RunTime>24.86</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1429080006">
<Place>S</Place>
<DogName>SENORITA PEPE</DogName>
<Trainer id="129172">B Kinder</Trainer>
<Box />
<Rug>10</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="892600001">
<Place>R</Place>
<DogName>REVEREND JOHN</DogName>
<Trainer id="103349">B Hall</Trainer>
<Box />
<Rug>9</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Times>
<WinTime>24.26</WinTime>
<Split1Time>6.71</Split1Time>
<Split1Rug>6</Split1Rug>
<Split2Time>11.61</Split2Time>
<Split2Rug>6</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>10.80</WinDiv>
<Place1Div>2.70</Place1Div>
<Place2Div>1.80</Place2Div>
<Place3Div>1.10</Place3Div>
</Dividends>
<Exotics>
<Quin>39.10</Quin>
<Exacta>82.80</Exacta>
<Trifecta>270.30</Trifecta>
<Pick4>1479.20</Pick4>
<RD>106.30</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="261264516">
<RaceNum>6</RaceNum>
<RaceName>TOPCAT VIDEO PRODUCTIONS (300+RANK)</RaceName>
<RaceTime>04:32PM</RaceTime>
<Distance>500m</Distance>
<RaceGrade>Grade 5</RaceGrade>
<Dog id="918250014">
<Place>1</Place>
<DogName>LANCE LOMAR</DogName>
<Trainer id="106709">S Stefanos</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>32.4</Weight>
<StartPrice>$1.20F</StartPrice>
<Handicap />
<Margin1>2.23</Margin1>
<Margin2 />
<PIR>M/111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.65</SplitMargin>
<RunTime>28.40</RunTime>
<Prizemoney>660.00</Prizemoney>
</Dog>
<Dog id="1206250046">
<Place>2</Place>
<DogName>BERRIDALE BUDDIE</DogName>
<Trainer id="106709">S Stefanos</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>35.6</Weight>
<StartPrice>$13.70</StartPrice>
<Handicap />
<Margin1>2.23</Margin1>
<Margin2>2.23</Margin2>
<PIR>M/422</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>6.77</SplitMargin>
<RunTime>28.56</RunTime>
<Prizemoney>190.00</Prizemoney>
</Dog>
<Dog id="1152760033">
<Place>3</Place>
<DogName>FAB DREAM</DogName>
<Trainer id="131277">B Reid</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>32.7</Weight>
<StartPrice>$7.60</StartPrice>
<Handicap />
<Margin1>2.94</Margin1>
<Margin2>0.71</Margin2>
<PIR>M/554</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.88</SplitMargin>
<RunTime>28.61</RunTime>
<Prizemoney>95.00</Prizemoney>
</Dog>
<Dog id="1184050018">
<Place>4</Place>
<DogName>HEY HEY FOZZ</DogName>
<Trainer id="58663">S Doust</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>28.2</Weight>
<StartPrice>$21.80</StartPrice>
<Handicap />
<Margin1>3.97</Margin1>
<Margin2>1.03</Margin2>
<PIR>M/345</PIR>
<Checks>3</Checks>
<Comments />
<SplitMargin>6.74</SplitMargin>
<RunTime>28.68</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1184050041">
<Place>5</Place>
<DogName>CULLQUIN FRANK</DogName>
<Trainer id="109690">S Quinlan</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>32.0</Weight>
<StartPrice>$15.50</StartPrice>
<Handicap />
<Margin1>4.76</Margin1>
<Margin2>0.79</Margin2>
<PIR>M/233</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.70</SplitMargin>
<RunTime>28.73</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1184050020">
<Place>6</Place>
<DogName>WAIKIKI CREEK</DogName>
<Trainer id="118267">B Fothergill</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>27.4</Weight>
<StartPrice>$32.00</StartPrice>
<Handicap />
<Margin1>5.80</Margin1>
<Margin2>1.04</Margin2>
<PIR>M/666</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>7.07</SplitMargin>
<RunTime>28.81</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="612290027">
<Place>T</Place>
<DogName>IMA EBAY</DogName>
<Trainer id="128208">R Dunne</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>34.0</Weight>
<StartPrice>$43.40</StartPrice>
<Handicap />
<Margin1 />
<Margin2 />
<PIR>M/777</PIR>
<Checks>6</Checks>
<Comments />
<SplitMargin>7.21</SplitMargin>
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>28.40</WinTime>
<Split1Time>6.65</Split1Time>
<Split1Rug>1</Split1Rug>
<Split2Time>15.48</Split2Time>
<Split2Rug>1</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>1.20</WinDiv>
<Place1Div>1.00</Place1Div>
<Place2Div>4.80</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>4.80</Quin>
<Exacta>5.90</Exacta>
<Trifecta>16.00</Trifecta>
<Pick4>64.00</Pick4>
<RD>32.70</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="261264509">
<RaceNum>7</RaceNum>
<RaceName>HIP POCKET BENDIGO (300+RANK)</RaceName>
<RaceTime>04:49PM</RaceTime>
<Distance>425m</Distance>
<RaceGrade>Grade 5</RaceGrade>
<Dog id="1490820087">
<Place>1</Place>
<DogName>HYPNOTIC TRANCE</DogName>
<Trainer id="106709">S Stefanos</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>27.8</Weight>
<StartPrice>$2.50F</StartPrice>
<Handicap />
<Margin1>0.31</Margin1>
<Margin2 />
<PIR>M/111</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.63</SplitMargin>
<RunTime>24.28</RunTime>
<Prizemoney>660.00</Prizemoney>
</Dog>
<Dog id="1241510038">
<Place>2</Place>
<DogName>TOORALEE</DogName>
<Trainer id="106709">S Stefanos</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>30.9</Weight>
<StartPrice>$13.50</StartPrice>
<Handicap />
<Margin1>0.31</Margin1>
<Margin2>0.31</Margin2>
<PIR>M/773</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>6.79</SplitMargin>
<RunTime>24.30</RunTime>
<Prizemoney>190.00</Prizemoney>
</Dog>
<Dog id="892600001">
<Place>3</Place>
<DogName>REVEREND JOHN</DogName>
<Trainer id="103349">B Hall</Trainer>
<Box>1</Box>
<Rug>9</Rug>
<Weight>32.3</Weight>
<StartPrice>$23.50</StartPrice>
<Handicap />
<Margin1>1.13</Margin1>
<Margin2>0.81</Margin2>
<PIR>M/232</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.63</SplitMargin>
<RunTime>24.36</RunTime>
<Prizemoney>95.00</Prizemoney>
</Dog>
<Dog id="592760069">
<Place>4</Place>
<DogName>COSMIC SPUR</DogName>
<Trainer id="11264">E Fothergill</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>34.4</Weight>
<StartPrice>$2.70</StartPrice>
<Handicap />
<Margin1>1.17</Margin1>
<Margin2>0.04</Margin2>
<PIR>M/424</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.70</SplitMargin>
<RunTime>24.36</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="894980012">
<Place>5</Place>
<DogName>CRACKERJACK ROY</DogName>
<Trainer id="68026">P Triaca</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>34.2</Weight>
<StartPrice>$7.10</StartPrice>
<Handicap />
<Margin1>2.80</Margin1>
<Margin2>1.63</Margin2>
<PIR>M/646</PIR>
<Checks>3</Checks>
<Comments />
<SplitMargin>6.76</SplitMargin>
<RunTime>24.48</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="794560015">
<Place>6</Place>
<DogName>TAMILE LASS</DogName>
<Trainer id="129557">C Rose</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>26.3</Weight>
<StartPrice>$17.50</StartPrice>
<Handicap />
<Margin1>2.89</Margin1>
<Margin2>0.09</Margin2>
<PIR>M/557</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>6.71</SplitMargin>
<RunTime>24.48</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="1306460009">
<Place>7</Place>
<DogName>RAZZLE OAK</DogName>
<Trainer id="289389">J Egan</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>25.8</Weight>
<StartPrice>$17.00</StartPrice>
<Handicap />
<Margin1>3.69</Margin1>
<Margin2>0.80</Margin2>
<PIR>M/365</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.67</SplitMargin>
<RunTime>24.54</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="851640033">
<Place>8</Place>
<DogName>LUNCHMONEY LEWIS</DogName>
<Trainer id="108179">L Bicchieri</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>34.1</Weight>
<StartPrice>$18.90</StartPrice>
<Handicap />
<Margin1>4.21</Margin1>
<Margin2>0.53</Margin2>
<PIR>M/888</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>6.81</SplitMargin>
<RunTime>24.58</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="714150022">
<Place>S</Place>
<DogName>JUST RUN LEFT</DogName>
<Trainer id="77242">D Basile</Trainer>
<Box />
<Rug>1</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="1429080006">
<Place>S</Place>
<DogName>SENORITA PEPE</DogName>
<Trainer id="129172">B Kinder</Trainer>
<Box />
<Rug>10</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Times>
<WinTime>24.28</WinTime>
<Split1Time>6.63</Split1Time>
<Split1Rug>2</Split1Rug>
<Split2Time>11.53</Split2Time>
<Split2Rug>2</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.50</WinDiv>
<Place1Div>1.20</Place1Div>
<Place2Div>2.90</Place2Div>
<Place3Div>3.70</Place3Div>
</Dividends>
<Exotics>
<Quin>17.10</Quin>
<Exacta>24.50</Exacta>
<Trifecta>222.80</Trifecta>
<Pick4>630.60</Pick4>
<RD>5.80</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="261264517">
<RaceNum>8</RaceNum>
<RaceName>TAB - WE LOVE A BET (300+RANK)</RaceName>
<RaceTime>05:07PM</RaceTime>
<Distance>500m</Distance>
<RaceGrade>Grade 5</RaceGrade>
<Dog id="592760066">
<Place>1</Place>
<DogName>WISE HARRY</DogName>
<Trainer id="101219">T Fernandes</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>33.7</Weight>
<StartPrice>$1.90F</StartPrice>
<Handicap />
<Margin1>4.51</Margin1>
<Margin2 />
<PIR>M/111</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>6.57</SplitMargin>
<RunTime>28.41</RunTime>
<Prizemoney>660.00</Prizemoney>
</Dog>
<Dog id="974830014">
<Place>2</Place>
<DogName>BEKIM FIRE</DogName>
<Trainer id="138164">J La Rosa</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>31.7</Weight>
<StartPrice>$5.00</StartPrice>
<Handicap />
<Margin1>4.51</Margin1>