<?xml version="1.0"?>
<!DOCTYPE Meet [<!ELEMENT Meet (Track,Date,Race+)>
<!ELEMENT Track (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Race (RaceNum,RaceName,RaceTime,Distance,RaceGrade,Dog+,Times+,Dividends+,Exotics+)>
<!ELEMENT RaceNum (#PCDATA)>
<!ELEMENT RaceName (#PCDATA)>
<!ELEMENT RaceTime (#PCDATA)>
<!ELEMENT Distance (#PCDATA)>
<!ELEMENT RaceGrade (#PCDATA)>
<!ELEMENT Dog (Place,DogName,Trainer,Box,Rug,Weight,StartPrice,Handicap,Margin1,Margin2,PIR,SplitMargin,RunTime)>
<!ELEMENT Place (#PCDATA)>
<!ELEMENT DogName (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>
<!ELEMENT Box (#PCDATA)>
<!ELEMENT Rug (#PCDATA)>
<!ELEMENT Race (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT StartPrice (#PCDATA)>
<!ELEMENT Handicap (#PCDATA)>
<!ELEMENT Margin1 (#PCDATA)>
<!ELEMENT Margin2 (#PCDATA)>
<!ELEMENT PIR (#PCDATA)>
<!ELEMENT SplitMargin (#PCDATA)>
<!ELEMENT RunTime (#PCDATA)>
<!ELEMENT Times (WinTime,Split1Time,Split1Rug,Split2Time,Split2Rug,Split3Time,Split3Rug)>
<!ELEMENT WinTime (#PCDATA)>
<!ELEMENT Split1Time (#PCDATA)>
<!ELEMENT Split1Rug (#PCDATA)>
<!ELEMENT Split2Time (#PCDATA)>
<!ELEMENT Split2Rug (#PCDATA)>
<!ELEMENT Split3Time (#PCDATA)>
<!ELEMENT Split3Rug (#PCDATA)>
<!ELEMENT Dividends (WinDiv,Place1Div,Place2Div,Place3Div)>
<!ELEMENT WinDiv (#PCDATA)>
<!ELEMENT Place1Div (#PCDATA)>
<!ELEMENT Place2Div (#PCDATA)>
<!ELEMENT Place3Div (#PCDATA)>
<!ELEMENT Exotics (Quin,Exacta,Trifecta,Pick4,RD,DD,Quad)>
<!ELEMENT Quin (#PCDATA)>
<!ELEMENT Exacta (#PCDATA)>
<!ELEMENT Trifecta (#PCDATA)>
<!ELEMENT Pick4 (#PCDATA)>
<!ELEMENT RD (#PCDATA)>
<!ELEMENT DD (#PCDATA)>
<!ELEMENT Quad (#PCDATA)>
]>
<Meet id="314366333">
<Track>Cranbourne</Track>
<Date>20 Mar 19</Date>
<Race id="418893617">
<RaceNum>1</RaceNum>
<RaceName>TOP CAT VIDEO. MAX 6 DOGS</RaceName>
<RaceTime>06:48PM</RaceTime>
<Distance>520m</Distance>
<RaceGrade>Maiden</RaceGrade>
<Dog id="248395301">
<Place>1</Place>
<DogName>BUBBLES</DogName>
<Trainer id="130608">K Leek</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>34.4</Weight>
<StartPrice>$1.50F</StartPrice>
<Handicap />
<Margin1>4.50</Margin1>
<Margin2 />
<PIR>M/2111</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.52</SplitMargin>
<RunTime>30.29</RunTime>
<Prizemoney />
</Dog>
<Dog id="201711124">
<Place>2</Place>
<DogName>JAGUAR JESSIE</DogName>
<Trainer id="118033">G Clifton</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>28.0</Weight>
<StartPrice>$3.90</StartPrice>
<Handicap />
<Margin1>4.50</Margin1>
<Margin2>4.50</Margin2>
<PIR>M/1222</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.50</SplitMargin>
<RunTime>30.60</RunTime>
<Prizemoney />
</Dog>
<Dog id="1721210083">
<Place>3</Place>
<DogName>ZIPPING TEX</DogName>
<Trainer id="289389">J Egan</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>34.8</Weight>
<StartPrice>$28.20</StartPrice>
<Handicap />
<Margin1>19.87</Margin1>
<Margin2>15.37</Margin2>
<PIR>S/5544</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>5.80</SplitMargin>
<RunTime>31.68</RunTime>
<Prizemoney />
</Dog>
<Dog id="201711121">
<Place>4</Place>
<DogName>BLONDIE LOCKS</DogName>
<Trainer id="118033">G Clifton</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>27.1</Weight>
<StartPrice>$6.30</StartPrice>
<Handicap />
<Margin1>20.06</Margin1>
<Margin2>0.19</Margin2>
<PIR>M/3453</PIR>
<Checks>9</Checks>
<Comments />
<SplitMargin>5.68</SplitMargin>
<RunTime>31.69</RunTime>
<Prizemoney />
</Dog>
<Dog id="119977480">
<Place>5</Place>
<DogName>PACIFIC TITLE</DogName>
<Trainer id="127987">F Bickerton</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>28.8</Weight>
<StartPrice>$38.90</StartPrice>
<Handicap />
<Margin1>20.77</Margin1>
<Margin2>0.71</Margin2>
<PIR>S/6665</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.89</SplitMargin>
<RunTime>31.74</RunTime>
<Prizemoney />
</Dog>
<Dog id="1582320002">
<Place>6</Place>
<DogName>NATIONAL GIRL</DogName>
<Trainer id="112737">N Barnett</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>30.3</Weight>
<StartPrice>$19.60</StartPrice>
<Handicap />
<Margin1>24.60</Margin1>
<Margin2>3.83</Margin2>
<PIR>M/4336</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>5.69</SplitMargin>
<RunTime>32.01</RunTime>
<Prizemoney />
</Dog>
<Dog id="250697400">
<Place>R</Place>
<DogName>FLASHY DE GOEY</DogName>
<Trainer id="19964">I Ognjenovic</Trainer>
<Box />
<Rug>9</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="219044248">
<Place>R</Place>
<DogName>LIMERICK ICON</DogName>
<Trainer id="78872">R Sullivan</Trainer>
<Box />
<Rug>10</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>30.29</WinTime>
<Split1Time>5.50</Split1Time>
<Split1Rug>5</Split1Rug>
<Split2Time>21.28</Split2Time>
<Split2Rug>2</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>1.50</WinDiv>
<Place1Div>1.20</Place1Div>
<Place2Div>1.70</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>1.90</Quin>
<Exacta>2.60</Exacta>
<Trifecta>18.30</Trifecta>
<Pick4>32.00</Pick4>
<RD />
<DD />
<Quad />
</Exotics>
</Race>
<Race id="418893618">
<RaceNum>2</RaceNum>
<RaceName>TAB.COM.AU. MAX 6 DOGS</RaceName>
<RaceTime>07:12PM</RaceTime>
<Distance>311m</Distance>
<RaceGrade>Maiden</RaceGrade>
<Dog id="223990166">
<Place>1</Place>
<DogName>WE HAVE ISSUES</DogName>
<Trainer id="68783">J Harrington</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>25.6</Weight>
<StartPrice>$9.80</StartPrice>
<Handicap />
<Margin1>0.37</Margin1>
<Margin2 />
<PIR>Q/11</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>9.82</SplitMargin>
<RunTime>18.35</RunTime>
<Prizemoney />
</Dog>
<Dog id="184228736">
<Place>2</Place>
<DogName>JAZZIER</DogName>
<Trainer id="123282">J Cottrell</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>28.9</Weight>
<StartPrice>$2.50F</StartPrice>
<Handicap />
<Margin1>0.37</Margin1>
<Margin2>0.37</Margin2>
<PIR>S/44</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>10.15</SplitMargin>
<RunTime>18.38</RunTime>
<Prizemoney />
</Dog>
<Dog id="212762679">
<Place>3</Place>
<DogName>MISS LAQUISHA</DogName>
<Trainer id="115198">G Kearns</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>29.3</Weight>
<StartPrice>$40.70</StartPrice>
<Handicap />
<Margin1>1.49</Margin1>
<Margin2>1.11</Margin2>
<PIR>M/22</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>10.00</SplitMargin>
<RunTime>18.45</RunTime>
<Prizemoney />
</Dog>
<Dog id="195108941">
<Place>4</Place>
<DogName>SPOLLY SMASHER</DogName>
<Trainer id="11461">S Spoljaric</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>31.5</Weight>
<StartPrice>$5.30</StartPrice>
<Handicap />
<Margin1>1.59</Margin1>
<Margin2>0.10</Margin2>
<PIR>S/55</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>10.16</SplitMargin>
<RunTime>18.46</RunTime>
<Prizemoney />
</Dog>
<Dog id="214382425">
<Place>5</Place>
<DogName>SUPERIOR KRIS</DogName>
<Trainer id="132862">J Condon</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>27.6</Weight>
<StartPrice>$5.30</StartPrice>
<Handicap />
<Margin1>2.93</Margin1>
<Margin2>1.34</Margin2>
<PIR>S/33</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>10.03</SplitMargin>
<RunTime>18.55</RunTime>
<Prizemoney />
</Dog>
<Dog id="221747122">
<Place>6</Place>
<DogName>INTER ROSE</DogName>
<Trainer id="71288">H Collins</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>30.3</Weight>
<StartPrice>$3.50</StartPrice>
<Handicap />
<Margin1>6.53</Margin1>
<Margin2>3.60</Margin2>
<PIR>M/66</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>10.21</SplitMargin>
<RunTime>18.81</RunTime>
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>18.35</WinTime>
<Split1Time>9.82</Split1Time>
<Split1Rug>4</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>9.80</WinDiv>
<Place1Div>3.60</Place1Div>
<Place2Div>2.80</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>6.80</Quin>
<Exacta>29.80</Exacta>
<Trifecta>213.30</Trifecta>
<Pick4>1180.70</Pick4>
<RD>17.40</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="418893619">
<RaceNum>3</RaceNum>
<RaceName>SPOLLYS. MAX 6 DOGS</RaceName>
<RaceTime>07:31PM</RaceTime>
<Distance>311m</Distance>
<RaceGrade>Maiden</RaceGrade>
<Dog id="195108942">
<Place>1</Place>
<DogName>OH SPOLLY</DogName>
<Trainer id="11461">S Spoljaric</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>32.6</Weight>
<StartPrice>$2.70</StartPrice>
<Handicap />
<Margin1>5.23</Margin1>
<Margin2 />
<PIR>Q/11</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>9.75</SplitMargin>
<RunTime>17.96</RunTime>
<Prizemoney />
</Dog>
<Dog id="222735081">
<Place>2</Place>
<DogName>ASTON VINO</DogName>
<Trainer id="130148">T Womann</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>31.8</Weight>
<StartPrice>$3.70</StartPrice>
<Handicap />
<Margin1>5.23</Margin1>
<Margin2>5.23</Margin2>
<PIR>M/22</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>9.91</SplitMargin>
<RunTime>18.33</RunTime>
<Prizemoney />
</Dog>
<Dog id="253388773">
<Place>3</Place>
<DogName>MUZA'S BELLE</DogName>
<Trainer id="131829">K Minne</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>26.3</Weight>
<StartPrice>$2.60F</StartPrice>
<Handicap />
<Margin1>8.11</Margin1>
<Margin2>2.89</Margin2>
<PIR>M/33</PIR>
<Checks>7</Checks>
<Comments />
<SplitMargin>10.12</SplitMargin>
<RunTime>18.53</RunTime>
<Prizemoney />
</Dog>
<Dog id="181886061">
<Place>4</Place>
<DogName>ON DEGOEY</DogName>
<Trainer id="295198">V Daffy</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>26.6</Weight>
<StartPrice>$17.70</StartPrice>
<Handicap />
<Margin1>11.91</Margin1>
<Margin2>3.80</Margin2>
<PIR>M/44</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>10.26</SplitMargin>
<RunTime>18.79</RunTime>
<Prizemoney />
</Dog>
<Dog id="221744616">
<Place>5</Place>
<DogName>KIP YOUR BEST</DogName>
<Trainer id="121317">S Kipirtidis</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>33.7</Weight>
<StartPrice>$12.00</StartPrice>
<Handicap />
<Margin1>13.80</Margin1>
<Margin2>1.89</Margin2>
<PIR>M/65</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>10.36</SplitMargin>
<RunTime>18.93</RunTime>
<Prizemoney />
</Dog>
<Dog id="182631034">
<Place>6</Place>
<DogName>REGGIE HATTON</DogName>
<Trainer id="100843">J Forrest</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>33.3</Weight>
<StartPrice>$52.40</StartPrice>
<Handicap />
<Margin1>16.23</Margin1>
<Margin2>2.43</Margin2>
<PIR>M/56</PIR>
<Checks>7</Checks>
<Comments />
<SplitMargin>10.29</SplitMargin>
<RunTime>19.10</RunTime>
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>17.96</WinTime>
<Split1Time>9.75</Split1Time>
<Split1Rug>1</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.70</WinDiv>
<Place1Div>1.20</Place1Div>
<Place2Div>2.10</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>5.20</Quin>
<Exacta>12.00</Exacta>
<Trifecta>28.00</Trifecta>
<Pick4>94.90</Pick4>
<RD>131.60</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="416009233">
<RaceNum>4</RaceNum>
<RaceName>RAM LOCKSMITH FINAL (3-6 WINS) (VICGREYS)</RaceName>
<RaceTime>07:51PM</RaceTime>
<Distance>311m</Distance>
<RaceGrade>Restricted Win Final</RaceGrade>
<Dog id="195100424">
<Place>1</Place>
<DogName>DUE TO BURN</DogName>
<Trainer id="104203">D Davis</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>32.9</Weight>
<StartPrice>$1.60F</StartPrice>
<Handicap />
<Margin1>1.04</Margin1>
<Margin2 />
<PIR>M/11</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>9.60</SplitMargin>
<RunTime>17.79</RunTime>
<Prizemoney />
</Dog>
<Dog id="141674790">
<Place>2</Place>
<DogName>DEWANA SPRITE</DogName>
<Trainer id="110650">R Clark</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>31.4</Weight>
<StartPrice>$8.60</StartPrice>
<Handicap />
<Margin1>1.04</Margin1>
<Margin2>1.04</Margin2>
<PIR>M/33</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>9.66</SplitMargin>
<RunTime>17.87</RunTime>
<Prizemoney />
</Dog>
<Dog id="126153840">
<Place>3</Place>
<DogName>WHY NOT LEO</DogName>
<Trainer id="117169">G Carter</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>31.7</Weight>
<StartPrice>$37.20</StartPrice>
<Handicap />
<Margin1>3.17</Margin1>
<Margin2>2.13</Margin2>
<PIR>M/22</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>9.60</SplitMargin>
<RunTime>18.01</RunTime>
<Prizemoney />
</Dog>
<Dog id="196374475">
<Place>4</Place>
<DogName>LAYBACK CRUISER</DogName>
<Trainer id="67940">J Grima</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>32.3</Weight>
<StartPrice>$11.20</StartPrice>
<Handicap />
<Margin1>3.41</Margin1>
<Margin2>0.24</Margin2>
<PIR>M/55</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>9.75</SplitMargin>
<RunTime>18.03</RunTime>
<Prizemoney />
</Dog>
<Dog id="198626466">
<Place>5</Place>
<DogName>JUGDISH</DogName>
<Trainer id="127852">T Burns</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>28.2</Weight>
<StartPrice>$10.50</StartPrice>
<Handicap />
<Margin1>4.13</Margin1>
<Margin2>0.71</Margin2>
<PIR>M/44</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>9.74</SplitMargin>
<RunTime>18.08</RunTime>
<Prizemoney />
</Dog>
<Dog id="156360096">
<Place>6</Place>
<DogName>BEES ON FIRE</DogName>
<Trainer id="103096">M Johnson</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>35.1</Weight>
<StartPrice>$21.60</StartPrice>
<Handicap />
<Margin1>4.30</Margin1>
<Margin2>0.17</Margin2>
<PIR>M/66</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>9.82</SplitMargin>
<RunTime>18.09</RunTime>
<Prizemoney />
</Dog>
<Dog id="184224213">
<Place>7</Place>
<DogName>MAVERICK BOB</DogName>
<Trainer id="58389">M Cartechini</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>29.9</Weight>
<StartPrice>$11.90</StartPrice>
<Handicap />
<Margin1>6.40</Margin1>
<Margin2>2.10</Margin2>
<PIR>M/77</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>9.87</SplitMargin>
<RunTime>18.24</RunTime>
<Prizemoney />
</Dog>
<Dog id="198626460">
<Place>8</Place>
<DogName>KEL KNIGHT</DogName>
<Trainer id="127852">T Burns</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>30.7</Weight>
<StartPrice>$10.50</StartPrice>
<Handicap />
<Margin1>6.93</Margin1>
<Margin2>0.53</Margin2>
<PIR>M/88</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>10.01</SplitMargin>
<RunTime>18.28</RunTime>
<Prizemoney />
</Dog>
<Dog id="126745010">
<Place>R</Place>
<DogName>LETHAL LEVI</DogName>
<Trainer id="67962">D Hills</Trainer>
<Box />
<Rug>9</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="119991025">
<Place>R</Place>
<DogName>POLO PETE</DogName>
<Trainer id="105986">D Dean</Trainer>
<Box />
<Rug>10</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Times>
<WinTime>17.79</WinTime>
<Split1Time>9.60</Split1Time>
<Split1Rug>6</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>1.60</WinDiv>
<Place1Div>1.04</Place1Div>
<Place2Div>2.40</Place2Div>
<Place3Div>6.50</Place3Div>
</Dividends>
<Exotics>
<Quin>4.70</Quin>
<Exacta>7.40</Exacta>
<Trifecta>69.20</Trifecta>
<Pick4>352.50</Pick4>
<RD>16.20</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="418893616">
<RaceNum>5</RaceNum>
<RaceName>CRANBOURNE TO SANDOWN HT1</RaceName>
<RaceTime>08:11PM</RaceTime>
<Distance>520m</Distance>
<RaceGrade>Grade 5 Heat</RaceGrade>
<Dog id="2014670017">
<Place>1</Place>
<DogName>VELOCITY ALAINA</DogName>
<Trainer id="70049">B Thorneycroft</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>29.2</Weight>
<StartPrice>$2.00F</StartPrice>
<Handicap />
<Margin1>2.80</Margin1>
<Margin2 />
<PIR>M/2222</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>5.58</SplitMargin>
<RunTime>30.73</RunTime>
<Prizemoney />
</Dog>
<Dog id="1092720000">
<Place>2</Place>
<DogName>SPAZZY BLUE</DogName>
<Trainer id="6955">D Cortese</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>29.7</Weight>
<StartPrice>$31.30</StartPrice>
<Handicap />
<Margin1>2.80</Margin1>
<Margin2>2.80</Margin2>
<PIR>Q/1111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.56</SplitMargin>
<RunTime>30.92</RunTime>
<Prizemoney />
</Dog>
<Dog id="191521838">
<Place>3</Place>
<DogName>LOCK PEPPER</DogName>
<Trainer id="116928">S Kyriacopoulos</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>30.3</Weight>
<StartPrice>$3.90</StartPrice>
<Handicap />
<Margin1>3.49</Margin1>
<Margin2>0.69</Margin2>
<PIR>M/5433</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>5.67</SplitMargin>
<RunTime>30.97</RunTime>
<Prizemoney />
</Dog>
<Dog id="183878542">
<Place>4</Place>
<DogName>DYNA REAVER</DogName>
<Trainer id="71288">H Collins</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>34.5</Weight>
<StartPrice>$14.60</StartPrice>
<Handicap />
<Margin1>5.20</Margin1>
<Margin2>1.71</Margin2>
<PIR>M/7554</PIR>
<Checks>6</Checks>
<Comments />
<SplitMargin>5.79</SplitMargin>
<RunTime>31.09</RunTime>
<Prizemoney />
</Dog>
<Dog id="1389280010">
<Place>5</Place>
<DogName>DYNAMIC RAINBOW</DogName>
<Trainer id="132697">P Craig</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>29.0</Weight>
<StartPrice>$21.40</StartPrice>
<Handicap />
<Margin1>7.87</Margin1>
<Margin2>2.67</Margin2>
<PIR>M/3666</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>5.63</SplitMargin>
<RunTime>31.28</RunTime>
<Prizemoney />
</Dog>
<Dog id="2077970005">
<Place>6</Place>
<DogName>MAHI INDIAN</DogName>
<Trainer id="131098">P Kelly</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>36.9</Weight>
<StartPrice>$4.10</StartPrice>
<Handicap />
<Margin1>8.23</Margin1>
<Margin2>0.36</Margin2>
<PIR>M/4345</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>5.65</SplitMargin>
<RunTime>31.30</RunTime>
<Prizemoney />
</Dog>
<Dog id="120958951">
<Place>P</Place>
<DogName>GOODBYE GOLDIE</DogName>
<Trainer id="103096">M Johnson</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>40.0</Weight>
<StartPrice>$19.80</StartPrice>
<Handicap />
<Margin1 />
<Margin2 />
<PIR>M/6777</PIR>
<Checks>7</Checks>
<Comments />
<SplitMargin>5.75</SplitMargin>
<RunTime />
<Prizemoney />
</Dog>
<Dog id="1752820061">
<Place>S</Place>
<DogName>VIVIAN SHIRAZ</DogName>
<Trainer id="11461">S Spoljaric</Trainer>
<Box />
<Rug>6</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>30.73</WinTime>
<Split1Time>5.56</Split1Time>
<Split1Rug>1</Split1Rug>
<Split2Time>21.75</Split2Time>
<Split2Rug>1</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.00</WinDiv>
<Place1Div>1.30</Place1Div>
<Place2Div>11.50</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>28.50</Quin>
<Exacta>33.20</Exacta>
<Trifecta>133.00</Trifecta>
<Pick4>450.80</Pick4>
<RD>3.70</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="418893615">
<RaceNum>6</RaceNum>
<RaceName>CRANBOURNE TO SANDOWN HT2</RaceName>
<RaceTime>08:33PM</RaceTime>
<Distance>520m</Distance>
<RaceGrade>Grade 5 Heat</RaceGrade>
<Dog id="123941403">
<Place>1</Place>
<DogName>MERCEDES RED</DogName>
<Trainer id="105257">P Knott</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>29.0</Weight>
<StartPrice>$2.30F</StartPrice>
<Handicap />
<Margin1>2.16</Margin1>
<Margin2 />
<PIR>M/1111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.51</SplitMargin>
<RunTime>30.41</RunTime>
<Prizemoney />
</Dog>
<Dog id="1338350014">
<Place>2</Place>
<DogName>RODEO</DogName>
<Trainer id="121695">J Carr</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>30.6</Weight>
<StartPrice>$22.30</StartPrice>
<Handicap />
<Margin1>2.16</Margin1>
<Margin2>2.16</Margin2>
<PIR>M/2222</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.56</SplitMargin>
<RunTime>30.56</RunTime>
<Prizemoney />
</Dog>
<Dog id="132913297">
<Place>3</Place>
<DogName>LIBERAL NUNNIO</DogName>
<Trainer id="170703">D Klemke</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>32.6</Weight>
<StartPrice>$7.60</StartPrice>
<Handicap />
<Margin1>6.59</Margin1>
<Margin2>4.43</Margin2>
<PIR>M/6444</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.66</SplitMargin>
<RunTime>30.87</RunTime>
<Prizemoney />
</Dog>
<Dog id="119991023">
<Place>4</Place>
<DogName>EMPTY CHAMBER</DogName>
<Trainer id="105986">D Dean</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>32.2</Weight>
<StartPrice>$5.10</StartPrice>
<Handicap />
<Margin1>7.69</Margin1>
<Margin2>1.10</Margin2>
<PIR>M/8865</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>5.80</SplitMargin>
<RunTime>30.95</RunTime>
<Prizemoney />
</Dog>
<Dog id="131736466">
<Place>5</Place>
<DogName>YELREDDA SAINT</DogName>
<Trainer id="62311">J Imlach</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>32.6</Weight>
<StartPrice>$24.80</StartPrice>
<Handicap />
<Margin1>7.71</Margin1>
<Margin2>0.03</Margin2>
<PIR>M/4333</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.60</SplitMargin>
<RunTime>30.95</RunTime>
<Prizemoney />
</Dog>
<Dog id="131736454">
<Place>6</Place>
<DogName>SAPPHIRE POWER</DogName>
<Trainer id="130058">C Johannsen</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>30.6</Weight>
<StartPrice>$6.20</StartPrice>
<Handicap />
<Margin1>12.54</Margin1>
<Margin2>4.83</Margin2>
<PIR>M/3556</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.58</SplitMargin>
<RunTime>31.29</RunTime>
<Prizemoney />
</Dog>
<Dog id="1522350001">
<Place>7</Place>
<DogName>DOUSED IN MUD</DogName>
<Trainer id="6439">G Bartlett</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>29.0</Weight>
<StartPrice>$47.20</StartPrice>
<Handicap />
<Margin1>13.43</Margin1>
<Margin2>0.89</Margin2>
<PIR>M/5677</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>5.65</SplitMargin>
<RunTime>31.35</RunTime>
<Prizemoney />
</Dog>
<Dog id="166062490">
<Place>8</Place>
<DogName>DYNA KARA</DogName>
<Trainer id="71288">H Collins</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>27.7</Weight>
<StartPrice>$6.30</StartPrice>
<Handicap />
<Margin1>17.29</Margin1>
<Margin2>3.86</Margin2>
<PIR>M/7788</PIR>
<Checks>12</Checks>
<Comments />
<SplitMargin>5.66</SplitMargin>
<RunTime>31.62</RunTime>
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>30.41</WinTime>
<Split1Time>5.51</Split1Time>
<Split1Rug>2</Split1Rug>
<Split2Time>21.44</Split2Time>
<Split2Rug>2</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.30</WinDiv>
<Place1Div>1.04</Place1Div>
<Place2Div>3.20</Place2Div>
<Place3Div>2.70</Place3Div>
</Dividends>
<Exotics>
<Quin>32.50</Quin>
<Exacta>45.30</Exacta>
<Trifecta>169.90</Trifecta>
<Pick4>514.50</Pick4>
<RD>11.20</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="418893620">
<RaceNum>7</RaceNum>
<RaceName>Cranbournegreyhounds.com.au</RaceName>
<RaceTime>08:50PM</RaceTime>
<Distance>311m</Distance>
<RaceGrade>Free For All</RaceGrade>
<Dog id="126153841">
<Place>1</Place>
<DogName>WHY NOT BAZZAR</DogName>
<Trainer id="117169">G Carter</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>32.4</Weight>
<StartPrice>$4.40</StartPrice>
<Handicap />
<Margin1>1.66</Margin1>
<Margin2 />
<PIR>M/11</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>9.66</SplitMargin>
<RunTime>17.82</RunTime>
<Prizemoney />
</Dog>
<Dog id="119991025">
<Place>2</Place>
<DogName>POLO PETE</DogName>
<Trainer id="105986">D Dean</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>30.8</Weight>
<StartPrice>$18.70</StartPrice>
<Handicap />
<Margin1>1.66</Margin1>
<Margin2>1.66</Margin2>
<PIR>M/22</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>9.80</SplitMargin>
<RunTime>17.93</RunTime>
<Prizemoney />
</Dog>
<Dog id="131736469">
<Place>3</Place>
<DogName>EBONIQUE</DogName>
<Trainer id="62311">J Imlach</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>25.8</Weight>
<StartPrice>$45.40</StartPrice>
<Handicap />
<Margin1>3.33</Margin1>
<Margin2>1.67</Margin2>
<PIR>M/34</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>9.84</SplitMargin>
<RunTime>18.05</RunTime>
<Prizemoney />
</Dog>
<Dog id="224008126">
<Place>4</Place>
<DogName>JEBRYNAH HELIOS</DogName>
<Trainer id="132636">R Crisafi</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>26.8</Weight>
<StartPrice>$1.20F</StartPrice>
<Handicap />
<Margin1>4.26</Margin1>
<Margin2>0.93</Margin2>
<PIR>M/55</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>9.92</SplitMargin>
<RunTime>18.11</RunTime>
<Prizemoney />
</Dog>
<Dog id="119991024">
<Place>5</Place>
<DogName>WATER PISTOL</DogName>
<Trainer id="105986">D Dean</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>31.8</Weight>
<StartPrice>$32.80</StartPrice>
<Handicap />
<Margin1>4.77</Margin1>
<Margin2>0.51</Margin2>
<PIR>M/43</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>9.91</SplitMargin>
<RunTime>18.15</RunTime>
<Prizemoney />
</Dog>
<Dog id="118013579">
<Place>6</Place>
<DogName>GOLDEN ROMANCE</DogName>
<Trainer id="8282">R Edwards</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>27.1</Weight>
<StartPrice>$39.00</StartPrice>
<Handicap />
<Margin1>7.47</Margin1>
<Margin2>2.70</Margin2>
<PIR>M/67</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>9.99</SplitMargin>
<RunTime>18.34</RunTime>
<Prizemoney />
</Dog>
<Dog id="133000473">
<Place>7</Place>
<DogName>ALL YOU GOT</DogName>
<Trainer id="127874">C Cortese</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>23.9</Weight>
<StartPrice>$42.60</StartPrice>
<Handicap />
<Margin1>8.09</Margin1>
<Margin2>0.61</Margin2>
<PIR>S/76</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>10.05</SplitMargin>
<RunTime>18.38</RunTime>
<Prizemoney />
</Dog>
<Dog id="2003010006">
<Place>S</Place>
<DogName>AGENT VOILET</DogName>
<Trainer id="289389">J Egan</Trainer>
<Box />
<Rug>3</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>17.82</WinTime>
<Split1Time>9.66</Split1Time>
<Split1Rug>7</Split1Rug>
<Split2Time />
<Split2Rug />
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>4.40</WinDiv>
<Place1Div>1.90</Place1Div>
<Place2Div>5.00</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>33.20</Quin>
<Exacta>38.10</Exacta>
<Trifecta>199.40</Trifecta>
<Pick4>329.00</Pick4>
<RD>23.00</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="418893625">
<RaceNum>8</RaceNum>
<RaceName>RAPIDVITE ANIMAL PRODUCTS</RaceName>
<RaceTime>09:11PM</RaceTime>
<Distance>520m</Distance>
<RaceGrade>Free For All</RaceGrade>
<Dog id="1992530001">
<Place>1</Place>
<DogName>ASTON UTAH</DogName>
<Trainer id="8042">D Douch</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>36.9</Weight>
<StartPrice>$3.00</StartPrice>
<Handicap />
<Margin1>0.61</Margin1>
<Margin2 />
<PIR>Q/2111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.42</SplitMargin>
<RunTime>30.31</RunTime>
<Prizemoney />
</Dog>
<Dog id="1550070030">
<Place>2</Place>
<DogName>DESTROYER</DogName>
<Trainer id="120257">D Condon</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>34.0</Weight>
<StartPrice>$10.80</StartPrice>
<Handicap />
<Margin1>0.61</Margin1>
<Margin2>0.61</Margin2>
<PIR>M/4222</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>5.58</SplitMargin>
<RunTime>30.36</RunTime>
<Prizemoney />
</Dog>
<Dog id="2032450073">
<Place>3</Place>
<DogName>BLUEGRASS ICON</DogName>
<Trainer id="31676">M Sullivan</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>26.7</Weight>
<StartPrice>$7.50</StartPrice>
<Handicap />
<Margin1>1.96</Margin1>
<Margin2>1.34</Margin2>
<PIR>M/1333</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.40</SplitMargin>
<RunTime>30.45</RunTime>
<Prizemoney />
</Dog>
<Dog id="1634080007">
<Place>4</Place>
<DogName>MISS DEE MEADOWS</DogName>
<Trainer id="130241">S Van Oirschot</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>27.8</Weight>
<StartPrice>$20.40</StartPrice>
<Handicap />
<Margin1>5.46</Margin1>
<Margin2>3.50</Margin2>
<PIR>M/3444</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>5.54</SplitMargin>
<RunTime>30.70</RunTime>
<Prizemoney />
</Dog>
<Dog id="141319224">
<Place>5</Place>
<DogName>NOTORIOUS MAC</DogName>
<Trainer id="8042">D Douch</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>30.6</Weight>
<StartPrice>$2.20F</StartPrice>
<Handicap />
<Margin1>10.96</Margin1>
<Margin2>5.50</Margin2>
<PIR>S/5655</PIR>
<Checks>11</Checks>
<Comments />
<SplitMargin>5.61</SplitMargin>
<RunTime>31.08</RunTime>
<Prizemoney />
</Dog>
<Dog id="154151196">
<Place>6</Place>
<DogName>IT'S A THRILL</DogName>
<Trainer id="116954">J Delaroche</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>26.0</Weight>
<StartPrice>$32.70</StartPrice>
<Handicap />
<Margin1>16.73</Margin1>
<Margin2>5.77</Margin2>
<PIR>M/6566</PIR>
<Checks>7</Checks>
<Comments />
<SplitMargin>5.65</SplitMargin>
<RunTime>31.48</RunTime>
<Prizemoney />
</Dog>
<Dog id="151438359">
<Place>7</Place>
<DogName>FULL TILT</DogName>
<Trainer id="101322">B Sands</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>35.1</Weight>
<StartPrice>$11.40</StartPrice>
<Handicap />
<Margin1>19.14</Margin1>
<Margin2>2.41</Margin2>
<PIR>M/7777</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>5.80</SplitMargin>
<RunTime>31.65</RunTime>
<Prizemoney />
</Dog>
<Dog id="1621880041">
<Place>S</Place>
<DogName>MI BLUE DAY</DogName>
<Trainer id="115806">B Alford</Trainer>
<Box />
<Rug>6</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>30.31</WinTime>
<Split1Time>5.40</Split1Time>
<Split1Rug>7</Split1Rug>
<Split2Time>21.30</Split2Time>
<Split2Rug>1</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>3.00</WinDiv>
<Place1Div>1.70</Place1Div>
<Place2Div>5.10</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>14.00</Quin>
<Exacta>26.20</Exacta>
<Trifecta>153.80</Trifecta>
<Pick4>582.70</Pick4>
<RD>25.30</RD>
<DD>10.80</DD>
<Quad>116.10</Quad>
</Exotics>
</Race>
<Race id="418893624">
<RaceNum>9</RaceNum>
<RaceName>BACKMANS PET FOODS</RaceName>
<RaceTime>09:27PM</RaceTime>
<Distance>311m</Distance>
<RaceGrade>Mixed 6/7</RaceGrade>
<Dog id="118703011">
<Place>1</Place>
<DogName>GRAY GREY GOOSE</DogName>