<?xml version="1.0"?>
<!DOCTYPE Meet [<!ELEMENT Meet (Track,Date,Race+)>
<!ELEMENT Track (#PCDATA)>
<!ELEMENT Date (#PCDATA)>
<!ELEMENT Race (RaceNum,RaceName,RaceTime,Distance,RaceGrade,Dog+,Times+,Dividends+,Exotics+)>
<!ELEMENT RaceNum (#PCDATA)>
<!ELEMENT RaceName (#PCDATA)>
<!ELEMENT RaceTime (#PCDATA)>
<!ELEMENT Distance (#PCDATA)>
<!ELEMENT RaceGrade (#PCDATA)>
<!ELEMENT Dog (Place,DogName,Trainer,Box,Rug,Weight,StartPrice,Handicap,Margin1,Margin2,PIR,SplitMargin,RunTime)>
<!ELEMENT Place (#PCDATA)>
<!ELEMENT DogName (#PCDATA)>
<!ELEMENT Trainer (#PCDATA)>
<!ELEMENT Box (#PCDATA)>
<!ELEMENT Rug (#PCDATA)>
<!ELEMENT Race (#PCDATA)>
<!ELEMENT Weight (#PCDATA)>
<!ELEMENT StartPrice (#PCDATA)>
<!ELEMENT Handicap (#PCDATA)>
<!ELEMENT Margin1 (#PCDATA)>
<!ELEMENT Margin2 (#PCDATA)>
<!ELEMENT PIR (#PCDATA)>
<!ELEMENT SplitMargin (#PCDATA)>
<!ELEMENT RunTime (#PCDATA)>
<!ELEMENT Times (WinTime,Split1Time,Split1Rug,Split2Time,Split2Rug,Split3Time,Split3Rug)>
<!ELEMENT WinTime (#PCDATA)>
<!ELEMENT Split1Time (#PCDATA)>
<!ELEMENT Split1Rug (#PCDATA)>
<!ELEMENT Split2Time (#PCDATA)>
<!ELEMENT Split2Rug (#PCDATA)>
<!ELEMENT Split3Time (#PCDATA)>
<!ELEMENT Split3Rug (#PCDATA)>
<!ELEMENT Dividends (WinDiv,Place1Div,Place2Div,Place3Div)>
<!ELEMENT WinDiv (#PCDATA)>
<!ELEMENT Place1Div (#PCDATA)>
<!ELEMENT Place2Div (#PCDATA)>
<!ELEMENT Place3Div (#PCDATA)>
<!ELEMENT Exotics (Quin,Exacta,Trifecta,Pick4,RD,DD,Quad)>
<!ELEMENT Quin (#PCDATA)>
<!ELEMENT Exacta (#PCDATA)>
<!ELEMENT Trifecta (#PCDATA)>
<!ELEMENT Pick4 (#PCDATA)>
<!ELEMENT RD (#PCDATA)>
<!ELEMENT DD (#PCDATA)>
<!ELEMENT Quad (#PCDATA)>
]>
<Meet id="425059523">
<Track>Meadows (MEP)</Track>
<Date>02 Oct 19</Date>
<Race id="480283689">
<RaceNum>1</RaceNum>
<RaceName>RSN - RACING &amp; SPORT</RaceName>
<RaceTime>12:13PM</RaceTime>
<Distance>525m</Distance>
<RaceGrade>Maiden</RaceGrade>
<Dog id="344097832">
<Place>1</Place>
<DogName>SARCASMIC</DogName>
<Trainer id="113853">J Galea</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>30.8</Weight>
<StartPrice>$10.30</StartPrice>
<Handicap />
<Margin1>3.86</Margin1>
<Margin2 />
<PIR>S/7421</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>5.48</SplitMargin>
<RunTime>30.99</RunTime>
<Prizemoney />
</Dog>
<Dog id="333540756">
<Place>2</Place>
<DogName>LEAVING</DogName>
<Trainer id="142783">B Keel</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>34.1</Weight>
<StartPrice>$2.60</StartPrice>
<Handicap />
<Margin1>3.86</Margin1>
<Margin2>3.86</Margin2>
<PIR>M/1112</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>5.20</SplitMargin>
<RunTime>31.26</RunTime>
<Prizemoney />
</Dog>
<Dog id="344097835">
<Place>3</Place>
<DogName>RUN BABA RUN</DogName>
<Trainer id="113853">J Galea</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>25.3</Weight>
<StartPrice>$4.50</StartPrice>
<Handicap />
<Margin1>5.73</Margin1>
<Margin2>1.87</Margin2>
<PIR>M/5653</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.36</SplitMargin>
<RunTime>31.39</RunTime>
<Prizemoney />
</Dog>
<Dog id="344097834">
<Place>4</Place>
<DogName>ANY LUCK</DogName>
<Trainer id="113853">J Galea</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>31.6</Weight>
<StartPrice>$23.50</StartPrice>
<Handicap />
<Margin1>5.96</Margin1>
<Margin2>0.23</Margin2>
<PIR>M/2234</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.22</SplitMargin>
<RunTime>31.40</RunTime>
<Prizemoney />
</Dog>
<Dog id="327468132">
<Place>5</Place>
<DogName>MANDALORIAN</DogName>
<Trainer id="130355">J Westerlo</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>35.2</Weight>
<StartPrice>$2.50F</StartPrice>
<Handicap />
<Margin1>6.23</Margin1>
<Margin2>0.27</Margin2>
<PIR>S/6566</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.36</SplitMargin>
<RunTime>31.42</RunTime>
<Prizemoney />
</Dog>
<Dog id="234617805">
<Place>6</Place>
<DogName>SPOT ON MICK</DogName>
<Trainer id="123171">J McCallum</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>35.6</Weight>
<StartPrice>$43.20</StartPrice>
<Handicap />
<Margin1>8.56</Margin1>
<Margin2>2.33</Margin2>
<PIR>M/3345</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.29</SplitMargin>
<RunTime>31.58</RunTime>
<Prizemoney />
</Dog>
<Dog id="344097838">
<Place>7</Place>
<DogName>MADAME POOKIE</DogName>
<Trainer id="68260">T Galea</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>24.3</Weight>
<StartPrice>$45.40</StartPrice>
<Handicap />
<Margin1>11.19</Margin1>
<Margin2>2.63</Margin2>
<PIR>M/4777</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.31</SplitMargin>
<RunTime>31.77</RunTime>
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>30.99</WinTime>
<Split1Time>5.20</Split1Time>
<Split1Rug>1</Split1Rug>
<Split2Time>18.45</Split2Time>
<Split2Rug>1</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>10.30</WinDiv>
<Place1Div>3.60</Place1Div>
<Place2Div>1.70</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>5.50</Quin>
<Exacta>18.40</Exacta>
<Trifecta>81.80</Trifecta>
<Pick4>450.60</Pick4>
<RD />
<DD />
<Quad />
</Exotics>
</Race>
<Race id="480283690">
<RaceNum>2</RaceNum>
<RaceName>SEQUENTIAL PROPERTY SERVICES</RaceName>
<RaceTime>12:30PM</RaceTime>
<Distance>525m</Distance>
<RaceGrade>Maiden</RaceGrade>
<Dog id="289027904">
<Place>1</Place>
<DogName>DEWANA DEGOEY</DogName>
<Trainer id="116745">M Dewan</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>34.4</Weight>
<StartPrice>$1.20F</StartPrice>
<Handicap />
<Margin1>3.76</Margin1>
<Margin2 />
<PIR>M/2211</PIR>
<Checks>3</Checks>
<Comments />
<SplitMargin>5.26</SplitMargin>
<RunTime>30.75</RunTime>
<Prizemoney>1325.00</Prizemoney>
</Dog>
<Dog id="295448258">
<Place>2</Place>
<DogName>MY BOY WINLOCK</DogName>
<Trainer id="107126">L Delbridge</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>29.1</Weight>
<StartPrice>$5.70</StartPrice>
<Handicap />
<Margin1>3.76</Margin1>
<Margin2>3.76</Margin2>
<PIR>M/3332</PIR>
<Checks>6</Checks>
<Comments />
<SplitMargin>5.27</SplitMargin>
<RunTime>31.01</RunTime>
<Prizemoney>375.00</Prizemoney>
</Dog>
<Dog id="255489960">
<Place>3</Place>
<DogName>SON OF FABIO</DogName>
<Trainer id="67150">R Hill</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>38.2</Weight>
<StartPrice>$37.40</StartPrice>
<Handicap />
<Margin1>8.89</Margin1>
<Margin2>5.13</Margin2>
<PIR>M/5444</PIR>
<Checks>10</Checks>
<Comments />
<SplitMargin>5.39</SplitMargin>
<RunTime>31.37</RunTime>
<Prizemoney>190.00</Prizemoney>
</Dog>
<Dog id="344097839">
<Place>4</Place>
<DogName>HAS THE POWER</DogName>
<Trainer id="113853">J Galea</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>24.8</Weight>
<StartPrice>$33.80</StartPrice>
<Handicap />
<Margin1>9.47</Margin1>
<Margin2>0.59</Margin2>
<PIR>M/1123</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>5.14</SplitMargin>
<RunTime>31.41</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="344097837">
<Place>5</Place>
<DogName>CRACKED SODA</DogName>
<Trainer id="236534">J Galea</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>26.3</Weight>
<StartPrice>$19.40</StartPrice>
<Handicap />
<Margin1>13.54</Margin1>
<Margin2>4.07</Margin2>
<PIR>S/7655</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>5.42</SplitMargin>
<RunTime>31.69</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="344097840">
<Place>6</Place>
<DogName>MUSTERED COURAGE</DogName>
<Trainer id="101954">R Galea</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>24.3</Weight>
<StartPrice>$15.80</StartPrice>
<Handicap />
<Margin1>15.00</Margin1>
<Margin2>1.46</Margin2>
<PIR>M/4566</PIR>
<Checks>8</Checks>
<Comments />
<SplitMargin>5.32</SplitMargin>
<RunTime>31.80</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="344097836">
<Place>7</Place>
<DogName>GABBY GABBY</DogName>
<Trainer id="113853">J Galea</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>24.3</Weight>
<StartPrice>$46.40</StartPrice>
<Handicap />
<Margin1>26.06</Margin1>
<Margin2>11.06</Margin2>
<PIR>S/6777</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.40</SplitMargin>
<RunTime>32.57</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>30.75</WinTime>
<Split1Time>5.14</Split1Time>
<Split1Rug>4</Split1Rug>
<Split2Time>18.47</Split2Time>
<Split2Rug>1</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>1.20</WinDiv>
<Place1Div>1.04</Place1Div>
<Place2Div>1.70</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>1.90</Quin>
<Exacta>2.20</Exacta>
<Trifecta>9.10</Trifecta>
<Pick4>55.40</Pick4>
<RD>18.30</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="480283687">
<RaceNum>3</RaceNum>
<RaceName>TAB.COM.AU (1-3 WINS) (250+RANK)</RaceName>
<RaceTime>12:47PM</RaceTime>
<Distance>525m</Distance>
<RaceGrade>Restricted Win</RaceGrade>
<Dog id="257637310">
<Place>1</Place>
<DogName>ASTON SAVANNAH</DogName>
<Trainer id="109224">A Debattista</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>27.2</Weight>
<StartPrice>$2.00F</StartPrice>
<Handicap />
<Margin1>4.87</Margin1>
<Margin2 />
<PIR>Q/1111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.12</SplitMargin>
<RunTime>30.56</RunTime>
<Prizemoney />
</Dog>
<Dog id="1634010000">
<Place>2</Place>
<DogName>BUDDY'S ENTITY</DogName>
<Trainer id="65664">J Fothergill</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>31.3</Weight>
<StartPrice>$10.10</StartPrice>
<Handicap />
<Margin1>4.87</Margin1>
<Margin2>4.87</Margin2>
<PIR>M/4444</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.41</SplitMargin>
<RunTime>30.91</RunTime>
<Prizemoney />
</Dog>
<Dog id="259610187">
<Place>3</Place>
<DogName>SHOWING</DogName>
<Trainer id="142783">B Keel</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>27.1</Weight>
<StartPrice>$4.00</StartPrice>
<Handicap />
<Margin1>5.76</Margin1>
<Margin2>0.89</Margin2>
<PIR>M/2222</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>5.24</SplitMargin>
<RunTime>30.97</RunTime>
<Prizemoney />
</Dog>
<Dog id="234325216">
<Place>4</Place>
<DogName>OSHKOSH NAR</DogName>
<Trainer id="99878">S Collyer</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>38.9</Weight>
<StartPrice>$3.00</StartPrice>
<Handicap />
<Margin1>5.86</Margin1>
<Margin2>0.10</Margin2>
<PIR>M/3333</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>5.25</SplitMargin>
<RunTime>30.97</RunTime>
<Prizemoney />
</Dog>
<Dog id="259610185">
<Place>S</Place>
<DogName>PRECISELY</DogName>
<Trainer id="118267">B Fothergill</Trainer>
<Box />
<Rug>8</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>30.56</WinTime>
<Split1Time>5.12</Split1Time>
<Split1Rug>4</Split1Rug>
<Split2Time>18.16</Split2Time>
<Split2Rug>4</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.00</WinDiv>
<Place1Div>NPP</Place1Div>
<Place2Div>NPP</Place2Div>
<Place3Div>NPP</Place3Div>
</Dividends>
<Exotics>
<Quin>8.80</Quin>
<Exacta>9.10</Exacta>
<Trifecta>15.00</Trifecta>
<Pick4>22.50</Pick4>
<RD>3.60</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="480283683">
<RaceNum>4</RaceNum>
<RaceName>SKY RACING</RaceName>
<RaceTime>01:05PM</RaceTime>
<Distance>600m</Distance>
<RaceGrade>Novice Grade 7</RaceGrade>
<Dog id="289027907">
<Place>1</Place>
<DogName>DEWANA CLASSIC</DogName>
<Trainer id="114204">B Dewan</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>27.0</Weight>
<StartPrice>$2.40F</StartPrice>
<Handicap />
<Margin1>1.63</Margin1>
<Margin2 />
<PIR>Q/1111</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>8.99</SplitMargin>
<RunTime>34.68</RunTime>
<Prizemoney>1620.00</Prizemoney>
</Dog>
<Dog id="289289011">
<Place>2</Place>
<DogName>WHISPY BALE</DogName>
<Trainer id="7683">C Grenfell</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>28.3</Weight>
<StartPrice>$10.20</StartPrice>
<Handicap />
<Margin1>1.63</Margin1>
<Margin2>1.63</Margin2>
<PIR>M/2222</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>9.17</SplitMargin>
<RunTime>34.79</RunTime>
<Prizemoney>460.00</Prizemoney>
</Dog>
<Dog id="276161316">
<Place>3</Place>
<DogName>HURRICANE ARMO</DogName>
<Trainer id="62641">C Armstrong</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>30.5</Weight>
<StartPrice>$29.90</StartPrice>
<Handicap />
<Margin1>5.94</Margin1>
<Margin2>4.31</Margin2>
<PIR>Q/3554</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>9.20</SplitMargin>
<RunTime>35.09</RunTime>
<Prizemoney>230.00</Prizemoney>
</Dog>
<Dog id="286401160">
<Place>4</Place>
<DogName>POTENTE ROCKS</DogName>
<Trainer id="113168">M Briganti</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>31.3</Weight>
<StartPrice>$10.70</StartPrice>
<Handicap />
<Margin1>8.04</Margin1>
<Margin2>2.10</Margin2>
<PIR>M/4333</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>9.20</SplitMargin>
<RunTime>35.24</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="282589057">
<Place>5</Place>
<DogName>SCREEN SHOT</DogName>
<Trainer id="115397">D Pell</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>28.1</Weight>
<StartPrice>$4.50</StartPrice>
<Handicap />
<Margin1>8.10</Margin1>
<Margin2>0.06</Margin2>
<PIR>M/5445</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>9.34</SplitMargin>
<RunTime>35.24</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="300177161">
<Place>6</Place>
<DogName>OMAR LITTLE</DogName>
<Trainer id="129410">N Vincent</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>31.4</Weight>
<StartPrice>$24.60</StartPrice>
<Handicap />
<Margin1>9.61</Margin1>
<Margin2>1.51</Margin2>
<PIR>M/7777</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>9.57</SplitMargin>
<RunTime>35.35</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="315938118">
<Place>7</Place>
<DogName>TRIPLE DOUBLE</DogName>
<Trainer id="106291">L Rowe</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>34.0</Weight>
<StartPrice>$3.60</StartPrice>
<Handicap />
<Margin1>10.14</Margin1>
<Margin2>0.53</Margin2>
<PIR>M/6666</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>9.38</SplitMargin>
<RunTime>35.39</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="230422429">
<Place>S</Place>
<DogName>WAKE UP</DogName>
<Trainer id="163558">P Mathieson</Trainer>
<Box />
<Rug>1</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>34.68</WinTime>
<Split1Time>8.99</Split1Time>
<Split1Rug>2</Split1Rug>
<Split2Time>22.20</Split2Time>
<Split2Rug>2</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.40</WinDiv>
<Place1Div>2.10</Place1Div>
<Place2Div>4.50</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>12.40</Quin>
<Exacta>11.60</Exacta>
<Trifecta>69.50</Trifecta>
<Pick4>219.40</Pick4>
<RD>5.30</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="480283692">
<RaceNum>5</RaceNum>
<RaceName>MEADOWS CONFERENCE &amp; EVENTS CENTRE</RaceName>
<RaceTime>01:23PM</RaceTime>
<Distance>525m</Distance>
<RaceGrade>Mixed 6/7</RaceGrade>
<Dog id="298889605">
<Place>1</Place>
<DogName>AKASHI BOY</DogName>
<Trainer id="132247">R Douglas</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>34.7</Weight>
<StartPrice>$2.90</StartPrice>
<Handicap />
<Margin1>7.39</Margin1>
<Margin2 />
<PIR>M/1211</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.14</SplitMargin>
<RunTime>29.88</RunTime>
<Prizemoney>1405.00</Prizemoney>
</Dog>
<Dog id="287618589">
<Place>2</Place>
<DogName>LILLY LANCASTER</DogName>
<Trainer id="107126">L Delbridge</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>29.7</Weight>
<StartPrice>$2.30F</StartPrice>
<Handicap />
<Margin1>7.39</Margin1>
<Margin2>7.39</Margin2>
<PIR>M/2122</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.16</SplitMargin>
<RunTime>30.40</RunTime>
<Prizemoney>400.00</Prizemoney>
</Dog>
<Dog id="286156679">
<Place>3</Place>
<DogName>GLORIA BALE</DogName>
<Trainer id="7683">C Grenfell</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>26.4</Weight>
<StartPrice>$10.40</StartPrice>
<Handicap />
<Margin1>9.63</Margin1>
<Margin2>2.24</Margin2>
<PIR>M/3333</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>5.16</SplitMargin>
<RunTime>30.56</RunTime>
<Prizemoney>200.00</Prizemoney>
</Dog>
<Dog id="289290531">
<Place>4</Place>
<DogName>VIGOROUS</DogName>
<Trainer id="142783">B Keel</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>37.3</Weight>
<StartPrice>$5.50</StartPrice>
<Handicap />
<Margin1>9.79</Margin1>
<Margin2>0.16</Margin2>
<PIR>M/5444</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>5.21</SplitMargin>
<RunTime>30.57</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="226500597">
<Place>5</Place>
<DogName>RUSTY YAALA</DogName>
<Trainer id="69305">E Palma</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>35.4</Weight>
<StartPrice>$16.90</StartPrice>
<Handicap />
<Margin1>10.63</Margin1>
<Margin2>0.84</Margin2>
<PIR>S/6555</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.25</SplitMargin>
<RunTime>30.63</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="242072189">
<Place>6</Place>
<DogName>ROSE MIKADO</DogName>
<Trainer id="133133">M Barber</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>27.4</Weight>
<StartPrice>$34.60</StartPrice>
<Handicap />
<Margin1>14.96</Margin1>
<Margin2>4.33</Margin2>
<PIR>M/4666</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.19</SplitMargin>
<RunTime>30.93</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="230053195">
<Place>7</Place>
<DogName>KAIDE BALE</DogName>
<Trainer id="313767">C Knott</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>27.6</Weight>
<StartPrice>$29.50</StartPrice>
<Handicap />
<Margin1>16.06</Margin1>
<Margin2>1.10</Margin2>
<PIR>M/7777</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>5.32</SplitMargin>
<RunTime>31.01</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="109766099">
<Place>S</Place>
<DogName>ELLE EST BONNE</DogName>
<Trainer id="7167">M Toner</Trainer>
<Box />
<Rug>7</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>29.88</WinTime>
<Split1Time>5.14</Split1Time>
<Split1Rug>6</Split1Rug>
<Split2Time>17.95</Split2Time>
<Split2Rug>6</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>2.90</WinDiv>
<Place1Div>1.70</Place1Div>
<Place2Div>1.04</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>3.40</Quin>
<Exacta>8.60</Exacta>
<Trifecta>25.10</Trifecta>
<Pick4>57.60</Pick4>
<RD>14.30</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="480283688">
<RaceNum>6</RaceNum>
<RaceName>HOME OF TEN GROUP 1'S</RaceName>
<RaceTime>01:40PM</RaceTime>
<Distance>525m</Distance>
<RaceGrade>Grade 5</RaceGrade>
<Dog id="295447253">
<Place>1</Place>
<DogName>WINLOCK SUNSHINE</DogName>
<Trainer id="115912">M Delbridge</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>26.3</Weight>
<StartPrice>$3.00</StartPrice>
<Handicap />
<Margin1>1.40</Margin1>
<Margin2 />
<PIR>M/1111</PIR>
<Checks>2</Checks>
<Comments />
<SplitMargin>5.10</SplitMargin>
<RunTime>30.29</RunTime>
<Prizemoney>1405.00</Prizemoney>
</Dog>
<Dog id="166063600">
<Place>2</Place>
<DogName>MANNY ALLEN</DogName>
<Trainer id="296441">W Green</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>34.2</Weight>
<StartPrice>$33.90</StartPrice>
<Handicap />
<Margin1>1.40</Margin1>
<Margin2>1.40</Margin2>
<PIR>S/6222</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.24</SplitMargin>
<RunTime>30.39</RunTime>
<Prizemoney>400.00</Prizemoney>
</Dog>
<Dog id="219001638">
<Place>3</Place>
<DogName>WILBURY</DogName>
<Trainer id="128667">C Elliot</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>28.8</Weight>
<StartPrice>$18.90</StartPrice>
<Handicap />
<Margin1>2.26</Margin1>
<Margin2>0.86</Margin2>
<PIR>S/8433</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.31</SplitMargin>
<RunTime>30.45</RunTime>
<Prizemoney>200.00</Prizemoney>
</Dog>
<Dog id="243599802">
<Place>4</Place>
<DogName>WINLOCK NEWBOLT</DogName>
<Trainer id="115912">M Delbridge</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>30.5</Weight>
<StartPrice>$7.40</StartPrice>
<Handicap />
<Margin1>5.53</Margin1>
<Margin2>3.27</Margin2>
<PIR>S/7755</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>5.26</SplitMargin>
<RunTime>30.68</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="226500601">
<Place>5</Place>
<DogName>ROSIE YAALA</DogName>
<Trainer id="108647">M Lloyd</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>27.9</Weight>
<StartPrice>$40.10</StartPrice>
<Handicap />
<Margin1>5.57</Margin1>
<Margin2>0.04</Margin2>
<PIR>M/2344</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>5.12</SplitMargin>
<RunTime>30.68</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="2018280008">
<Place>6</Place>
<DogName>MILITANT SPIRIT</DogName>
<Trainer id="122784">K Hunt</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>29.5</Weight>
<StartPrice>$1.70F</StartPrice>
<Handicap />
<Margin1>6.86</Margin1>
<Margin2>1.29</Margin2>
<PIR>M/3566</PIR>
<Checks>9</Checks>
<Comments />
<SplitMargin>5.14</SplitMargin>
<RunTime>30.77</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="2043510004">
<Place>7</Place>
<DogName>HOO GUR AFFAIR</DogName>
<Trainer id="130881">M Hanke</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>30.6</Weight>
<StartPrice>$56.70</StartPrice>
<Handicap />
<Margin1>11.10</Margin1>
<Margin2>4.24</Margin2>
<PIR>M/4677</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>5.17</SplitMargin>
<RunTime>31.07</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="151439835">
<Place>8</Place>
<DogName>SMART MARY</DogName>
<Trainer id="132216">J Frewin</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>30.0</Weight>
<StartPrice>$46.00</StartPrice>
<Handicap />
<Margin1>12.59</Margin1>
<Margin2>1.49</Margin2>
<PIR>M/5888</PIR>
<Checks>7</Checks>
<Comments />
<SplitMargin>5.21</SplitMargin>
<RunTime>31.18</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>30.29</WinTime>
<Split1Time>5.10</Split1Time>
<Split1Rug>4</Split1Rug>
<Split2Time>18.01</Split2Time>
<Split2Rug>4</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>3.00</WinDiv>
<Place1Div>1.04</Place1Div>
<Place2Div>3.10</Place2Div>
<Place3Div>3.00</Place3Div>
</Dividends>
<Exotics>
<Quin>34.60</Quin>
<Exacta>63.80</Exacta>
<Trifecta>240.10</Trifecta>
<Pick4>948.50</Pick4>
<RD>19.80</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="480283691">
<RaceNum>7</RaceNum>
<RaceName>FEIKUAI GREYHOUNDS</RaceName>
<RaceTime>01:55PM</RaceTime>
<Distance>525m</Distance>
<RaceGrade>Mixed 3/4</RaceGrade>
<Dog id="227854801">
<Place>1</Place>
<DogName>TITANIUM LAD</DogName>
<Trainer id="62838">K Howat</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>32.7</Weight>
<StartPrice>$5.00</StartPrice>
<Handicap />
<Margin1>0.27</Margin1>
<Margin2 />
<PIR>M/2222</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.17</SplitMargin>
<RunTime>30.21</RunTime>
<Prizemoney>1650.00</Prizemoney>
</Dog>
<Dog id="134886250">
<Place>2</Place>
<DogName>WINSOME EXPRESS</DogName>
<Trainer id="115912">M Delbridge</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>32.2</Weight>
<StartPrice>$14.60</StartPrice>
<Handicap />
<Margin1>0.27</Margin1>
<Margin2>0.27</Margin2>
<PIR>M/1111</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.12</SplitMargin>
<RunTime>30.23</RunTime>
<Prizemoney>475.00</Prizemoney>
</Dog>
<Dog id="128010524">
<Place>3</Place>
<DogName>UNDISPUTED</DogName>
<Trainer id="69179">D Mowat</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>35.1</Weight>
<StartPrice>$18.70</StartPrice>
<Handicap />
<Margin1>0.71</Margin1>
<Margin2>0.44</Margin2>
<PIR>M/6543</PIR>
<Checks>9</Checks>
<Comments />
<SplitMargin>5.25</SplitMargin>
<RunTime>30.26</RunTime>
<Prizemoney>235.00</Prizemoney>
</Dog>
<Dog id="172047912">
<Place>4</Place>
<DogName>KINLOCH MOSS</DogName>
<Trainer id="112239">D Geall</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>32.6</Weight>
<StartPrice>$3.40</StartPrice>
<Handicap />
<Margin1>3.80</Margin1>
<Margin2>3.09</Margin2>
<PIR>M/4434</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>5.24</SplitMargin>
<RunTime>30.48</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="163484323">
<Place>5</Place>
<DogName>MIMSTAR</DogName>
<Trainer id="108219">K Lloyd</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>27.4</Weight>
<StartPrice>$18.90</StartPrice>
<Handicap />
<Margin1>4.96</Margin1>
<Margin2>1.16</Margin2>
<PIR>M/5666</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>5.24</SplitMargin>
<RunTime>30.56</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="163762389">
<Place>6</Place>
<DogName>DAKORA</DogName>
<Trainer id="108469">D Webber</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>35.3</Weight>
<StartPrice>$1.90F</StartPrice>
<Handicap />
<Margin1>6.11</Margin1>
<Margin2>1.16</Margin2>
<PIR>M/3355</PIR>
<Checks>1</Checks>
<Comments />
<SplitMargin>5.19</SplitMargin>
<RunTime>30.64</RunTime>
<Prizemoney>0.00</Prizemoney>
</Dog>
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Dog id="" />
<Times>
<WinTime>30.21</WinTime>
<Split1Time>5.12</Split1Time>
<Split1Rug>8</Split1Rug>
<Split2Time>17.90</Split2Time>
<Split2Rug>8</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>5.00</WinDiv>
<Place1Div>1.90</Place1Div>
<Place2Div>4.80</Place2Div>
<Place3Div>NTD</Place3Div>
</Dividends>
<Exotics>
<Quin>18.80</Quin>
<Exacta>31.20</Exacta>
<Trifecta>168.00</Trifecta>
<Pick4>288.90</Pick4>
<RD>37.70</RD>
<DD />
<Quad />
</Exotics>
</Race>
<Race id="480283693">
<RaceNum>8</RaceNum>
<RaceName>DOWNLOAD THE NEW WATCHDOG APP</RaceName>
<RaceTime>02:15PM</RaceTime>
<Distance>600m</Distance>
<RaceGrade>Mixed 4/5</RaceGrade>
<Dog id="109766094">
<Place>1</Place>
<DogName>HUNKAPAPA</DogName>
<Trainer id="113168">M Briganti</Trainer>
<Box>3</Box>
<Rug>3</Rug>
<Weight>34.4</Weight>
<StartPrice>$4.00</StartPrice>
<Handicap />
<Margin1>0.34</Margin1>
<Margin2 />
<PIR>M/3221</PIR>
<Checks>6</Checks>
<Comments />
<SplitMargin>9.18</SplitMargin>
<RunTime>34.86</RunTime>
<Prizemoney />
</Dog>
<Dog id="139788539">
<Place>2</Place>
<DogName>LOCHINVAR DEUS</DogName>
<Trainer id="66497">J Formosa</Trainer>
<Box>6</Box>
<Rug>6</Rug>
<Weight>33.6</Weight>
<StartPrice>$5.90</StartPrice>
<Handicap />
<Margin1>0.34</Margin1>
<Margin2>0.34</Margin2>
<PIR>S/7753</PIR>
<Checks>5</Checks>
<Comments />
<SplitMargin>9.34</SplitMargin>
<RunTime>34.88</RunTime>
<Prizemoney />
</Dog>
<Dog id="202027751">
<Place>3</Place>
<DogName>ROCKET JAX</DogName>
<Trainer id="108648">G Mitchell</Trainer>
<Box>2</Box>
<Rug>2</Rug>
<Weight>31.6</Weight>
<StartPrice>$4.60</StartPrice>
<Handicap />
<Margin1>3.64</Margin1>
<Margin2>3.30</Margin2>
<PIR>M/2466</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>9.11</SplitMargin>
<RunTime>35.11</RunTime>
<Prizemoney />
</Dog>
<Dog id="258682341">
<Place>4</Place>
<DogName>SUPER BLU</DogName>
<Trainer id="112239">D Geall</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>30.5</Weight>
<StartPrice>$12.70</StartPrice>
<Handicap />
<Margin1>3.83</Margin1>
<Margin2>0.19</Margin2>
<PIR>M/1112</PIR>
<Checks>10</Checks>
<Comments />
<SplitMargin>9.04</SplitMargin>
<RunTime>35.12</RunTime>
<Prizemoney />
</Dog>
<Dog id="2043510010">
<Place>5</Place>
<DogName>SHELLBROOK</DogName>
<Trainer id="118680">W Bocquet</Trainer>
<Box>5</Box>
<Rug>5</Rug>
<Weight>28.3</Weight>
<StartPrice>$33.10</StartPrice>
<Handicap />
<Margin1>4.19</Margin1>
<Margin2>0.36</Margin2>
<PIR>M/4334</PIR>
<Checks>10</Checks>
<Comments />
<SplitMargin>9.18</SplitMargin>
<RunTime>35.15</RunTime>
<Prizemoney />
</Dog>
<Dog id="1619850000">
<Place>6</Place>
<DogName>SO AMAZING</DogName>
<Trainer id="130148">T Womann</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>31.7</Weight>
<StartPrice>$32.40</StartPrice>
<Handicap />
<Margin1>4.86</Margin1>
<Margin2>0.67</Margin2>
<PIR>M/5677</PIR>
<Checks>9</Checks>
<Comments />
<SplitMargin>9.22</SplitMargin>
<RunTime>35.20</RunTime>
<Prizemoney />
</Dog>
<Dog id="212745246">
<Place>7</Place>
<DogName>DYNA BONNAY</DogName>
<Trainer id="115912">M Delbridge</Trainer>
<Box>8</Box>
<Rug>8</Rug>
<Weight>25.5</Weight>
<StartPrice>$3.40F</StartPrice>
<Handicap />
<Margin1>5.69</Margin1>
<Margin2>0.83</Margin2>
<PIR>M/6545</PIR>
<Checks>12</Checks>
<Comments />
<SplitMargin>9.23</SplitMargin>
<RunTime>35.25</RunTime>
<Prizemoney />
</Dog>
<Dog id="109766100">
<Place>P</Place>
<DogName>ITA LOUISA</DogName>
<Trainer id="130410">D Toner</Trainer>
<Box>1</Box>
<Rug>1</Rug>
<Weight>28.0</Weight>
<StartPrice>$9.30</StartPrice>
<Handicap />
<Margin1 />
<Margin2 />
<PIR>M/8888</PIR>
<Checks>4</Checks>
<Comments />
<SplitMargin>9.93</SplitMargin>
<RunTime />
<Prizemoney />
</Dog>
<Dog id="284105087">
<Place>R</Place>
<DogName>NICKO EXPRESS</DogName>
<Trainer id="114910">T Dahl</Trainer>
<Box />
<Rug>9</Rug>
<Weight />
<StartPrice />
<Handicap />
<Margin1 />
<Margin2 />
<PIR />
<Checks>0</Checks>
<Comments />
<SplitMargin />
<RunTime />
<Prizemoney />
</Dog>
<Dog id="" />
<Times>
<WinTime>34.86</WinTime>
<Split1Time>9.04</Split1Time>
<Split1Rug>4</Split1Rug>
<Split2Time>22.20</Split2Time>
<Split2Rug>4</Split2Rug>
<Split3Time />
<Split3Rug />
</Times>
<Dividends>
<WinDiv>4.00</WinDiv>
<Place1Div>1.20</Place1Div>
<Place2Div>2.40</Place2Div>
<Place3Div>1.40</Place3Div>
</Dividends>
<Exotics>
<Quin>14.90</Quin>
<Exacta>31.30</Exacta>
<Trifecta>106.10</Trifecta>
<Pick4>550.70</Pick4>
<RD>26.00</RD>
<DD>20.30</DD>
<Quad>260.60</Quad>
</Exotics>
</Race>
<Race id="480283684">
<RaceNum>9</RaceNum>
<RaceName>AJS CORPORATION HT1 (NCW)</RaceName>
<RaceTime>02:30PM</RaceTime>
<Distance>525m</Distance>
<RaceGrade>Grade 5 Heat</RaceGrade>
<Dog id="319674574">
<Place>1</Place>
<DogName>SHADOW MIST</DogName>
<Trainer id="132247">R Douglas</Trainer>
<Box>7</Box>
<Rug>7</Rug>
<Weight>36.9</Weight>
<StartPrice>$2.90</StartPrice>
<Handicap />
<Margin1>5.83</Margin1>
<Margin2 />
<PIR>M/4111</PIR>
<Checks>0</Checks>
<Comments />
<SplitMargin>5.19</SplitMargin>
<RunTime>30.04</RunTime>
<Prizemoney />
</Dog>
<Dog id="190934616">
<Place>2</Place>
<DogName>NATE'S AWESOME</DogName>
<Trainer id="130142">G Wood</Trainer>
<Box>4</Box>
<Rug>4</Rug>
<Weight>34.8</Weight>
<StartPrice>$2.30F</StartPrice>
<Handicap />
<Margin1>5.83</Margin1>
<Margin2>5.83</Margin2>
<PIR>M/2333</PIR>